### ISSUE TITLE
Question: Is there a way to replace a tag or value?

### ISSUE THREAD

**Issue by WorksWellWithOthers** [danielaparker/jsoncons#100]
Hello, I was wondering if there was a method to replace a tag or value.
I couldn't seem to find one so I am attempting to use std::replace and am concerned about picking the correct tag/value in a large json structure with duplicate names.

{"store":  
    {"book": [  
        {"category": "reference",  
            "author": "Margaret Weis",  
            "title": "Dragonlance Series",  
            "price": 31.96}, {"category": "reference",  
            "author": "Brent Weeks",  
            "title": "Night Angel Trilogy",  
            "price": 14.70  
        }]}}')

**Comment by WorksWellWithOthers** [comment]
I'm thinking of having the target word replaced once the user set keyword is triggered/detected.

**Comment by danielaparker** [comment]
It's a good question.

For values, with what we support now, you could do something like this:
```c++
int main()
{
    json j;
    try
    {
        j = json::parse(R"(
{"store":
{"book": [
{"category": "reference",
"author": "Margaret Weis",
"title": "Dragonlance Series",
"price": 31.96}, {"category": "reference",
"author": "Brent Weeks",
"title": "Night Angel Trilogy",
"price": 14.70
}]}}
)");
    }
    catch (const parse_exception& e)
    {
        std::cout << e.what() << std::endl;
    }

    std::cout << ("1\n") << pretty_print(j) << std::endl;

    try
    {
        for (auto& book : j["store"]["book"].elements())
        {
            if (book["price"].as<double>() == 31.96)
            {
                book["price"] = 30.90;
            }
        }
    }
    catch (const std::exception& e)
    {
        std::cout << e.what() << std::endl;
    }

    std::cout << ("2\n") << pretty_print(j) << std::endl;
}
```
But I think we could add a companion function to` json_query`,
```c++
template <class T>
void replace(json& root, const char* jsonpath, T&& new_value); 
```
that would allow you to replace all values matched by the jsonpath expression with the new value,
so you could write something like
```c++
replace(j,"$..book[?(@.price==31.96)].price", 30.9);
```
For member names, you can't change them in a json value, they're immutable. You could use a filter for that, see the tutorial (Transforming JSON with filters)[https://github.com/danielaparker/jsoncons/wiki/Transforming%20JSON%20with%20filters]

You could override `do_name` as
```c++
    void do_name(const char* p, size_t length, 
                           const parsing_context& context) override
    {
        property_name_ = string(p,length);
        if (string(p,length) == "price")
        {
            input_handler().name("price2", context);
        }
    }
```

**Comment by WorksWellWithOthers** [comment]
Thank you!

**Comment by danielaparker** [comment]
I've added `json_replace` in latest master, which allows you to replace values that match a jsonpath expression, you can find the example here

`examples\src\jsonpath_examples.cpp`

**Comment by WorksWellWithOthers** [comment]
=)

**Comment by WorksWellWithOthers** [comment]
Question: 

It might be a mistake on my part but i'm getting a build error stating that 

jsonpath_evaluator<Json> evaluator; should have 3 arguments in its parameter and not 1.

**Comment by danielaparker** [comment]
Can you try again?

**Comment by WorksWellWithOthers** [comment]
Warning: I did not do a git pull and instead copy pasted the RAW.

error: jsoncons_ext/jsonpath/jsonpath_filter.hpp:475:32: error: wrong number of template arguments (1, should be 3)
         jsonpath_evaluator<Json> evaluator;

**Comment by danielaparker** [comment]
jsonpath_filter.hpp:475:32 You should see

template <class Json,
          class JsonReference,
          class JsonPointer>
class jsonpath_evaluator;

Three template parameters, it used to have one.

**Comment by WorksWellWithOthers** [comment]
Hmm weird. I still see one. I just cloned.

    void initialize(const Json& context_node) override
    {
        jsonpath_evaluator<Json> evaluator;
        evaluator.evaluate(context_node,path_);
        nodes_ = evaluator.get_values();
    }

is what I have.

**Comment by WorksWellWithOthers** [comment]
I have that template at line 22

**Comment by WorksWellWithOthers** [comment]
#include "jsoncons/json.hpp"
#include "jsonpath_error_category.hpp"

namespace jsoncons { namespace jsonpath {

template <class Json,
          class JsonReference,
          class JsonPointer>
class jsonpath_evaluator;

**Comment by danielaparker** [comment]
Oh, okay, try again.

**Comment by WorksWellWithOthers** [comment]
It's building. Thank you.

**Comment by danielaparker** [comment]
I've also added a built in filter `rename_name_filter` for changing object member names, see [Transforming JSON with filters](https://github.com/danielaparker/jsoncons/wiki/Transforming%20JSON%20with%20filters).
