### ISSUE TITLE
Compilation errors under macOS 10.12.2

### ISSUE THREAD

**Issue by yplaksyuk** [danielaparker/jsoncons#107]
Building examples:

fire:debug yplaksyuk$ cmake -DCMAKE_BUILD_TYPE=debug -DBUILD_STATIC_LIBS=ON -DBUILD_SHARED_LIBS=OFF -DARCHIVE_INSTALL_DIR=. -G "Unix Makefiles" ..
-- The CXX compiler identification is AppleClang 8.0.0.8000042
-- Check for working CXX compiler: /usr/bin/clang++
-- Check for working CXX compiler: /usr/bin/clang++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    ARCHIVE_INSTALL_DIR
    BUILD_SHARED_LIBS
    BUILD_STATIC_LIBS

-- Build files have been written to: /Users/yplaksyuk/local/j/jsoncons/examples/build/cmake/debug
fire:debug yplaksyuk$ make 
Scanning dependencies of target jsoncons_examples
[  6%] Building CXX object CMakeFiles/jsoncons_examples.dir/Users/yplaksyuk/local/j/jsoncons/examples/src/array_examples.cpp.o
[ 13%] Building CXX object CMakeFiles/jsoncons_examples.dir/Users/yplaksyuk/local/j/jsoncons/examples/src/basics_examples.cpp.o
In file included from /Users/yplaksyuk/local/j/jsoncons/examples/src/basics_examples.cpp:5:
In file included from /Users/yplaksyuk/local/j/jsoncons/examples/build/cmake/../../../src/jsoncons/json.hpp:20:
In file included from /Users/yplaksyuk/local/j/jsoncons/examples/build/cmake/../../../src/jsoncons/jsoncons.hpp:18:
/Users/yplaksyuk/local/j/jsoncons/examples/build/cmake/../../../src/jsoncons/unicode_traits.hpp:1106:25: error: incompatible operand types
      ('const wchar_t' and 'std::pair<const wchar_t *, size_t>' (aka 'pair<const wchar_t *, unsigned long>'))
    return index < size ? *(first+size) : std::pair<InputIt,size_t>(last,0);
                        ^ ~~~~~~~~~~~~~   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/Users/yplaksyuk/local/j/jsoncons/examples/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:237:46: note: in instantiation of
      function template specialization 'unicons::sequence_at<const wchar_t *>' requested here
                    auto sequence = unicons::sequence_at(s.data(), s.data() + s.size(), index);
                                             ^
/Users/yplaksyuk/local/j/jsoncons/examples/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:169:26: note: in instantiation of
      member function 'jsoncons::jsonpath::jsonpath_evaluator<jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>,
      std::__1::allocator<wchar_t> >, const jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> > &,
      const jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> > *>::name_selector::select'
      requested here
                selector.select(context, nodes, temp_json_values);
                         ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:2125:7: note: in instantiation of member function
      'jsoncons::jsonpath::jsonpath_evaluator<jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> >,
      const jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> > &, const
      jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> > *>::expr_selector::select' requested here
class __libcpp_compressed_pair_imp<_T1, _T2, 1>
      ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:4411:26: note: in instantiation of function template specialization
      'std::__1::__shared_ptr_emplace<jsoncons::jsonpath::jsonpath_evaluator<jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>,
      std::__1::allocator<wchar_t> >, const jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> > &,
      const jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> > *>::expr_selector,
      std::__1::allocator<jsoncons::jsonpath::jsonpath_evaluator<jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>,
      std::__1::allocator<wchar_t> >, const jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> > &,
      const jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> > *>::expr_selector>
      >::__shared_ptr_emplace<jsoncons::jsonpath::jsonpath_filter_expr<jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>,
      std::__1::allocator<wchar_t> > > &>' requested here
    ::new(__hold2.get()) _CntrlBlk(__a2, _VSTD::forward<_Args>(__args)...);
                         ^
/Library/Developer/CommandLineTools/usr/bin/../include/c++/v1/memory:4775:29: note: in instantiation of function template specialization
      'std::__1::shared_ptr<jsoncons::jsonpath::jsonpath_evaluator<jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>,
      std::__1::allocator<wchar_t> >, const jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> > &,
      const jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> >
      *>::expr_selector>::make_shared<jsoncons::jsonpath::jsonpath_filter_expr<jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>,
      std::__1::allocator<wchar_t> > > &>' requested here
    return shared_ptr<_Tp>::make_shared(_VSTD::forward<_Args>(__args)...);
                            ^
/Users/yplaksyuk/local/j/jsoncons/examples/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:562:51: note: in instantiation of
      function template specialization 'std::__1::make_shared<jsoncons::jsonpath::jsonpath_evaluator<jsoncons::basic_json<wchar_t,
      jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> >, const jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>,
      std::__1::allocator<wchar_t> > &, const jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> >
      *>::expr_selector, jsoncons::jsonpath::jsonpath_filter_expr<jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>,
      std::__1::allocator<wchar_t> > > &>' requested here
                        selectors_.push_back(std::make_shared<expr_selector>(result));
                                                  ^
/Users/yplaksyuk/local/j/jsoncons/examples/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:83:15: note: in instantiation of
      member function 'jsoncons::jsonpath::jsonpath_evaluator<jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>,
      std::__1::allocator<wchar_t> >, const jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> > &,
      const jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> > *>::evaluate' requested here
    evaluator.evaluate(root,path.data(),path.length());
              ^
/Users/yplaksyuk/local/j/jsoncons/examples/src/basics_examples.cpp:297:20: note: in instantiation of function template specialization
      'jsoncons::jsonpath::json_query<jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> > >'
      requested here
    wjson result = json_query(booklist, L"$[*][?(@.price < 12)].author");
                   ^
In file included from /Users/yplaksyuk/local/j/jsoncons/examples/src/basics_examples.cpp:6:
/Users/yplaksyuk/local/j/jsoncons/examples/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:942:33: error: no matching function
      for call to 'sequence_at'
                auto sequence = unicons::sequence_at(s.data(), s.data() + s.size(), pos);
                                ^~~~~~~~~~~~~~~~~~~~
/Users/yplaksyuk/local/j/jsoncons/examples/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:883:17: note: in instantiation of
      member function 'jsoncons::jsonpath::jsonpath_evaluator<jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>,
      std::__1::allocator<wchar_t> >, const jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> > &,
      const jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> > *>::apply_unquoted_string'
      requested here
                apply_unquoted_string(*(stack_.back()[i]), name);
                ^
/Users/yplaksyuk/local/j/jsoncons/examples/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:740:21: note: in instantiation of
      member function 'jsoncons::jsonpath::jsonpath_evaluator<jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>,
      std::__1::allocator<wchar_t> >, const jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> > &,
      const jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> > *>::apply_unquoted_string'
      requested here
                    apply_unquoted_string(buffer_);
                    ^
/Users/yplaksyuk/local/j/jsoncons/examples/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:83:15: note: in instantiation of
      member function 'jsoncons::jsonpath::jsonpath_evaluator<jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>,
      std::__1::allocator<wchar_t> >, const jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> > &,
      const jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> > *>::evaluate' requested here
    evaluator.evaluate(root,path.data(),path.length());
              ^
/Users/yplaksyuk/local/j/jsoncons/examples/src/basics_examples.cpp:297:20: note: in instantiation of function template specialization
      'jsoncons::jsonpath::json_query<jsoncons::basic_json<wchar_t, jsoncons::json_traits<wchar_t>, std::__1::allocator<wchar_t> > >'
      requested here
    wjson result = json_query(booklist, L"$[*][?(@.price < 12)].author");
                   ^
/Users/yplaksyuk/local/j/jsoncons/examples/build/cmake/../../../src/jsoncons/unicode_traits.hpp:1084:32: note: candidate template ignored:
      disabled by 'enable_if' [with InputIt = const wchar_t *]
static typename std::enable_if<std::is_integral<typename std::iterator_traits<InputIt>::value_type>::value 
                               ^
/Users/yplaksyuk/local/j/jsoncons/examples/build/cmake/../../../src/jsoncons/unicode_traits.hpp:1103:1: note: candidate template ignored:
      substitution failure [with InputIt = const wchar_t *]
sequence_at(InputIt first, InputIt last, size_t index) 
^
2 errors generated.
make[2]: *** [CMakeFiles/jsoncons_examples.dir/Users/yplaksyuk/local/j/jsoncons/examples/src/basics_examples.cpp.o] Error 1
make[1]: *** [CMakeFiles/jsoncons_examples.dir/all] Error 2
make: *** [all] Error 2

**Comment by danielaparker** [comment]
Thanks for reporting this. It should be fixed on master, please let me know if you still see an issue.

Daniel
