### ISSUE TITLE
compiler errors on V0.99.6 with g++ 5.4.1 on Ubuntu 16.04

### ISSUE THREAD

**Issue by jeffreyscottgraham** [danielaparker/jsoncons#109]
/x86_64.Linux.Ubuntu.16/jsoncons/include/jsoncons/json_error_category.hpp:50:32: error: expected ‘;’ at end of member declaration
     virtual const char* name() const JSONCONS_NOEXCEPT
                                ^
y/x86_64.Linux.Ubuntu.16/jsoncons/include/jsoncons/json_error_category.hpp:50:38: error: ‘JSONCONS_NOEXCEPT’ does not name a type
     virtual const char* name() const JSONCONS_NOEXCEPT
                                      ^
y/x86_64.Linux.Ubuntu.16/jsoncons/include/jsoncons/json_error_category.hpp:50:25: error: looser throw specifier for ‘virtual const char* jsoncons::json_error_category_impl::name() const’
     virtual const char* name() const JSONCONS_NOEXCEPT
                         ^
In file included from /usr/include/c++/5/bits/ios_base.h:46:0,
                 from /usr/include/c++/5/ios:42,
                 from /usr/include/c++/5/ostream:38,
                 from /usr/include/c++/5/iostream:39,
                 from testSuggestProcedure.cpp:1:
/usr/include/c++/5/system_error:77:5: error:   overriding ‘virtual const char* std::_V2::error_category::name() const noexcept’
     name() const noexcept = 0;
     ^
/makefiles/post.mak:102: recipe for target 'testSuggestProcedure.o' failed

**Comment by danielaparker** [comment]
This should be fixed on master. There'll be a 0.99.7 release shortly.
