### ISSUE TITLE
jsonpath fails to evaluate complex expressions

### ISSUE THREAD

**Issue by yplaksyuk** [danielaparker/jsoncons#110]
**Example:** [?(@.FieldA == 'A' && @.FieldB == 'B')] doesn't work, because **==** and **&&** have the same precedence (see **jsonpath_filter_expr::make_term** in _jsonpath_filter.hpp_). It is evaluated as

[?(((@.FieldA == 'A') && @.FieldB) == 'B')]

**Workaround:** explicitly define precedence using parens:

[?((@.FieldA == 'A') && (@.FieldB == 'B'))]

**Comment by danielaparker** [comment]
Thanks for reporting this. That needs to be fixed.

**Comment by danielaparker** [comment]
This issue has been fixed on master. The precedence order is now

Precedence|Operator|Associativity
----------|--------|-----------
1 |`!` unary `-`    |Right
2 |`=~`             |Left
3 |`+` `-`          |Left 
4 |`<` `>` `<=` `>=`|Left 
5 |`==` `!=`        |Left 
6 |`&&`             |Left 
7 |`||`             |Left
