### ISSUE TITLE
How can i use string variable in json_query?

### ISSUE THREAD

**Issue by NickyVSTaiMokWong09** [danielaparker/jsoncons#112]
I've tried reading tutorials  but still didn't find it.
Hope you can help me!

**Comment by danielaparker** [comment]
You can pass an std::string variable everywhere you see a string literal in the examples, e.g. instead of

result = json_query(booklist, "$[2]"); 

you can write

std::string s = "$[2]";
result = json_query(booklist, s);

**Comment by NickyVSTaiMokWong09** [comment]
Thankyyyy!

I know this is a stupid question,but thank for you timely reply.
