### ISSUE TITLE
error with GCC 6.2

### ISSUE THREAD

**Issue by cenit** [danielaparker/jsoncons#118]
First of all, thank you so much for this wonderful library. I am a longtime user and this is the first issue I have.
Using newer gcc (both 5.x and also the supported 6.2) the library unfortunately fails with this error

```
./jsoncons/src/jsoncons/unicode_traits.hpp:1387:12: error: specialization of ‘std::is_error_code_enum<unicons::conv_errc>’ after instantiation
     struct is_error_code_enum<unicons::conv_errc> : public true_type
            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
./jsoncons/src/jsoncons/unicode_traits.hpp:1387:12: error: redefinition of ‘struct std::is_error_code_enum<unicons::conv_errc>’
In file included from /usr/include/c++/6/bits/ios_base.h:46:0,
                 from /usr/include/c++/6/ios:42,
                 from /usr/include/c++/6/ostream:38,
                 from /usr/include/c++/6/iostream:39,
                 from /home/travis/build/......:
/usr/include/c++/6/system_error:53:12: error: previous definition of ‘struct std::is_error_code_enum<unicons::conv_errc>’
     struct is_error_code_enum : public false_type { };
            ^~~~~~~~~~~~~~~~~~
```

A manual solution that I adopt is just to remove this snippet of code from unicode_traits.hpp:
```
namespace std {
    template<>
    struct is_error_code_enum<unicons::conv_errc> : public true_type
    {
    };
    template<>
    struct is_error_code_enum<unicons::encoding_errc> : public true_type
    {
    };
}
```
but I don't think that it is a real good solution!
On clang it works, but I need to support also GCC
Do you have any advice?

Best regards

**Comment by cenit** [comment]
Sorry, fixed. Just including <iostream> before <jsoncons/json.hpp> did the trick

**Comment by danielaparker** [comment]
It may also be related to the `is_error_code_enum` specializations being at the end of the `unicode_traits.hpp` file, after instantiation in the body, as the error message suggests. In any case I've moved those specializations up immediately below the definitions of the `conv_errc` and `encoding_errc` error codes, on master.

**Comment by cenit** [comment]
just saw it 51b0944
thank you very much again!
