### ISSUE TITLE
json_query doesn't support returning normalized path expressions

### ISSUE THREAD

**Issue by GetJon** [danielaparker/jsoncons#119]
Goessner's JSONPath supports returning [normalized path expressions](http://goessner.net/articles/JsonPath/index.html#e4) rather than values, which would be very useful to have in json_query!

**Comment by danielaparker** [comment]
Thanks for the suggestion, we'll look into it.

**Comment by danielaparker** [comment]
On master, `json_query` now supports returning normalized path expressions, with the optional third parameter value `result_type::path`.  E.g.
```c++
using namespace jsoncons;
using namespace jsoncons::jsonpath;

std::string path = "$.store.book[?(@.price < 10)].title";
json result = json_query(store,path,result_type::path);
```
