### ISSUE TITLE
json_query error

### ISSUE THREAD

**Issue by pfi79** [danielaparker/jsoncons#122]
json:
{ "store": {
    "book": {
      "aaa":{ "category": "reference",
        "author": "Nigel Rees",
        "title": "Sayings of the Century",
        "price": 8.95
      },
      "bbb":{ "category": "fiction",
        "author": "Evelyn Waugh",
        "title": "Sword of Honour",
        "price": 12.99
      },
      "ccc":{ "category": "fiction",
        "author": "Herman Melville",
        "title": "Moby Dick",
        "isbn": "0-553-21311-3",
        "price": 8.99
      },
      "ddd":{ "category": "fiction",
        "author": "J. R. R. Tolkien",
        "title": "The Lord of the Rings",
        "isbn": "0-395-19395-8",
        "price": 22.99
      }
    }
  }
}

query:
"$..book[?(@.author == 'Nigel Rees')].title"

return:
[]

should return:
["Sayings of the Century"]

**Comment by danielaparker** [comment]
Thanks for reporting this. I compared with the online [jsonpath evaluator](https://jsonpath.herokuapp.com/). Interestingly, using your version of the store, the usually correct jayway produces the same result as jsoncons, but Goessner gives your, and I believe correct, result.

**Comment by danielaparker** [comment]
I also compared with the [JSONPATH Expression Tester](https://jsonpath.curiousconcept.com/), which compares Flow Communications' implementations and Stefan Goessner implementations. This time, using your version of the store, the Stefan Goessner implementations fail with your query, while the Flow Communications' implementations return your result.

**Comment by danielaparker** [comment]
My own understanding is that jsoncons and jayway are correct (to the extent that that means anything in the absence of a formal specification.) I think the recursive descent implied by `$..book` has to stop at book.

**Comment by pfi79** [comment]
Thank you.
When you change the book from the object to the array, the query changes 
object:
$..book..[?(@.author == 'Nigel Rees')].title
Array:
$..book[?(@.author == 'Nigel Rees')].title

It seems to me that this is not beautiful

**Comment by danielaparker** [comment]
I think it's consistent. With the object, the query has to get through the additional keys that aren't explicitly in the query, "aaa" etc, and needs recursive descent to do that. With the array, everything is right where it's needed, and further recursive descent isn't required.
