### ISSUE TITLE
Issue with strtod_l and Android STL

### ISSUE THREAD

**Issue by Phaestion** [danielaparker/jsoncons#124]
Hi there!

I seem to have picked up an issue with your latest release. When compiling on Android with the "c++_static" STL, which is LLVM's libc++, I get the following compilation error:
`use of undeclared identifier 'strtod_l'; did you mean 'strtold_l'?`

By simply changing it to "strtold_l" compilation succeeds and all of my tests pass. Is "strtod_l" part of C++11? 

Regards

**Comment by danielaparker** [comment]
None of the locale invariant _l versions of `strtod`, `strold` functions are standard C++, but were supposed to be supported in android. That section of the code is surrounded by `if defined(JSONCONS_HAS_STRTOD_L)`, and is currently enabled only for android in `jsoncons_config.hpp`. It was added over a year ago in response to issue [Android does not support localeconv] (https://github.com/danielaparker/jsoncons/issues/78), reported by, you actually :-).  Thanks for these.

Just did a search on `strtod_l android`, and it seems that some android toolsets are missing strtod_l. I can certainly change it to strtold_l.

**Comment by danielaparker** [comment]
strtod_l has been changed to strtold_l on master

**Comment by Phaestion** [comment]
Great! :)
