### ISSUE TITLE
Warnings on GCC

### ISSUE THREAD

**Issue by henriksjostrom** [danielaparker/jsoncons#127]
I'm having some problems with warnings when compiling on `gcc (Ubuntu 7.2.0-8ubuntu3) 7.2.0`

The warning is `warning: bad option ‘-ffunction-sections’ to attribute ‘optimize’ [-Wattributes]`

Removing [this line](https://github.com/danielaparker/jsoncons/blob/v0.100.0/include/jsoncons/detail/jsoncons_config.hpp#L41) eliminates the warnings. 

What can I do other than removing this line to resolve these warnings?

And is it safe to remove this line?

**Comment by danielaparker** [comment]
Thanks for pointing that out. That line has been removed from `jsoncons/jsoncons_config.hpp`, and also from `jsoncons_ext/binary/binary_utilities.hpp`, in master and Release 0.100.2.

**Comment by henriksjostrom** [comment]
Thanks, that resolves the issue.
