### ISSUE TITLE
How can i convert csv to json if one of column type is array

### ISSUE THREAD

**Issue by qqwx1986** [danielaparker/jsoncons#128]
`   
 const std::string bond_yields = R"(Date,1Y,2Y,3Y,5Y
2017-01-09,0.0062,0.0075,0.0083,(0.011,0.012)
2017-01-08,0.0063,0.0076,0.0084,(0.0112,0.013)
2017-01-08,0.0063,0.0076,0.0084,(0.0112,0.014)
)";
    json_decoder<ojson> decoder;
    csv_parameters params;
    params.assume_header(true)
          .column_types("string,float,float,float,[float,*]");

    // Default
    std::istringstream is1(bond_yields);
    csv_reader reader1(is1,decoder,params);
    reader1.read();
    ojson val1 = decoder.get_result();
    std::cout << "\n(1)\n"<< pretty_print(val1) << "\n";
`
column_types may throw exception.

**Comment by danielaparker** [comment]
Currently, we only support a very specific case for mapping an arbitrarily long list of one or more items, e.g.  a file containing an arbitrary number of pairs of julian date and string date (I needed that for an application I'm working on.)

```c++
const std::string holidays = R"(1,CAD,2,UK,3,EUR,4,US + UK,5,US
38719,2-Jan-2006,40179,1-Jan-2010,38719,2-Jan-2006,38719,2-Jan-2006,39448,1-Jan-2008
38733,16-Jan-2006,40270,2-Apr-2010,38733,16-Jan-2006,38733,16-Jan-2006,39468,21-Jan-2008
)";

    json_decoder<ojson> decoder;
    csv_parameters params;
    params.column_types("[integer,string]*");

    // Default
    std::istringstream is1(holidays);
    csv_reader reader1(is1, decoder, params);
    reader1.read();
    ojson val1 = decoder.get_result();
    std::cout << pretty_print(val1) << "\n";
```
produces
```json
[
    [
        [1,"CAD"],
        [2,"UK"],
        [3,"EUR"],
        [4,"US + UK"],
        [5,"US"]
    ],
    [
        [38719,"2-Jan-2006"],
        [40179,"1-Jan-2010"],
        [38719,"2-Jan-2006"],
        [38719,"2-Jan-2006"],
        [39448,"1-Jan-2008"]
    ],
    [
        [38733,"16-Jan-2006"],
        [40270,"2-Apr-2010"],
        [38733,"16-Jan-2006"],
        [38733,"16-Jan-2006"],
        [39468,"21-Jan-2008"]
    ]
]
```
I'll see if I can generalize this notation to handle more cases.

**Comment by qqwx1986** [comment]
Got , thanks
