### ISSUE TITLE
Using csv parser without intermediate istream object

### ISSUE THREAD

**Issue by xezon** [danielaparker/jsoncons#132]
Hello Sir.

The json_parser can be used with strings, but the csv_parser takes istreams only, thus forcing the user to create an intermediate istringstream. Is there any chance to improve the csv parser to support the same easy functionality the json_parser has?

Json
```c++
string utf8string = "some data";
json::json json = json::json::parse(utf8string);
stl::clear_mem(utf8string);
ObjectType someObject = json.as<ObjectType>();
```

Csv
```c++
string utf8string = "some data";
std::istringstream utf8stream(utf8string.c_str());
stl::clear_mem(utf8string);
json::json_decoder<json::json> decoder;
json::csv_reader reader(utf8stream, decoder, csv);
reader.read();
json::json json = decoder.get_result();
stl::clear_mem(utf8stream);
ObjectType someObject = json.as<ObjectType>();
```

**Comment by danielaparker** [comment]
The csv_reader (json_reader) reads from a stream in chunks, and pass those chunks to the csv_parser (json_parser) to parse. 

I've added a convenience function to master that uses `json_parser` directly:

```c++
std::string s = "some label\nsome value";
csv_parameters params;
params.assume_header(true);
std::cout << decode_csv<json>(s,params) << std::endl;
```

**Comment by xezon** [comment]
Thank you. I will try this.

**Comment by xezon** [comment]
Works perfectly. Will there also be convinience functions for file parse and file serialization / string serialization. Afaik json has string parse / file parse function. Not sure about serialization helpers.

**Comment by danielaparker** [comment]
I've added a version of `decode_csv` that takes an `istream` instead of a `string_view`, that will work for files. 

I'll also add `encode_csv` functions.

**Comment by xezon** [comment]
Very nice. Thank you.

**Comment by danielaparker** [comment]
I fixed an issue with `encode_csv` and added doc for `decode_csv` and `encode_csv` in ref.
