### ISSUE TITLE
as_double returning NaN

### ISSUE THREAD

**Issue by xezon** [danielaparker/jsoncons#139]
I was wondering what the usefulness is for having a null field returning NaN double. This means the user must not only use exception handling, but also check every double for std::isnan. Considering a nan double is not a useful value, shouldn't this function just throw the exception instead of returning a malfomed double silently ?

The integer and bool types also throw on null type.

```c++
    double as_double() const
    {
        switch (var_.type_id())
        {
        case json_type_tag::null_t:
            return std::numeric_limits<double>::quiet_NaN();
        }
    }
```

**Comment by danielaparker** [comment]
I think it's okay if an attempt to convert from json null to double in `as_double` throws.

Keep in mind that the double value itself can be NaN (or Inf), depending on how the double value made its way into the `json` value. If it's parsed JSON text, then no, but if it's decoded CBOR, then maybe, or if you assigned a computation that evaluated to NaN, then yes.

**Comment by risksnap** [comment]
`to_double` called on a json null value now throws, in master
