### ISSUE TITLE
question regarding jsonpath

### ISSUE THREAD

**Issue by stdlef** [danielaparker/jsoncons#142]
Hello,

I have the json input below and I would like to learn how to use the json_query method (from json path ext) in order to retrieve the objects that have ( a == 5 && b == 500 ) && ( a == 6 && b == 600)

When I use $..*[?(@.a == 5 && @.b == 500)] I am getting the first object in the array. I would like to get the first and the second in my query result.

Thank you in advance. 

```
[
  {
    "a": 5,
    "b": 500,
    "c": 5000
  },
  {
    "a": 6,
    "b": 600,
    "c": 6000
  },
  {
    "a": 7,
    "b": 700,
    "c": 7000
  }
]
```

**Comment by risksnap** [comment]
This should do it:

"$..*[?((@.a == 5 && @.b == 500) || (@.a == 6 && @.b == 600))]"

(I've added a test case for that in jsonpath_tests.cpp)

**Comment by stdlef** [comment]
Indeed worked, I wonder why the || is selected instead of &&.
The query is "give me those objects that have (a,b)=(5,500) AND (a,b)=(6,600)

Thanks very much

**Comment by danielaparker** [comment]
No, || is correct in logic. There are no elements such that @.a == 5 and @.a == 6 are both true, it's one or the other.  If you had a SQL query that expressed a similar condition, it would also use OR.

**Comment by stdlef** [comment]
Thanks @danielaparker
