### ISSUE TITLE
json::merge and json::merge_or_update does not do deep merge nested objects

### ISSUE THREAD

**Issue by hiviah** [danielaparker/jsoncons#144]
Example:

```cpp
#include <jsoncons/json.hpp>
#include <iostream>

using namespace jsoncons;
using namespace std;

int main() {
    json j1 = json::parse(R"({
    "SET": {
        "service": {
            "ssh": {
                "port": 22
            }
        }
    }
    })");

    json j2 = json::parse(R"({
    "SET": {
        "service": {
            "telnet": {
                "port": 23
            }
        }
    }
    })");

    j2.merge_or_update(j1);
    cout << pretty_print(j2) << endl;
}
```

Result:

```
{
    "SET": {
        "service": {
            "ssh": {
                "port": 22
            }
        }
    }
}
```

Expected result:

```
{
    "SET": {
        "service": {
            "ssh": {
                "port": 22
            },
            "telnet": {
                "port": 23
            }
        }
    }
}
```

In case it is intended that only toplevel keys are merged (and their values replaced instead of deep merge), this should be mentioned in the docs.

**Comment by danielaparker** [comment]
The json `merge_or_update` function follows the behavior of the python dictionary `update` function, and only merges top level keys of two json objects.  I'll update the docs as you suggested.

We could introduce a `deep_merge_or_update` function, but we'd need to adopt sensible policies for handling awkward cases, for instance, if the member "service" is a json object in j2 but an integer in j1, or for merging arrays of objects.

**Comment by hiviah** [comment]
OK, great, the updating docs is good enough. 

If you wanted to introduce a deep merge, then I'd make the rules like this:

- for `deep_merge`:
  1. if there is a key with value on both sides that's a dictionary (JSON object), then do recursive merge
  2. otherwise ignore
- for `deep_merge_and_update`:
  1. if there is a key with value on both sides that's a dictionary (JSON object), then do recursive merge, updating the values recursively
  2. if the types of values don't match, replace the original value with new value

I'm also not 100% sure I covered all the cases, since JSON even though seeming to be simple has lots of pathological/edge cases.
