### ISSUE TITLE
Suspected error in class print_double

### ISSUE THREAD

**Issue by mickcollyer** [danielaparker/jsoncons#145]
In class print_double operator() we have this code, whose job appears to be to deal with useless trailing zeroes:
                const CharT* p = send;
                while (p >= sbeg+2 && *(p-1) == '0' && *(p-2) != '.')
                {
                    --p;
                }
                const CharT* qend = *(p-2) == '.' ? p : send;

However, if parameter 'val' is a single digit:
(a) "while (p >= sbeg+2 && *(p-1) == '0' && *(p-2) != '.')" will (correctly) never be entered
(b) then test "const CharT* qend = *(p-2) == '.' ? p : send;" will peel 1 byte before the beginning of the buffer.

This could be fixed by altering
                const CharT* qend = *(p-2) == '.' ? p : send;
to
                const CharT* qend = ( (p >= sbeg+2 ) && ( *(p-2) == '.') ) ? p : send;

although I don't claim that's the best fix

**Comment by danielaparker** [comment]
You're right, thanks for reporting this. I've taken your suggested fix on master.

**Comment by mickcollyer** [comment]
Thanks for your email, Daniel

In return, thanks for your library - we are getting quite a bit of usage
from it here at PassivSystems

Best Regards

Mick
