### ISSUE TITLE
Question: Serialize and Deserialize performance

### ISSUE THREAD

**Issue by rohitjoshi** [danielaparker/jsoncons#146]
Thanks for creating header-only library with `jsonpath` support.  I am planning to use in my LuaJIT based application by adding a C/FFI layer.

The performance for `parse` and deserialize using `<<` seem to be much slower  (twice) than [cjson](https://github.com/mpx/lua-cjson/blob/master/lua_cjson.c) library's `encode` and `decode` function which is currently used in our application.

e.g  I am decoding using 

`json obj = json::parse(json_str);` 

and encoding using 

```
std::ostringstream ss;
ss << *json_payload_;
strcpy(payload_out, ss.str().c_str());
```
Any suggestion for optimization?

**Comment by danielaparker** [comment]
Hi Rohit,

It's always interesting to compare the performance characteristics of different json libraries, and how they're achieved, so I'll add cjson to our benchmarks, and assess what accounts for the differences you're observing. I can probably reply more meaningfully after that. 

What operating system and compiler are you using?

Daniel

**Comment by rohitjoshi** [comment]
Thanks Daniel.  I am using MacOSX 10.12.16.  One of my colleague ran test on Ubuntu as well.  The Jsonpath is faster than lua-jsonpath but serialize and deserialize are much slower comparatively.  Particularly deserialization/encoding seem to be much slower. May be providing a method which takes a pre-allocate buffer might be faster.
 
I really like your implementation of `jsonpath` 👍

**Comment by rohitjoshi** [comment]
cjson test:
```
decode: 11325.502
encode: 29716.622
```
jsoncons test:
```
decode: 13371.361
encode: 4199.556
```

**Comment by danielaparker** [comment]
Could you rerun your benchmark with the latest code on master?

Thanks,
Daniel

**Comment by rohitjoshi** [comment]
See the below benchmarks with master-branch + pre-allocating `string` object and using `dump`.
I do see some improvement.
```
parse/decode: 4215.596
encode TPS: 14050.433
```

**Comment by danielaparker** [comment]
Improvement? The numbers that you're reporting are actually worse, aren't they?

**Comment by danielaparker** [comment]
Interesting. Your results differ significantly from my benchmarks on Windows, see

[Results with text and integers](https://github.com/danielaparker/json_benchmarks/blob/master/report/performance.md)

[Results with text and doubles](https://github.com/danielaparker/json_benchmarks/blob/master/report/performance_fp.md)

The two generated input files I'm using for these tests are in `persons.zip` and `person_fp.zip` from

https://github.com/danielaparker/json_benchmarks/tree/master/data

Would you be able to provide me with your input file, or alternatively, a description of the composition of your file and its size?

Thanks,
Daniel

**Comment by rohitjoshi** [comment]
@danielaparker thanks.  I will use the same JSON file and provide you benchmarks results.

**Comment by rohitjoshi** [comment]
Here are benchmarks for attached json file.

jsoncons test:
```
parse_json/decode TPS: 5694.387, Total Time:1.756115
to_string/encode TPS: 17556.888, Total Time:0.569577
```

cjson test:
```
parse_json/decode TPS: 18830.547, Total Time:0.531052
to_string/encode TPS: 53353.251, Total Time:0.18743
```


[english.json.txt](https://github.com/danielaparker/jsoncons/files/1674309/english.json.txt)

**Comment by danielaparker** [comment]
I see. My benchmarks are for processing large json files approximately 600 megabytes in size, with different proportions of integers, doubles, text and escaping, and yours are for processing tiny and simple json files many times. The difference are most likely attributable to difference in initial setup costs incurred many times, rather than the speed of parsing and serialization per se. 

jsoncons uses different `#def`'ed code for parsing and serializing floating point numbers on Windows MSC, Android, and all other platforms (MacOSX and linux), and originally jsoncons code on "all other platforms" was significantly slower than the MSC specific code. I did some optimizations, and that code now runs very close. If you had had any floating point numbers in your file when you picked up the new master, you should have seen an improvement in performance, but you didn't, so you wouldn't have :-)

We can probably reduce the initial setup cost of encode, when using the function that dumps to a string. 
Currently, that function uses a `std::ostringstream` under the hood, like your original example, but we could re-implement it so that it writes directly into the supplied string. That would save a lot of memory allocations if you're processing tiny files many times.

I'll look at the parsing side as well. If processing many files, it should be cheaper to use the objects used by `json::parse` directly, namely `json_decoder` and `json_parser`, and re-use them rather than have them created and destroyed each time.

**Comment by rohitjoshi** [comment]
For parsing json file, I am reusing `json` object which did improve some performance.  I have not validated output of the json.  I assume it flushes underneath structure and recreates for a new file.

parse_json/decode TPS: 6621.810, Total Time:1.510161

**Comment by rohitjoshi** [comment]
any example on how to directly use `json_decoder` and `json_parser`?

**Comment by danielaparker** [comment]
I don't understand that result at all. `json::parse` is a static function, so calling it on a shared `json` instance should have no affect whatsoever. 

The following code (latest version on master) is now implemented efficiently (inserts directly into the string):  
```
std::string s;
s.reserve(/* expected maximum size */);
json_payload_->dump(s);
```
To use `json_decoder` and `json_parser` directly (although I'm not sure it's worth it, unless your use case really is parsing 10's of thousands of small files):
```c++

// These structures can be re-used (if they're not going to be accessed by multiple threads, of course)
std::string s;
json_decoder<json> decoder;
 parse_error_handler_type err_handler;
json_parser<char> parser(decoder,err_handler);
 
// This is specific for each json text

// Insert json into s

// Skip past bom, if any
auto result = unicons::skip_bom(s.begin(), s.end());
if (result.ec != unicons::encoding_errc())
{
     throw parse_error(result.ec,1,1);
}
size_t offset = result.it - s.begin();

// Note that json_parser does not own memory, it just holds a pointer to the buffer and its length
parser.set_source(s.data()+offset,s.size()-offset);
parser.parse(); 
parser.end_parse(); 
parser.check_done();
if (!decoder.is_valid())
{
    JSONCONS_THROW_EXCEPTION(std::runtime_error,"Failed to parse json string");
}
json j = decoder.get_result();
```

**Comment by rohitjoshi** [comment]
not sure but latest from master, parse() has become too slow.
```
parse_json/decode TPS: 156.422, Total Time:63.929297
```

**Comment by danielaparker** [comment]
Nothing has changed on master that would affect the performance of parse. I reran my benchmarks, and the results were similar to what is posted at 

[Results with text and integers](https://github.com/danielaparker/json_benchmarks/blob/master/report/performance.md)

[Results with text and doubles](https://github.com/danielaparker/json_benchmarks/blob/master/report/performance_fp.md)

**Comment by rohitjoshi** [comment]
hm...  not sure. I double check and confirmed by reverting the merge. Any changes specific to OS?

**Comment by rohitjoshi** [comment]
I checked out master branch again and could see the performance impact.

**Comment by danielaparker** [comment]
Other than floating point conversions, there are no specific OS differences, and your benchmark does not have floating point numbers. I'm not doubting your observations, but having some difficulty trying to account for them. I'll start with your benchmark code, which of course is measuring something very different from my benchmarks.

**Comment by rohitjoshi** [comment]
sorry, I check out from the master as a separate project and issue seem to be resolved. Not sure if  this issue was due to merge with my modifications to add `remove` function similar to `replace`.  

No difference in performance though except if I reuse `json` object to parse file.  It increase 500-900 TPS more.

e.g
```
if (json_payload_) {
       json_payload_->parse(json_str);
 }else {
       json obj = json::parse(json_str);
      json_payload_ = new json(obj);
 }
```

Earlier  I was using

```
if (json_payload_) {
      delete json_payload_;
}
 json obj = json::parse(json_str);
 json_payload_ = new json(obj);
```

**Comment by danielaparker** [comment]
I would just note that
```c++
if (json_payload_) {
       json_payload_->parse(json_str);
 }else {
       json obj = json::parse(json_str);
      json_payload_ = new json(obj);
 }
```
doesn't make sense. I would say regardless of what your measurements are showing, just use
``` c++
json obj = json::parse(json_str);
```
`parse` is a static function

**Comment by danielaparker** [comment]
Change

json obj = json::parse(json_str);
 json_payload_ = new json(obj);

to

json obj = json::parse(json_str);
 json_payload_ = new json(std::move(obj));

or

 json_payload_ = new json(json::parse(json_str));

Either will avoid a copy.

**Comment by rohitjoshi** [comment]
@danielaparker thanks.  updated as above.

Here are benchmark numbers using the latest from the master branch. Using 50K iterations.

`jsoncons`:

```
parse_json/decode TPS: 7887.195, Total Time:6.339389
to_string/encode TPS: 28877.263, Total Time:1.731466
```

`cjson`:

```
parse_json/decode TPS: 17577.763, Total Time:2.844503
to_string/encode TPS: 50112.251, Total Time:0.99776
```

**Comment by danielaparker** [comment]
I ran my version of your benchmark on Windows with VC++.

std::string input; // Contains input json you supplied
std::string output; // Output goes here

jsoncons:

Decode: 

    json root = jsoncons::json::parse(input);

Encode:

    root.dump(output);

cJSON:

Decode:

    cJSON*  root = cJSON_Parse(input.c_str());

Encode:

    output = cJSON_PrintUnformatted(root);

Destroy:

    cJSON_Delete(root);

Repeat 50,000 times

Results:

Decode times averaged over 50,000 times (in microseconds):

jsoncons: 98 
cJSON: 52

Encode times averaged over 50,000 times (in microseconds):

jsoncons: 25
cJSON: 20

In both cases cJSON is faster than jsconcons. The magnitude of the results differ somewhat from yours, but that's not surprising, for example, I'm assigning the return valued from cJSON_PrintUnformatted to a C++ string which involves a copy, there are differences in compiler optimization, etc.

For parsing, those 52 (98) microseconds include setup, parsing, and teardown. jsoncons certainly does more setup than cJSON, constructing separate decoder and parser objects. That setup is a fixed cost, and would be the same regardless of whether the input file is 6,918 bytes including indentation and white space (your input), or 10 megabytes, or 600 megabytes (my benchmark.)

**Comment by rohitjoshi** [comment]
I think your results are similar to mine.  I am using additional FFI layer and running these test from Lua (LuaJIT).   I am using [lua-cjson](https://github.com/mpx/lua-cjson/) which might be more efficient than my FFI/Lua layer.

Here are the benchmarks from C++ program using `jsoncons`:

```
./dist/Release/GNU-MacOSX/jsonpathbenchmark 50000 english.json
Decode: wall time 4.772852s,  TPS:10475.916829
Encode: wall time 1.930700s,  TPS:25897.342078
```

Code: added a .txt suffix so I can upload here:

[main.cpp.txt](https://github.com/danielaparker/jsoncons/files/1685988/main.cpp.txt)

**Comment by danielaparker** [comment]
Could you rerun your tests with the attached file? It adds an array of integers to each object in your input file.

Thanks,
Daniel

**Comment by danielaparker** [comment]
Could you rerun your benchmarks with the attached file? I added a member to each object consisting of an array of integers.
[small_file.json.txt](https://github.com/danielaparker/jsoncons/files/1689982/small_file.json.txt)

**Comment by rohitjoshi** [comment]
`jsoncons` performance is better with `small_file.json` file.

`jsoncons`:

```
parse_json/decode TPS: 7887.195, Total Time:6.339389
to_string/encode TPS: 28877.263, Total Time:1.731466
```
`cjson`:

```
parse_json/decode TPS: 2447.744, Total Time:20.42697
to_string/encode TPS: 3605.0123, Total Time:13.869578
```

**Comment by danielaparker** [comment]
It looks like the main issue is that cJSON is faster at decoding and encoding text. I'll have a look at that next.

**Comment by rohitjoshi** [comment]
👍

**Comment by rohitjoshi** [comment]
It seems `std::enable_if` and memory allocations are expensive.   See attached Valgrind output for `parse/decode`.  Maybe pre-allocation memory pool might help.

<img width="1609" alt="jsoncons_parse" src="https://user-images.githubusercontent.com/1570798/35768965-c93a9d9a-08d1-11e8-8cf1-77336f5c2997.png">

**Comment by rohitjoshi** [comment]
For `encode/to_string`, copy by character seem to be taking most of the time.   Maybe we should add an optional feature to preserve original json string and override element only if replace/delete operations were performed on the particular element (index + length).  It might take more memory but would be very efficient.

<img width="1606" alt="jsoncons_encode" src="https://user-images.githubusercontent.com/1570798/35769054-3ec6b5e8-08d3-11e8-8e91-db4ba65e6535.png">

**Comment by danielaparker** [comment]
"memory allocations are expensive"

Agreed there is some room for reducing memory allocations

"It seems std::enable_if ... [is] expensive."

 `std::enable_if` only applies at compile time

"in escape_string and other functions, const characters are not defined as constant which means are allocated every time"

Not sure what you mean here, the signature of `escape_string` is
```
    void escape_string(const CharT* s,
                       size_t length,
                       const basic_serialization_options<CharT>& options,
                       writer_type& writer)
```

**Comment by rohitjoshi** [comment]
I do see ~5% performance improvement with the latest code.  It seems when json file contains numbers/floats, `jsoncons` outperforms `cjson` but for string processing, `cjson` is still faster.

**Comment by danielaparker** [comment]
The following changes have been made: 

- Faster floating point conversions for linux and MacOSX (not picked up by your benchmark)
- Memory allocation decoding larger string values reduced by half (not picked up by your benchmark)
- Optimization to `json_parser` `parse_string` (accounts for the ~5% performance improvement you see)
- Improvements to `json_decoder`

I'll have to leave it at that for the moment, but will continue to investigate the discrepancy with cjson when time permits.
