### ISSUE TITLE
Implicit declaration of arrays

### ISSUE THREAD

**Issue by JanisTerinde** [danielaparker/jsoncons#148]
Hi, 

first of all thanks for providing this library. I need to build complex json files for a project and the implicit declaration of json objects along a path really helps.

I'm not sure if I've overlooked something, but is there a way to implicitly declare an array when using paths? 

For example specifying 'somestring' to be declared as an array?
```
    jsoncons::json jObj;
    jObj["subObj"]["somestring"] = "Hallo";
```
Thanks a lot.

**Comment by JanisTerinde** [comment]
xyvyxcv

**Comment by danielaparker** [comment]
We don't support implicitly declaring an array, the best you can do is
```c++
int main()
{
    jsoncons::json jObj;
    jObj["subObj"]["somestring"] = jsoncons::json::array{"Hallo"};

    std::cout << pretty_print(jObj) << std::endl;
}
```
Output:
```json
{
    "subObj": {
        "somestring": ["Hallo"]
    }
}
```

**Comment by JanisTerinde** [comment]
Ok, thank you.
