### ISSUE TITLE
pos_inf_replacement on write; nothing available on parse?

### ISSUE THREAD

**Issue by BongoVR** [danielaparker/jsoncons#149]
Hello,
I have a question about pos_inf_replacement and similar functions in jsoncons::json_printable (actually, basic_serialization_options). I can set up a pretty printer that replaces the representation of NAN, INF etc. However, there seems to be no customisation possible on parsing a string created this way.

Was this just an oversight or is the aforementioned customisation intended for some special case and not for reading in again?

Best regards

**Comment by danielaparker** [comment]
Thanks for the suggestion, yes, we should support analogous options for parsing. We'll add it as a future enhancement.

If you need an immediate work around, you can use a filter:

```
#include <jsoncons/json.hpp>
#include <jsoncons/json_filter.hpp>
#include <iostream>
#include <cmath>

using namespace jsoncons;

class nan_substitution_filter : public json_filter
{
public:
    nan_substitution_filter(json_input_handler& handler)
        : json_filter(handler)
    {
    }

private:

    void do_string_value(const string_view_type& s, const parsing_context& context) override
    {
        if (s == "NAN")
        {
            this->downstream_handler().double_value(std::nan(""), context);
        }
        else
        {
            this->downstream_handler().string_value(s, context);
        }
    }
};

int main()
{
    try
    {
        std::string s("\"NAN\"");
        std::istringstream is(s);

        json_decoder<json> decoder;
        nan_substitution_filter filter(decoder);
        json_reader reader(is, filter);
        reader.read();

        json j = decoder.get_result();
        std::cout << std::boolalpha << j.is_double() << std::endl;

        serialization_options options;
        options.nan_replacement("NaN");
        std::cout << print(j, options) << std::endl;
    }
    catch (const std::exception& e)
    {
        std::cout << e.what() << std::endl;
    }
}
```

**Comment by danielaparker** [comment]
The class `serialization_options` has been deprecated (still works) and changed to `json_serializing_options`. Rationale: naming consistency with the extensions.

I've added an optional `json_serializing_options` parameter to the `json::parse` functions and the `json_parser` and `json_reader` constructors, which allows replacing
a string that matches nan_replacement(), pos_inf_replacement(), and neg_inf_replacement(). For example,

```c++
std::string s = R"({"field1":"NaN","field2":"PositiveInfinity","field3":"NegativeInfinity"})";

json_serializing_options options;
options.nan_replacement("\"NaN\"");
options.pos_inf_replacement("\"PositiveInfinity\"");
options.neg_inf_replacement("\"NegativeInfinity\"");

json j = json::parse(s,options);

std::cout << pretty_print(j,options) << std::endl;
```
Output:
```
{
    "field1": "NaN",
    "field2": "PositiveInfinity",
    "field3": "NegativeInfinity"
}
```
If the write replacement is to a number, e.g. replacing NaN with 0, no read replacement is performed.
