### ISSUE TITLE
Accessing raw data with char*

### ISSUE THREAD

**Issue by MrRomanMaccaruni** [danielaparker/jsoncons#152]
Hi,
I was wondering if there's a way to access the raw (char) content underlying a json object. What I am trying to do is to store a big array (~400Mb) of float as binary hex-string into a json field. In order to retrieve that amount of data, without making what I feel as an unnecessary copy, can I set up a char* to the first char of the field? If yes, how? Any comment or idea to differently address my issue is more than welcome!

Thanks in advance!

Cheers,
Alessandro

**Comment by danielaparker** [comment]
Use `as_string_view()`, e.g.
```
json j = json::parse("\"Hello World\"");
auto sv = j.as_string_view();
```
`sv.data()` returns a pointer to the beginning of the string data, and `sv.length()` returns its length.

**Comment by MrRomanMaccaruni** [comment]
Exactly what I was looking for!! Thanks a lot for your fast answer and keep going. Your repo rocks!!!!!

Cheers,
Alessandro
