### ISSUE TITLE
its work with arduino?

### ISSUE THREAD

**Issue by majidmp97** [danielaparker/jsoncons#153]
its work with arduino?

**Comment by danielaparker** [comment]
Until your question, I hadn't heard of arduino!

You'll need a C++ compiler that supports C++ 11 features, maybe this will help:

[How to program arduino with c++](https://stackoverflow.com/questions/18523577/how-to-program-arduino-with-c)

**Comment by majidmp97** [comment]
arduino campiler work with c and c++

**Comment by danielaparker** [comment]
OK, try it, and if you have any issues, please report them.
