### ISSUE TITLE
Incremental parsing?

### ISSUE THREAD

**Issue by vinniefalco** [danielaparker/jsoncons#155]
I don't see a way to perform incremental parsing, i.e. when a large serialized JSON object is presented as a series of individual buffers, one per call into the parser. In other words, an **online algorithm**:
https://en.wikipedia.org/wiki/Online_algorithm

**Comment by danielaparker** [comment]
I believe `json_parser` supports incremental parsing, if I understand the term correctly. A buffer of text is supplied to the parser with a call to  `set_source(buffer,buffer_length)`. If a subsequent call to `parse_some` reaches the end of the buffer in the middle of parsing, say after digesting the sequence 'f', 'a', 'l', it returns and the `source_exhausted()` accessor on the parser returns `true`. The user can then supply additional text to the parser, and the parser continues from where it paused.

The original motivation for designing it this way was to support reading large files in chunks. I have used it to parse json text coming in bits and pieces on a socket connection.     

I haven't documented `json_parser`, it's currently considered an implementation detail to `json_reader`. You can see how it's used by looking at the [source to json_reader](https://github.com/danielaparker/jsoncons/blob/master/include/jsoncons/json_reader.hpp), in the `read_buffer` function. But it could be documented.

**Comment by vinniefalco** [comment]
> I believe json_parser supports incremental parsing,

Yes, what you described is definitely incremental parsing! I think this project would benefit from making the interface public, and having improved documentation.

**Comment by danielaparker** [comment]
New documentation for `json_parser` on master can be found here: 

https://github.com/danielaparker/jsoncons/blob/master/doc/ref/json_parser.md

**Comment by vinniefalco** [comment]
I believe this is the first JSON library to support incremental parsing, no?

**Comment by danielaparker** [comment]
Possibly of the ones that have active users, but I searched after seeing your comment, and there appear to be experimental ones, for example

https://github.com/bjouhier/i-json

**Comment by danielaparker** [comment]
Thanks :-)
