### ISSUE TITLE
Errors in cbor_parser.hpp - How can I fix it to work with Visual Studio 2017?

### ISSUE THREAD

**Issue by MavKillian** [danielaparker/jsoncons#160]
How can I fix this? It is not compatible with latest Visual Studio?

I am using Visual Studio Professional 2017, Version 15.7.5. I downloaded the JSONCONS zip file, unzipped and set my Config Properties "General Additional Include directories" to point to the jsoncons include directory. I then added all of the #include statements in my C++ program. However when I run Debug get many errors from the jsoncons "cbor_parser.hpp" include file such as:

Warning	C4244	'=': conversion from 'unsigned __int64' to 'size_t', possible loss of data	ConsoleApplication3 c:\users\killimm1\desktop\c code\jsoncons-master\jsoncons-master\include\jsoncons_ext\cbor\cbor_parser.hpp

Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4244	'return': conversion from 'const __int64' to 'size_t', possible loss of data

Severity	Code	Description	Project	File	Line	Suppression State
Error	C2664	'std::string jsoncons::cbor::detail::get_text_string(const uint8_t *,const uint8_t *,const uint8_t **)': cannot convert argument 3 from 'unsigned char **' to 'const uint8_t **'

Severity	Code	Description	Project	File	Line	Suppression State
Warning	C4244	'argument': conversion from 'const unsigned __int64' to 'size_t', possible loss of data

**Comment by danielaparker** [comment]
Thanks for reporting these. I do need to add vs2017 to the automatic builds!

The particular issues you reported should be fixed now on master. Most of them have to do with being too cavalier with treating uint64_t and size_t the same, and char and uint8_t as close enough in binary conversions. 

The level 3 warnings and the error you experienced should be fixed. There are some level 4 warnings I still need to look at.

Daniel

**Comment by danielaparker** [comment]
Just to follow up, I believe all vs2017 level 3 and level 4 warnings have been eliminated in the code on master.
