### ISSUE TITLE
Raspberry Pi (Arm) problem

### ISSUE THREAD

**Issue by kjellc** [danielaparker/jsoncons#163]
Hi Daniel,

I'm trying to use jsoncons (0.109.0) on a Raspberry Pi (running raspbian stretch, gcc 6.3.0, Arm). 
I get segfaults probably caused by corrupted memory.

I ran the jsoncons_tests and it fails in a similar way (see below).
I know that Arm is not a target you test, but do you have any idea what could be the problem?

Br Kjell Christenson
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
jsoncons_tests is a Catch v2.3.0 host application.
Run with -? for options

-------------------------------------------------------------------------------
test_serialize_to_stream
-------------------------------------------------------------------------------
/home/pi/jsoncons-0.109.0/tests/src/cbor/cbor_serializer_tests.cpp:17
...............................................................................

/home/pi/jsoncons-0.109.0/tests/src/cbor/cbor_serializer_tests.cpp:17: FAILED:
due to unexpected exception with message:
  std::bad_alloc

[true,false,null]
[[true,false,null,"Hello"]]
-------------------------------------------------------------------------------
cbor_test_floating_point
-------------------------------------------------------------------------------
/home/pi/jsoncons-0.109.0/tests/src/cbor/cbor_tests.cpp:16
...............................................................................

/home/pi/jsoncons-0.109.0/tests/src/cbor/cbor_tests.cpp:16: FAILED:
due to a fatal error condition:
  SIGSEGV - Segmentation violation signal

===============================================================================
test cases:  21 |  19 passed | 2 failed
assertions: 179 | 177 passed | 2 failed

Segmentation fault

**Comment by danielaparker** [comment]
Hi Kjell,

Thanks for reporting this. Currently we only run tests on x64 architecture, but I'll look into getting them to run on ARM. It may be an alignment issue.

Can you provide any additional log details? In particular, for the simplest example you have that fails, the jsoncons file and line where the error occured?

Thanks,
Daniel

**Comment by danielaparker** [comment]
If you're still following this, I'd be interested if the failure still happens with the latest code on master, as a fix has been applied that could have caused an issue with deallocation.

I cross compiled for ARMv8-A architecture on Travis using clang and ran the tests successfully using the emulator qemu, but of course that isn't the same as your environment. We'll be looking for more opportunities to add cross compilation to the continuous integration testing.
