### ISSUE TITLE
Failure to compile on Json::make_array()

### ISSUE THREAD

**Issue by henriksjostrom** [danielaparker/jsoncons#168]
I'm trying to upgrade from v0.100.2 to v0.113.0 but when I compile I get

` cannot convert from 'jsoncons::json_array<jsoncons::basic_json<char,jsoncons::sorted_policy,std::allocator<char>>>' to 'jsoncons::basic_json<char,jsoncons::sorted_policy,std::allocator<char>>::variant'
`

Seemingly coming from `Json::make_array();`

Using VS 15.8.9, with c++17 enabled

**Comment by henriksjostrom** [comment]
Great, thanks

**Comment by danielaparker** [comment]
Patched release v0.113.1 with this fix has been uploaded.

**Comment by henriksjostrom** [comment]
And seems to work. Thanks for the assistance
