### ISSUE TITLE
Windows 2015 compile error

### ISSUE THREAD

**Issue by toutant** [danielaparker/jsoncons#169]
Well I need some help ... i have been using your older code for years - very solid and very dependable.

I have downloaded your latest code and I have been having troubles making it compile.
I am sure it is due to the old code syntax to the newer one. ( which i like better )

I have gone through and changed all the older stuff to newer .. ie json::an_array to json::array() as well as ::null() ::object() etc ... but for the life of me i cannot fix the last error's while compiling 

any help would be appreciated ( i should have backed up my code before installing the latest )

1>c:\local\jsoncons\bignum.hpp(1462): error C2589: '(': illegal token on right side of '::'
1>  c:\local\jsoncons\bignum.hpp(1462): note: while compiling class template static data member 'const uint64_t jsoncons::basic_bignum<std::allocator<uint8_t>>::max_basic_type'
1>  c:\local\jsoncons\json_serializer.hpp(1191): note: see reference to function template instantiation 'jsoncons::basic_bignum<std::allocator<uint8_t>>::basic_bignum<CharT>(const CharT *,std::size_t)' being compiled
1>          with
1>          [
1>              CharT=char
1>          ]
1>  c:\local\jsoncons\json_serializer.hpp(1191): note: see reference to function template instantiation 'jsoncons::basic_bignum<std::allocator<uint8_t>>::basic_bignum<CharT>(const CharT *,std::size_t)' being compiled
1>          with
1>          [
1>              CharT=char
1>          ]
1>  c:\local\jsoncons\json_serializer.hpp(1181): note: while compiling class template member function 'void jsoncons::basic_json_compressed_serializer<char,jsoncons::detail::string_writer<std::string>>::write_bignum_value(const jsoncons::Basic_string_view_<char,std::char_traits<char>> &)'
1>  c:\local\jsoncons\json_serializer.hpp(1241): note: see reference to function template instantiation 'void jsoncons::basic_json_compressed_serializer<char,jsoncons::detail::string_writer<std::string>>::write_bignum_value(const jsoncons::Basic_string_view_<char,std::char_traits<char>> &)' being compiled
1>  c:\local\jsoncons\basic_json.hpp(3382): note: see reference to class template instantiation 'jsoncons::basic_json_compressed_serializer<char,jsoncons::detail::string_writer<std::string>>' being compiled
1>  c:\local\jsoncons\basic_json.hpp(3327): note: see reference to function template instantiation 'std::basic_string<char,std::char_traits<char>,std::allocator<char>> jsoncons::basic_json<char,jsoncons::sorted_policy,std::allocator<char>>::as_string<std::allocator<char>>(const jsoncons::basic_json_serializing_options<char> &,const SAllocator &) const' being compiled
1>          with
1>          [
1>              SAllocator=std::allocator<char>
1>          ]
1>  c:\local\jsoncons\basic_json.hpp(3327): note: see reference to function template instantiation 'std::basic_string<char,std::char_traits<char>,std::allocator<char>> jsoncons::basic_json<char,jsoncons::sorted_policy,std::allocator<char>>::as_string<std::allocator<char>>(const jsoncons::basic_json_serializing_options<char> &,const SAllocator &) const' being compiled
1>          with
1>          [
1>              SAllocator=std::allocator<char>
1>          ]
1>  c:\local\jsoncons\json_type_traits.hpp(628): note: see reference to function template instantiation 'std::basic_string<char,std::char_traits<char>,std::allocator<char>> jsoncons::basic_json<char,jsoncons::sorted_policy,std::allocator<char>>::as_string<std::allocator<char>>(void) const' being compiled
1>  c:\local\jsoncons\json_type_traits.hpp(628): note: see reference to function template instantiation 'std::basic_string<char,std::char_traits<char>,std::allocator<char>> jsoncons::basic_json<char,jsoncons::sorted_policy,std::allocator<char>>::as_string<std::allocator<char>>(void) const' being compiled
1>  c:\local\jsoncons\json_type_traits.hpp(627): note: while compiling class template member function 'std::string jsoncons::json_type_traits<jsoncons::basic_json<char,jsoncons::sorted_policy,std::allocator<char>>,T,void>::as(const Json &)'
1>          with
1>          [
1>              T=std::string,
1>              Json=jsoncons::basic_json<char,jsoncons::sorted_policy,std::allocator<char>>
1>          ]
1>  c:\local\jsoncons\basic_json.hpp(3179): note: see reference to function template instantiation 'std::string jsoncons::json_type_traits<jsoncons::basic_json<char,jsoncons::sorted_policy,std::allocator<char>>,T,void>::as(const Json &)' being compiled
1>          with
1>          [
1>              T=std::string,
1>              Json=jsoncons::basic_json<char,jsoncons::sorted_policy,std::allocator<char>>
1>          ]
1>  c:\local\jsoncons\basic_json.hpp(3179): note: see reference to class template instantiation 'jsoncons::json_type_traits<jsoncons::basic_json<char,jsoncons::sorted_policy,std::allocator<char>>,T,void>' being compiled
1>          with
1>          [
1>              T=std::string
1>          ]
1>  c:\local\jsoncons\basic_json.hpp(1726): note: see reference to function template instantiation 'T jsoncons::basic_json<char,jsoncons::sorted_policy,std::allocator<char>>::as<T,>(void) const' being compiled
1>          with
1>          [
1>              T=std::string
1>          ]
1>  c:\local\jsoncons\basic_json.hpp(1726): note: see reference to function template instantiation 'T jsoncons::basic_json<char,jsoncons::sorted_policy,std::allocator<char>>::as<T,>(void) const' being compiled
1>          with
1>          [
1>              T=std::string
1>          ]
1>  c:\users\robto\downloads\sciter-sdk\demos\usciter\cfunc.cpp(92): note: see reference to function template instantiation 'T jsoncons::basic_json<char,jsoncons::sorted_policy,std::allocator<char>>::json_proxy<jsoncons::basic_json<char,jsoncons::sorted_policy,std::allocator<char>>>::as<std::string,>(void) const' being compiled
1>          with
1>          [
1>              T=std::string
1>          ]
1>  c:\users\robto\downloads\sciter-sdk\demos\usciter\cfunc.cpp(92): note: see reference to function template instantiation 'T jsoncons::basic_json<char,jsoncons::sorted_policy,std::allocator<char>>::json_proxy<jsoncons::basic_json<char,jsoncons::sorted_policy,std::allocator<char>>>::as<std::string,>(void) const' being compiled
1>          with
1>          [
1>              T=std::string
1>          ]
1>c:\local\jsoncons\bignum.hpp(1462): error C2059: syntax error: '::'

**Comment by danielaparker** [comment]
Hi toutant,

It looks like you're including "windows.h", and you've run into a line in our code where we've neglected to protect against windows macro expansion of "max", bignum.hpp line 1462 is

```c++
const uint64_t basic_bignum<Allocator>::max_basic_type = std::numeric_limits<uint64_t>::max();
``` 
but, with windows.h in the includes, should be written as
```c++
const uint64_t basic_bignum<Allocator>::max_basic_type = (std::numeric_limits<uint64_t>::max)();
``` 
That got by our tests this time, my apologies, but going forward I'll include windows.h in our windows continuous integration testing. We should have a patch to the current release up soon (it will be 0.113.2, will be tested with windows.h) but in the meantime you could try making the change above.

Daniel

**Comment by danielaparker** [comment]
The fix is currently on master, and all tests have passed with windows.h included at the top of source files for the windows 2015 and 2017 continuous integration tests.

**Comment by toutant** [comment]
That did the trick ... thank you
