### ISSUE TITLE
Problem with parsing CSV file with quotes

### ISSUE THREAD

**Issue by karimhm** [danielaparker/jsoncons#172]
If i try to parse the following CSV file:
The file start with **0xEFBBBF** BOM mark.

```csv
stop_id,stop_name,stop_lat,stop_lon,location_type,parent_station
"8220B007612","Hotel Merrion Street","53","-6","",""
```
The library crash when trying to access **stop_id**, even though the field (**stop_id**) exist within the file?
```c++
#include <fstream>
#include <jsoncons/json.hpp>
#include <jsoncons_ext/csv/csv_reader.hpp>

using namespace jsoncons;
using namespace jsoncons::csv;

int main() {
    csv_options options;
    options.assume_header(true);
    
    std::ifstream is("stations.csv");
    ojson station = decode_csv<ojson>(is, options)[0];
    
    // Will throw and print: "Key 'stop_id' not found"
    try {
        ojson stop_id = station["stop_id"];
        std::cout << pretty_print(stop_id) << std::endl;
    } catch (const jsoncons::key_not_found& e) {
        std::cout << e.what() << std::endl;
    }
    
    // Will print: "Hotel Merrion Street"
    try {
        ojson stop_name = station["stop_name"];
        std::cout << pretty_print(stop_name) << std::endl;
    } catch (const jsoncons::key_not_found& e) {
        std::cout << e.what() << std::endl;
    }
    
    // Will print:
    /*
        stop_id
        stop_name
        stop_lat
        stop_lon
        location_type
        parent_station
     */
    for (auto &obj: station.object_value()) {
        std::cout << obj.key() << std::endl;
    }
}
```

But if the quote marks are removed then everything works fine???
```csv
stop_id,stop_name,stop_lat,stop_lon,location_type,parent_station
8220B007612,Hotel Merrion Street,53,-6,,
```

**Comment by danielaparker** [comment]
Hi karimhm,

 I think it's the presence of the BOM mark that's causing the issue, the csv_reader, unlike the json_reader, doesn't currently strip BOM marks. With the BOM mark, the CSV parser is reading the first key as `0xEFBBBFstop_it`, so "stop_it" wouldn't match it. If, in the header line, `stop_it` were enclosed in quotes, you should see the correct result, as the parser would ignore any characters coming before the first unescaped quote.

Regarding your other observation, my guess is that when you removed quote marks in the data line, you inadvertently removed the BOM mark preceding the header line as well, otherwise that should have had no effect.

BOM marks shouldn't be used, they're not needed, and the JSON specification forbids them for JSON "Implementations MUST NOT add a byte order mark to the beginning of a  JSON text." This is the first time I've come across one in a CSV file. But it's not a big deal to detect them and ignore them, it just requires that the code in `csv_reader` follow `json_reader` where `json_reader` calls `unicons::skip_bom`. I'll do that sometime this weekend and put it on master.

Daniel

**Comment by karimhm** [comment]
> Hi karimhm,
> 
> I think it's the presence of the BOM mark that's causing the issue, the `csv_reader`, unlike the `json_reader`, doesn't currently strip BOM marks. With the BOM mark, the CSV parser is reading the first key as `0xEFBBBFstop_it`, so "stop_it" wouldn't match it. If, in the header line, `stop_it` were enclosed in quotes, you should see the correct result, as the parser would ignore any characters coming before the first unescaped quote.
> 
> Regarding your other observation, my guess is that when you removed quote marks in the data line, you inadvertently removed the BOM mark preceding the header line as well, otherwise that should have had no effect.
> 
> BOM marks shouldn't be used, they're not needed, and the JSON specification forbids them for JSON "Implementations MUST NOT add a byte order mark to the beginning of a JSON text." This is the first time I've come across one in a CSV file. But it's not a big deal to detect them and ignore them, it just requires that the code in `csv_reader` follow `json_reader` where `json_reader` calls `unicons::skip_bom`. I'll do that sometime this weekend and put it on master.
> 
> Daniel

Thanks for your reply.

I dettect the BOM using this code (if any one is interested in knowing how to do it)

```c++
uint32_t *fileBegin;
if ((0xEFBBBF00 ^ (*fileBegin & 0xFFFFFF00)) == 0) {
    std::cout << "BOM exist" << std::endl;
}
```

**Comment by karimhm** [comment]
> Hi karimhm,
> 
> I think it's the presence of the BOM mark that's causing the issue, the `csv_reader`, unlike the `json_reader`, doesn't currently strip BOM marks. With the BOM mark, the CSV parser is reading the first key as `0xEFBBBFstop_it`, so "stop_it" wouldn't match it. If, in the header line, `stop_it` were enclosed in quotes, you should see the correct result, as the parser would ignore any characters coming before the first unescaped quote.
> 
> Regarding your other observation, my guess is that when you removed quote marks in the data line, you inadvertently removed the BOM mark preceding the header line as well, otherwise that should have had no effect.
> 
> BOM marks shouldn't be used, they're not needed, and the JSON specification forbids them for JSON "Implementations MUST NOT add a byte order mark to the beginning of a JSON text." This is the first time I've come across one in a CSV file. But it's not a big deal to detect them and ignore them, it just requires that the code in `csv_reader` follow `json_reader` where `json_reader` calls `unicons::skip_bom`. I'll do that sometime this weekend and put it on master.
> 
> Daniel

I use this code actually:
```c++
uint32_t offset = bomExist ? 3:0;

jsoncons::csv::csv_options options;
options.assume_header(true);
                    
jsoncons::ojson::string_view_type string((char*)buffer + offset, buffer.size - offset);
jsoncons::ojson json = jsoncons::csv::decode_csv<jsoncons::ojson>(string, options);
```

**Comment by danielaparker** [comment]
The current version of cvs_reader on master now detects and ignores boms. I've included your example in tests/src/csv/csv_tests.cpp, and it passes.
