### ISSUE TITLE
JsonPath for CBOR

### ISSUE THREAD

**Issue by quannh0308** [danielaparker/jsoncons#173]
JsonPath is a query language that we can use to extract data from JSON.
CBOR is json-like data format.
If you can make JsonPath work with CBOR, it will be welcomed by a lot of developers.
In Java, there is a Jackson library that do almost all operations in CBOR same like in JSON though JsonNode object (stands for both CBOR and JSON, depends on the implementation).

**Comment by danielaparker** [comment]
It should work now similarly to what you describe for Jackson. Use the function `cbor::decode_cbor` to decode the CBOR bytes into a `json` value `j`, and then apply `jsonpath::json_query` to `j`. The type `json` is intended to accommodate all JSON-like data formats, not just JSON, and supports byte strings as well as capturing a limited subset of CBOR semantic tagging, see [jsoncons data model](https://github.com/danielaparker/jsoncons/blob/master/doc/ref/data-model.md) for details.

**Comment by quannh0308** [comment]
Thank you for your fast response.
I've updated the project to the latest version and found both bug fix and performance enhancement.

**Comment by danielaparker** [comment]
Thanks for the feedback. I'll look into adding examples and tests cases for JsonPath specifically for CBOR. I'll also look into having the JsonPath numeric filter functions and operators work for bignum, big decimal, and big float, which is not currently the case. Any other suggestions welcome.

**Comment by danielaparker** [comment]
I've added an example in the README, Query CBOR with JSONPath, which illustrates querying CBOR that contains a float, a double, a bignum, a decimal fraction, and a bigfloat.

**Comment by quannh0308** [comment]
Thank you so much for your support.
Actually, We are doing more things with your library, especially with JsonPath.
We use it not only to query but also update data with some operations like UPDATE, ADD_TO_LIST, ADD_TO_SET, DELETE (name), REMOVE (value), INCREMENT (number).
CBOR looks promise to be a great replacement for JSON. It only needs time to have more libraries those support querying it like you are using JsonPath to do the job.

CBOR is smaller than JSON in term of data size. It also has its own standard. Have JsonPath to work with it, I think that we can query/update data in the same way that MongoDB is doing with their BSON. Such a great combination, I think.

**Comment by danielaparker** [comment]
Actually, just noticed a mistake in the answer, had hoped you hadn't saw this yet :-)  Will fix.
