### ISSUE TITLE
wjson dump() not formatting booleans correctly

### ISSUE THREAD

**Issue by ErikDOlson** [danielaparker/jsoncons#174]
Looks like there's a string length problem on formatting the strings "true" and "false" on the wjson implementation.  This is Visual Studio 2017/Windows.  

Sample output:

{"bar":false null,"baz":truefals,"foo":truefals}    <- suspect this actually "true\0fals"
{"bar":false,"baz":true,"foo":true}

Code that generated this:

        jsoncons::wjson testBlock;
        testBlock[L"foo"] = true;
        testBlock[L"bar"] = false;
        testBlock[L"baz"] = true;
        std::wstring testStr;
        testBlock.dump(testStr);
        
        std::wcout << testStr << std::endl;
        
        jsoncons::json nestBlock;
        nestBlock["foo"] = true;
        nestBlock["bar"] = false;
        nestBlock["baz"] = true;
        std::string nestStr;
        nestBlock.dump(nestStr);

        std::cout << nestStr << std::endl;

**Comment by ErikDOlson** [comment]
Ah, json_literals need to have sizeof(chars)/sizeof(*chars) for null, true, false.

**Comment by danielaparker** [comment]
Thanks for reporting this! Fixed on master.
