### ISSUE TITLE
json_query skips over arrays in path result

### ISSUE THREAD

**Issue by bergmansj** [danielaparker/jsoncons#177]
The following snippet
```C++
    json test = json::parse(R"(
    {
      "books": [
        {"title": "b1", "chapters":[{"subtitle":"b1c1"}]},
        {"title": "b2", "chapters":[{"subtitle":"b2c1"}]}
      ]
    } )");
    json path_result = json_query(test, "$..[?(@.subtitle == 'b2c1')]", result_type::path);

    std::cout << path_result.to_string() << std::endl;
```
prints out 
```
  ["$['books']['chapters'][0]"]
``` 
while I expected `["$['books'][1]['chapters'][0]"]`

It seems that the path result skips array indices, which prohibits me from finding the location of the matched data item in the json structure.

**Comment by danielaparker** [comment]
Thanks for reporting this. The query will return the correct value result, but the path result is incomplete. In the presence of the ".." recursive descent notation, the evaluator is not keeping enough information on the stack to compute the entire path. Will investigate.

**Comment by danielaparker** [comment]
Fixed on master

**Comment by bergmansj** [comment]
Seems to work ok now. Good to have such a swift response 👍
