### ISSUE TITLE
String construction bug in json_encoder.hpp

### ISSUE THREAD

**Issue by Cebtenzzre** [danielaparker/jsoncons#179]
https://github.com/danielaparker/jsoncons/blob/c68cf331a53d34ee6943b2809f92957f9b7cb859/include/jsoncons/json_encoder.hpp#L356-L360
https://github.com/danielaparker/jsoncons/blob/c68cf331a53d34ee6943b2809f92957f9b7cb859/include/jsoncons/json_encoder.hpp#L366-L370

This calls the `basic_string(count, ch)` constructor.  This code probably intends to use the initializer_list constructor.

**Comment by danielaparker** [comment]
Thanks for reporting this. It appears there were no test cases for those two options, issue has been fixed and test cases added on master.
