### ISSUE TITLE
CMAKE_BUILD_TYPE when BUILD_TESTS in on

### ISSUE THREAD

**Issue by GMellar** [danielaparker/jsoncons#180]
I don't know if this is really an issue but I'm using this great library in some projects now and include it as submodule in cmake. The problem is that it always alters the build type when tests are enable (which is the default). The CMAKE_BUILD_TYPE variable should be touched in a console call but not within any cmake list files.

**Comment by danielaparker** [comment]
Thanks for reporting this. I added a `if(NOT CMAKE_BUILD_TYPE)` around those lines on master. Please let me know if that fixes the issue.

**Comment by GMellar** [comment]
Thank you for adding this in the master branch so fast. This works well and integrating this project inside my project is now possible without having a custom branch.
