### ISSUE TITLE
private constructor for serializing / deserializing custom objects

### ISSUE THREAD

**Issue by rbroggi** [danielaparker/jsoncons#182]
Hi all,

As ```JSONCONS_TYPE_TRAITS_FRIEND``` is used for accessing private fields within serialization / deserialization, would be a nice feature to have a dedicated MACRO  to be able to declare the empty constructor as a private field so that only the deserialization frameworks can use it: it allows users to create pseudo-immutable data classes and enforce users to use the right constructors.

Thank you and best regards,
Rodrigo

**Comment by danielaparker** [comment]
Hi Rodrigo,

You raised an issue that I hadn't thought about. `JSONCONS_TYPE_TRAITS_FRIEND ` makes the private members accessible to the `json_type_traits` specializations, but there are a number of other functions and classes that assume a public default constructor. While we could add a dedicated macro as you suggest, I would prefer to rewrite those other functions and classes to not require a public default constructor. That way for `JSON_MEMBER_TRAITS_DECL` it would be enough to use `JSONCONS_TYPE_TRAITS_FRIEND `, and for  `JSON_GETTER_CTOR_TRAITS_DECL`, it would not be necessary to supply a default constructor at all.

Best regards,
Daniel

**Comment by rbroggi** [comment]
Well you got exactly what I meant. I didn't suggested to change the current macros because I still don't know fully their behaviors but that was exactly my first thought... 
That will be great to have...

Thank you for your fast reply.

Best,
Rodrigo

**Comment by danielaparker** [comment]
This is now implemented on master.

Types that are specialized in `json_type_traits` are no longer required to have a public default
constructor. In particular, types that are specialized using `JSONCONS_MEMBER_TRAITS_DECL`
or `JSONCONS_NONDEFAULT_MEMBER_TRAITS_DECL` may have a private default constructor + `JSONCONS_TYPE_TRAITS_FRIEND`,   and types that are specialized with `JSONCONS_GETTER_CTOR_TRAITS_DECL` are not required to have a default  constructor at all.

**Comment by rbroggi** [comment]
Thank you for the support Daniel
