### ISSUE TITLE
JSON-ify a template struct

### ISSUE THREAD

**Issue by lhy0403** [danielaparker/jsoncons#183]
Can I serialise a template struct?
 e.g. 
```c++
template <typename XTYPE>
struct myStruct
{
      XTYPE typeContent;
      std::string someString;
}
```

**Comment by lhy0403** [comment]
How can I use `JSONCONS_MEMBER_TRAITS_DECL` and specify a type parameter?

**Comment by danielaparker** [comment]
Currently, if you wish to use `JSONCONS_MEMBER_TRAITS_DECL` to generate the traits, you need to declare a trait for each specialization, e.g.
```
typedef myStruct<std::pair<int, int>> myType;
JSONCONS_MEMBER_TRAITS_DECL(myType,typeContent,someString)
```

Alternatively, you can specialize `json_type_traits` manually,

```c++
namespace jsoncons {
    template <class Json, class XTYPE>
    struct json_type_traits<Json, myStruct<XTYPE>>
    {
        typedef typename Json::allocator_type allocator_type;

        static bool is(const Json& j) noexcept
        {
            return j.is_object() && j.contains("typeContent") && j.contains("someString");
        }

        static myStruct<XTYPE> as(const Json& j)
        {
            myStruct<XTYPE> val;
            val.typeContent = j.as("typeContent");
            val.someString = j.as("someString");
            return val;
        }

        static Json to_json(const myStruct<XTYPE>& val, const allocator_type& allocator = allocator_type())
        {
            Json j(allocator);
            j.try_emplace("typeContent", val.at("typeContent"));
            j.try_emplace("someString", val.at("someString"));
            return j;
        }
    };
}
```
In both cases,

```c++
myStruct<std::pair<int,int>> val;
 val.typeContent = std::make_pair(1,2);
 val.someString = "A string";

 std::cout << val.typeContent.first << ", " << val.typeContent.second << ", " << val.someString << "\n";
```
Output:
```
1, 2, A string
```

But I'll look into adding another macro that will do this.

**Comment by lhy0403** [comment]
Thanks! Another MACRO would be very useful for this case.

**Comment by danielaparker** [comment]
The following new macros are now on master:

-JSONCONS_TEMPLATE_MEMBER_TRAITS_DECL(num_template_params,class_name,member_name1,member_name2,...)`
- `JSONCONS_TEMPLATE_STRICT_MEMBER_TRAITS_DECL(num_template_params,class_name,member_name1,member_name2,...)`
- `JSONCONS_TEMPLATE_GETTER_CTOR_TRAITS_DECL(num_template_params,class_name,getter_name1,getter_name2,...)`

`JSONCONS_TEMPLATE_MEMBER_TRAITS_DECL`, `JSONCONS_TEMPLATE_STRICT_MEMBER_TRAITS_DECL` and `JSONCONS_TEMPLATE_GETTER_CTOR_TRAITS_DECL`
are for specializing `json_type_traits` for template types. The parameter `num_template_params` gives the number of template parameters. 

So in the example, use

JSONCONS_TEMPLATE_MEMBER_TRAITS_DECL(1,myType,typeContent,someString)
