### ISSUE TITLE
Visual Studio 2013

### ISSUE THREAD

**Issue by xtremi** [danielaparker/jsoncons#185]
I've used jsoncons with VS2017 projects without problems. 
I'm trying now to use it in a VS2013 project (Toolset v120) and get a few compilation errors. 
I can see VS2013 is not under supported compilers, but has it been tested before?

**Comment by danielaparker** [comment]
At one time, but we dropped it as a supported compiler when it became too troublesome to `#define` around its limitations.

**Comment by xtremi** [comment]
Ok, I understand. Thank you for the quick response!
