### ISSUE TITLE
Deprecation warning for jsoncons::json.get()

### ISSUE THREAD

**Issue by alekseyt** [danielaparker/jsoncons#186]
This is not a big deal, if you don't think any action is needed then i'll close this issue.

```c++
JSONCONS_DEPRECATED_MSG("Instead, use at(const string_view_type&)")
    const basic_json& get(const string_view_type& name) const
```

Warning suggests to use `at("something")` instead of `get("something")`, the problem with this is that `at("something")` throws (makes sense), however `get("something")` didn't throw but returned null object instead. Therefore it wasn't enclosed with `try {} catch {}`. So at least in my case, correct replacement for `get("something")` was `get_with_default("something", jsoncons::json())`.

I think it might be helpful to someone to at least reword warning message to something like 

>Instead, use at(const string_view_type&) or get_with_default(const string_view_type&, T&&)

as another overload of `get()` already suggests.

Another related issue is that `__attribute((deprecated))` is used to show deprecated warnings. Warnings are printed if clang or GCC with `-std=c++14` is used, however GCC with `-std=c++11` doesn't print this warning even with `-Wall -Wextra` because it's C++14 feature. So deprecated calls compiled with `-std=c++11` compiles cleanly without any deprecation warnings.

I assume this works as intended, just FYI, something to consider before removing those.

**Comment by danielaparker** [comment]
Thanks for spotting that, will address when I get back from holidays.

**Comment by danielaparker** [comment]
Incidentally, your replacement for `get("something")` should have been `get_with_default("something", jsoncons::json::null())` (the default `json` constructor produces an empty object), but I've added a single argument overload of `get_with_default` on master with the same semantics as `get("something")`, the deprecation message has been updated accordingly. Also, the deprecation messages should now show on all supported versions of GCC and clang.

**Comment by alekseyt** [comment]
>your replacement for get("something") should have been get_with_default("something", jsoncons::json::null())

Thank you for pointing that out.

I can confirm that GCC 8 prints deprecation warnings with out without `-std=c++11`, `get_with_default()` also works great. Thank you very much.
