### ISSUE TITLE
Inserting object after deleting it fails

### ISSUE THREAD

**Issue by jkalmar** [danielaparker/jsoncons#188]
Hi,  
I'm using jsonpointer to insert and remove object from json, but it seems that after I remove object from json I'm unable to add any more objects. Please check sample code:
     
      jsoncons::ojson oj;

      std::error_code ec;

      jsoncons::jsonpointer::insert_or_assign( oj, "/test", jsoncons::ojson(), ec );
      std::cout << "After first insert: " << std::endl << jsoncons::pretty_print( oj ) << std::endl;

      jsoncons::jsonpointer::remove( oj, "/test", ec );
      std::cout << "After remove of the added object: " << std::endl << jsoncons::pretty_print( oj ) << std::endl;

      std::cout << "Befor second insert: " << std::endl;
      jsoncons::jsonpointer::insert_or_assign( oj, "/t", jsoncons::ojson(), ec );
      std::cout << "After second insert: " << std::endl << jsoncons::pretty_print( oj ) << std::endl;

Output:
>After first insert: 
{
    "test": {}
}
After remove of the added object: 
{}
Befor second insert: 
 *** Generic error *** 
vector::_M_range_check: __n (which is 0) >= this->size() (which is 0)
  
Am I using it wrong or is this a known issue?

**Comment by danielaparker** [comment]
Thanks for reporting this. There was a defect in the `erase` functions for  the order preserving `basic_json` specializations, in  particular, for `ojson`.  This has been fixed on master, and test cases added.

**Comment by jkalmar** [comment]
Thanks, it is working now.

**Comment by danielaparker** [comment]
Patch release v0.136.1 includes this fix.
