### ISSUE TITLE
Is the support planned ~ (getting the parameter name) in jsonpath?

### ISSUE THREAD

**Issue by sergkukuev** [danielaparker/jsoncons#194]
Dear Daniel, 
currently not working sign '~' in jsonpath. Is the support planned?

**Example:**
Input (json):
``` json
{
  "firstName": "John",
  "lastName" : "doe",
  "age"      : 26,
  "address"  : {
    "streetAddress": "naist street",
    "city"         : "Nara",
    "postalCode"   : "630-0192"
  },
  "phoneNumbers": [
    {
      "type"  : "iPhone",
      "number": "0123-4567-8888"
    },
    {
      "type"  : "home",
      "number": "0123-4567-8910"
    }
  ]
}
```

Input (jsonpath): 
`$.*~`

Result:
`
[
  "firstName",
  "lastName",
  "age",
  "address",
  "phoneNumbers"
]
`

**Comment by danielaparker** [comment]
I wasn't familiar with the `~` syntax, but I understand now that it's an extension to the [Goessner syntax](https://goessner.net/articles/JsonPath/) proposed in [s3u/JSONPath](https://github.com/s3u/JSONPath). 

In jsoncons, you can use a function for this:
```
json j = jsonpath::json_query(root, "keys($)");
``` 
Output:
```
[["address","age","firstName","lastName","phoneNumbers"]]
```

**Comment by sergkukuev** [comment]
Not yet, I only saw online converters like this https://jsonpath.com/. Thanks for the answer!
