### ISSUE TITLE
Access values in cbor/bson/ubjson

### ISSUE THREAD

**Issue by davidglavas** [danielaparker/jsoncons#197]
Is it possible to directly access values in cbor, bson, or ubjson objects (without first converting them back to an ordinary json object)?

**Comment by danielaparker** [comment]
If you mean random access of values, the answer is not anymore. We used to have that for CBOR, but removed it in v0.109.0. Until then, we had `cbor_view`, which held a a pointer and a size, and which supported most of the read-only interface of `basic_json`, e.g. 
```c++
// a non-owning view of the CBOR bytes
cbor::cbor_view view = /* some CBOR */; 

// Loop over outer array elements
for (cbor::cbor_view row : bv.array_range())
{    
    // Get element at position /0/1 using jsonpointer::get on cbor_view 
    cbor::cbor_view val = jsonpointer::get(row, "/0/1");
    std::cout << "(3) " << val.as<std::string>() << "\n\n";
}
```
But as far as I could tell, there wasn't much interest in this, and it would have been a lot of work to similarly support bson, message pack, and ubjson, and to support querying these "_view" things with JSONPath.  So it was removed.

Also, keep in mind that random access on `cbor_view` is very inefficient, CBOR is not designed for random access, and it wouldn't have taken many random accesses before performing more work parsing than parsing the whole thing once into a `basic_json`. The only reasonably efficient operation is iteration, but if that's what you want to do, you can do that by reading the CBOR as a stream of parse events, using `cbor_bytes_cursor` or `cbor_stream_cursor`.

**Comment by davidglavas** [comment]
So before v0.109.0 it was possible to use a json pointer (eg. "/employees/josh/friends/1") to access any value in the CBOR document? It indeed sounds like a lot of work to support this for all the binary formats :p

In versions before v0.109.0, how is this access to values in a CBOR document (eg. `jsonpointer::get(row, "/0/1");`) implemented? Do you know the asymptotic time complexity of such an access (big O notation)? Why do you think that accessing values in a `basic_json` is so much faster than accessing values in `cbor_view`?

**Comment by danielaparker** [comment]
The `jsonpointer::get` function is defined on a generic type `J` that satisfies [certain conditions](https://github.com/danielaparker/jsoncons/blob/master/doc/ref/jsonpointer/get.md), and applies to any type satisfying those conditions, a `basic_json` satisfies those conditions, but there is no assumption that type `J` _is_ a `basic_json`. A `cbor_view` had an `is_array()`, `is_object()`, `size()`, `contains()` and `at()` functions. The main difficulty was that the `cbor_view::at()` functions returned a `cbor_view` value (containing a pointer into the original CBOR bytes), while the `basic_json::at()` functions returned a reference to a value stored in a `basic_json`, hence the `typename std::enable_if<is_accessible_by_reference<J>::value,J&>::type` expressions in the `jsonpointer::get` function definitions, to handle both cases. The same approach could have been taken with the `jsonpath::json_query` function, except it would have been more complicated.

The complexity for a `basic_json` search on an object by name is logarithmic in the size of the object ( O(log n)), and the complexity for a `basic_json` index operation on an array is constant (O(1)). I contrast, any search or index operation on a `cbor_view` would be a linear (O(n)).
