### ISSUE TITLE
JSON path result type.

### ISSUE THREAD

**Issue by andysCaplin** [danielaparker/jsoncons#198]
Is it possible to introduce a result type option for jsoncons::jsonpath::json_query() that returns a JSON object instead of an array of values - i.e. similar to the result returned by the jayway JSON path evaluator - https://jsonpath.herokuapp.com/ ? 

In our use case we have JSON objects like this 

{"Bid":"100","Ask":"200","Last":"300"}

and queries like this

$['Bid','Ask']

The query result is an array of the values 

[   "100",   "200" ]

What we need is a result type that would return the result returned by jayway for the same query

{
   "Bid" : "100",
   "Ask" : "200"
}

**Comment by danielaparker** [comment]
Not sure, I'd have to think about it. The Jayway JsonPath feature to extract a subset of members from a json object is actually a bug in the Jayway JsonPath parser, see [[,] is intersection, not a union operator for field names](https://github.com/json-path/JsonPath/issues/395).

**Comment by andysCaplin** [comment]
Ok. Cheers. Just to clarify, our problem is in the case where a field name is not found. In that case we can't be certain what value's were found.

**Comment by danielaparker** [comment]
Oh, okay. You can do intersections with the current syntax like this:
```c++
std::string input = R"(
[
    {"Bid":"100","Ask":"200","Last":"300"},
    {"Bid":"100","Last":"300"},
    {"Bid":"110","Ask":"220"}
]
)";

json root = json::parse(input);

json result = jsonpath::json_query(root,"$..[?(@.'Bid')][?(@.'Ask')]");
std::cout << "result: " << result << "\n";
```
Result:
```
[{"Ask":"200","Bid":"100","Last":"300"},{"Ask":"220","Bid":"110"}]
```

**Comment by andysCaplin** [comment]
Thanks for the response. 

What we need is not so much an intersection as a union I guess. I mean that, given a set of field value pairs in out JSON object, we want to fish  out a selection of field value pairs. 

I.e. if we have a JSON object of {"Bid":"100","Ask":"200","Last":"300","First":"50"} and we want to select Bid and Last we need to get

["Bid":"100","Last":"300"]

I've experimented with the syntax a fair bit and I can't get a version that does this. The best I can get is an array of the values only and if some values are missing then we can't know what names the returned values relate to.

I mean say I asked for Bid, Ask, X and Y. I'll get

["100","300"] 

because X and Y aren't in the object. But from the response I have no way of knowing what field names these values are for.

**Comment by danielaparker** [comment]
The best I can suggest for now is to use an intersection to select objects that contain both Bid and Ask, and a C++ for loop to extract Bid and Ask, 

```c++
#include <jsoncons/json.hpp>
#include <jsoncons_ext/jsonpath/json_query.hpp>

using namespace jsoncons;

int main()
{
    std::string input = R"(
    [
        {"Bid":"100","Ask":"200","Last":"300"},
        {"Bid":"100","Last":"300"},
        {"Bid":"110","Ask":"220"},
        {"Bid":"100","Ask":"205","Last":"300","First":"50"}
    ]
    )";

    json root = json::parse(input);

    json result = jsonpath::json_query(root, "$..[?(@.'Bid')][?(@.'Ask')]");

    for (const auto& item : result.array_range())
    {
        std::cout << item["Bid"] << "," << item["Ask"] << "\n";
    }
}
```
Regarding the jayway comparison, jayway is the odd man out according to [https://cburgmer.github.io/json-path-comparison/](https://cburgmer.github.io/json-path-comparison/results/key_bracket_notation_union.html)
and in fact itself [2.5 Milestone](https://github.com/json-path/JsonPath/milestone/4) (second item).

**Comment by andysCaplin** [comment]
Thanks for the example but that isn't our use case. Our data is a list of field/value pairs that occur once per instance.
In some cases the user is just interested in a subset of the field/value pairs and doesn't want to get all of them but he has to be able to identify which value goes with which field name.

We can represent in different ways to suit any selector that would work. I've tried

{"Bid":"100","Ask":"200","Last":"300"}

{{"Bid":"100"},{"Ask":"200"},{"Last":"300"}}
 
[{"Bid":"100"},{"Ask":"200"},{"Last":"300"}]

I haven't managed to find a representation or a selector that can achieve this.

The only thing I can think of is to double up the name which seems wasteful i.e.

{"Bid":{"Bid":"100"},"Ask":{"Ask":"200"},"Last":{"Last":"300"}}

$.'Bid','Ask'

Result in evaluator

[
   {
      "Bid" : "100"
   },
   {
      "Ask" : "200"
   }
]

**Comment by danielaparker** [comment]
Okay, but I think that's a limitation of JSONPath, not on jsoncons's implementation of it. We're also going to be adding an implementation of [JMESPath](http://jmespath.org/), which may be an option going forward.
