### ISSUE TITLE
json_query() is reordering arrays.

### ISSUE THREAD

**Issue by andysCaplin** [danielaparker/jsoncons#200]
When I call json_query() on an array it reorders the results. i.e if I have 

JSON:          {"book":[{"author":"C"},{"author":"B"},{"author":"A"}]}
query:          $.book[0,1]
result           [{"author":"B"},{"author":"C"}]

I get the correct contents but in the wrong order. I expected to get  [{"author":"C"},{"author":"B"}]

Is there any way to make the query preserve the order ?

I wrote this code to test it ( I initially thought it may have been the print that was the issue )

   
    char *jsonString = (char *)"{\"book\":[{\"author\":\"C\"},{\"author\":\"B\"},{\"author\":\"A\"}]}";
    jsoncons::json_options print_options;

    print_options.new_line_chars("");
    print_options.indent_size(0);
    print_options.spaces_around_comma(jsoncons::spaces_option::no_spaces);
    print_options.spaces_around_colon(jsoncons::spaces_option::no_spaces);

    try {
        jsoncons::json json = jsoncons::json::parse(jsonString);
        std::ostringstream ss;
        ss << jsoncons::pretty_print(json, print_options);
        printf("<%s>\n\n", ss.str().c_str());
        ss.str(std::string());

        jsoncons::json qjson = jsoncons::jsonpath::json_query(json, "$.book[0,1]");
        ss << jsoncons::pretty_print(qjson, print_options);
        printf("<%s>\n\n", ss.str().c_str());
        ss.str(std::string());

        jsoncons::json qqjson = jsoncons::jsonpath::json_query(qjson, "$[0]");
        ss << jsoncons::pretty_print(qqjson, print_options);
        printf("<%s>\n\n", ss.str().c_str());
        ss.str(std::string());
    } catch (const jsoncons::jsonpatch::jsonpatch_error& e) {
        printf("<%s>\n", e.what());
    }

**Comment by andysCaplin** [comment]
Actually if I use [:2] instead of [0,1] I get the right answer but in the JSON path doc it doesn't mention that one method re-orders and the other doesn't.

**Comment by andysCaplin** [comment]
Actually if I use [:2] instead of [0,1] I get the right answer but in the JSON path doc it doesn't mention that one method re-orders and the other doesn't.

**Comment by danielaparker** [comment]
Reopening, this is a defect. The re-ordering you see with [0,1] is a consequence of how jsoncons removes duplicates from unions, but it should preserve the order. Thanks for reporting this.

**Comment by danielaparker** [comment]
Fixed on master. You'll now see the expected ` [{"author":"C"},{"author":"B"}]`.

**Comment by danielaparker** [comment]
Fix is in Release 0.142.0.
