### ISSUE TITLE
decode_csv error

### ISSUE THREAD

**Issue by earonjohnson** [danielaparker/jsoncons#202]
I am receiving an error stating "csv::decode_csv is not a member of jsoncons::csv"

**Comment by danielaparker** [comment]
Taken literally, the message is correct, but I'd need to see an example as to how you got it. Could you post an example that reproduces it?

Thanks,
Daniel

**Comment by earonjohnson** [comment]
Thank you for the quick response! I simply copied the code from an example you provided, and edited it to fit my program and i received the error.

 if(fin.is_open())
        {
                csv::csv_options options;
    options.assume_header(true)
           .trim(true)
           .ignore_empty_values(true)
           .column_types("integer,string,string,string");
    ojson tasks = csv::decode_csv<ojson>(fin, options); // Error is here

Hope this helps.

**Comment by danielaparker** [comment]
Should be 
```
ojson tasks = csv::decode_csv<ojson>(fin, options); 
```

**Comment by earonjohnson** [comment]
I don't know why it didn't copy over correctly but I do have the <ojson> following the decode_csv

**Comment by danielaparker** [comment]
Oh, I see. I fixed the formatting so it's displayed correctly.

**Comment by danielaparker** [comment]
Try running this program.
```
#include <jsoncons/json.hpp>
#include <jsoncons_ext/csv/csv.hpp>

using namespace jsoncons;

int main()
{
    std::string input = R"(a,b,c,d
1,2,"foo","baz")";
    std::istringstream is(input);

    csv::csv_options options;
    options.assume_header(true)
        .trim(true)
        .ignore_empty_values(true)
        .column_types("integer,string,string,string");
    ojson tasks = csv::decode_csv<ojson>(is, options);
    std::cout << pretty_print(tasks) << "\n";
}
```
Is there anything about it that's different from yours?

**Comment by earonjohnson** [comment]
Sorry for the late response, But that code worked fine. 

I am using putty on windows 10 

using this to compile the program: g++ -std=c++11 filename.cpp

**Comment by danielaparker** [comment]
Check what header file you're including. If it's `<jsoncons_ext/csv/csv_reader.hpp>`, change it to `<jsoncons_ext/csv/csv.hpp>`.

**Comment by earonjohnson** [comment]
That fixed the problem. Thank you so much!

**Comment by danielaparker** [comment]
On the contrary, thank you for revealing the problem with wrong header files in some of the documentation! That will be fixed in the next release.
