### ISSUE TITLE
Support for jmespath

### ISSUE THREAD

**Issue by jonstewart** [danielaparker/jsoncons#204]
First, thank you very much for `jsoncons`. It's a good library.

**Feature request:** It would be nice if jsoncons also had `jmespath` support that worked in a similar fashion to the `jsonpath` support.

[jmespath](http://jmespath.org/) is a newer alternative to `jsonpath`. It's embedded into both the AWS and Azure CLI utilities and has libraries available in a number of languages. Unlike `jsonpath`, it has a formal spec with conformance tests.

The only other C++ library I've been able to find that promises support for `jmespath` is https://github.com/robertmrk/jmespath.cpp, which uses `nlohmann_json`. It requires building a library with `cmake` and configuring `cmake` to find `nlohmann_json`. The header-only approach that `jsoncons` takes is far preferable as it's easier to integrate into other build systems.

**Comment by danielaparker** [comment]
Thanks for the suggestion, we'll add it to the list.

**Comment by jonstewart** [comment]
Thanks!

**Comment by danielaparker** [comment]
The [jmespath extension](https://github.com/danielaparker/jsoncons/blob/master/doc/ref/jmespath/jmespath.md) has been moved to master. All [compliance tests](https://github.com/jmespath/jmespath.test) pass with the exception of four syntax error tests that as far as I can tell are extra-grammatical as the grammar alone does not rule them out, in those case the jsoncons implementation will fail later during evaluation.

**Comment by jonstewart** [comment]
Oh wow, that’s great! Thanks!! I will give it a try.

**Comment by danielaparker** [comment]
All compliance tests now pass.
