### ISSUE TITLE
type_traits for std::shared_ptr<std::string>

### ISSUE THREAD

**Issue by rbroggi** [danielaparker/jsoncons#206]
Hi Daniel, all,

First of all, I wanted to reinforce that I really love this work/library, thank you for that. After a while I managed to include it in our company private repository, only drawback is that now I'm bind (at least for the moment) to release **0.123.1** 
I've been browsing around to try to understand how to reproduce optional fields in my C++ objects representing optional fields in the underlying JSON. I've gave it a try with having a class with a ```std::shared_ptr<std::string>``` member on it. E.g.:

```cpp
class MetaDataReplyTest {
 public:
  const std::string& GetStatus() const {
    return status;
  }
  const std::string& GetPayload() const {
    return payload;
  }
  const std::shared_ptr<std::string>& GetDescription() const {
    return description;
  }

 private:
  // this allows serialization/deserialization of the objects
  JSONCONS_TYPE_TRAITS_FRIEND;
  std::string status;
  std::string payload;
  std::shared_ptr<std::string> description;
};

JSONCONS_TYPE_TRAITS_DECL(MetaDataReplyTest, status, payload, description)

```

what I'm trying to achieve is to be able to serialize/deserialize those two jsons from/to my object:

```json
    {
      "status": "OK",
      "payload": "Modified",
      "description": "TEST"
    }
```

```json
    {
      "status": "OK",
      "payload": "Modified"
    }
```

It might be possible to do it using the `struct json_type_traits` but I'm not sure about how to do it. 

In the meanwhile, 

Thank you and best wishes for the year to come.

Rodrigo Broggi

**Comment by danielaparker** [comment]
Hi rbroggi ,

If you were on v0.138.0 or later, the statement
```c++
JSONCONS_POLYMORPHIC_TRAITS_DECL(std::string,std::string)
```
would generate the required boilerplate for `std::shared_ptr<std::string>` and `std::unique_ptr<std::string>`.

But as you're on version v0.123.1, this specialization of `json_type_traits` should do:

```c++
namespace jsoncons {
template<class Json, class ValueType>
struct json_type_traits<Json, std::shared_ptr<ValueType>> {
    static bool is(const Json& j, const ValueType& v) noexcept {
        return j.is<ValueType>();
    }

    static std::shared_ptr<ValueType> as(const Json& j) {
        return std::make_shared<ValueType>(j.as<ValueType>());
    }

    static Json to_json(const std::shared_ptr<ValueType>& ptr) {
        if (ptr.get() != nullptr) {
            Json j(*ptr);
            return j;
        }
        else {
            return Json::null();
        }
    }
};
}
```
What version of C++ are you using? If you're on C++ 2017, I'd  suggest looking at `std::optional<T>` for optional values of type `T`. Or if using `boost`, `boost::optional<T>`.

Daniel

**Comment by rbroggi** [comment]
Dear Daniel, thank you very much for your much appreciated support.

**Comment by rbroggi** [comment]
After trying it out I have only one quetion:

Would there be a way to not print a all the json property in case the pointer is null (or the optional is empty)?

Thank you,

Rodrigo

**Comment by danielaparker** [comment]
It's a good question. When we specialize `json_type_traits` for `std::optional<T>` in the library (we don't yet), I'd like it to produce JSON with no value rather than a `null` value in the output, but I haven't fully thought through how to do that.

From another perspective, we could add a serialization option to omit nulls from the JSON.

Daniel

**Comment by rbroggi** [comment]
That would be amazing. Thank you for the fast reply.

**Comment by danielaparker** [comment]
Just FYI, with v0.145.0, and with a compiler that supports C++17, you can do it this way,

```c++
#include <cassert>
#include <jsoncons/json.hpp>

namespace ns
{
    class MetaDataReplyTest 
    {
    public:
        MetaDataReplyTest()
            : description()
        {
        }
        const std::string& GetStatus() const 
        {
            return status;
        }
        const std::string& GetPayload() const 
        {
            return payload;
        }
        const std::optional<std::string>& GetDescription() const 
        {
            return description;
        }
    private:
        JSONCONS_TYPE_TRAITS_FRIEND;
        std::string status;
        std::string payload;
        std::optional<std::string> description;
    };
}

JSONCONS_N_MEMBER_TRAITS(ns::MetaDataReplyTest, 2, status, payload, description)

using namespace jsoncons;

int main()
{
    std::string input1 = R"({
      "status": "OK",
      "payload": "Modified",
      "description": "TEST"
    })";
    std::string input2 = R"({
      "status": "OK",
      "payload": "Modified"
    })";

    auto val1 = decode_json<ns::MetaDataReplyTest>(input1);
    assert(val1.GetStatus() == "OK");
    assert(val1.GetPayload() == "Modified");
    assert(val1.GetDescription());
    assert(val1.GetDescription() == "TEST");

    auto val2 = decode_json<ns::MetaDataReplyTest>(input2);
    assert(val2.GetStatus() == "OK");
    assert(val2.GetPayload() == "Modified");
    assert(!val2.GetDescription());

    std::string output1;
    std::string output2;

    encode_json(val2,output2,indenting::indent);
    encode_json(val1,output1,indenting::indent);

    std::cout << "(1)\n";
    std::cout << output1 << "\n\n";

    std::cout << "(2)\n";
    std::cout << output2 << "\n\n";
}
```
Output:
```
(1)
{
    "description": "TEST",
    "payload": "Modified",
    "status": "OK"
}

(2)
{
    "payload": "Modified",
    "status": "OK"
}
```
With a compiler that does not support C++17, you can use `jsoncons::optional<T>` instead.

Daniell
