### ISSUE TITLE
Disabling pretty print when using basic_json_encoder

### ISSUE THREAD

**Issue by ecorm** [danielaparker/jsoncons#207]
Using this [example](https://github.com/danielaparker/jsoncons/blob/master/doc/ref/basic_json_encoder.md), the only way to completely disable pretty-printing is to use the following options:

```c++
auto opts = json_options()
        .indent_size(0)
        .spaces_around_colon(spaces_option::no_spaces)
        .spaces_around_comma(spaces_option::no_spaces)
        .new_line_chars("")
        .object_object_line_splits(line_split_kind::same_line)
        .array_object_line_splits(line_split_kind::same_line)
        .object_array_line_splits(line_split_kind::same_line)
        .array_array_line_splits(line_split_kind::same_line);
```
...which is a bit inconvenient.

When used for network serialization, it's important to be able to disable pretty-printing to reduce message sizes, especially for deeply-nested objects.

When used for serialization, the speed penalty of checking all the `json_options` at runtime may be something to consider if it's significant (I have no idea if it is). Perhaps there could be a "fast" `basic_json_encoder` with no pretty-printing options, and sensible default formats for numbers that survive round-tripping.

I'm aware of `encode_json`, but I want to be able to encode C++ structures directly to JSON without involving `basic_json` at all.

**Comment by danielaparker** [comment]
Try using json_compressed_string_encoder or `json_compressed_stream_encoder`

**Comment by ecorm** [comment]
I'm kicking myself for missing json_compressed_x_encoder. It works, thanks!

**Comment by ecorm** [comment]
Does `json_compressed_x_encoder` output numbers in a round-trippable fashion by default?

**Comment by danielaparker** [comment]
It's supposed to.
