### ISSUE TITLE
jsonpatch example fails and throws jsoncons::json_runtime_error exception

### ISSUE THREAD

**Issue by dharriso** [danielaparker/jsoncons#209]
Hi Guys

I downloaded your library today and was working through a few of the basic examples.  The example worked just fine however I found that the Jsonpatch example throws a runtime error. Example shown here; https://github.com/danielaparker/jsoncons/blob/master/doc/ref/jsonpatch/jsonpatch.md

Calling what() on the exception it reports "Not an array".
OS is RHEL 7.2.

see code snippet below.

Is there something Im not doing here?

std::string data = R"(
    { "foo": "bar"}
)";
std::string patchData = R"(
        [ 
            { "op": "add", "path": "/baz", "value": "qux" },
            { "op": "add", "path": "/foo", "value": [ "bar", "baz" ] }
        ]
)";
     // Parse the string of data into a json value
     std::error_code ec;
    jsoncons::json doc(data);
    jsoncons::json patch(patchData);
    try {
         jsoncons::jsonpatch::apply_patch(doc, patch, ec);
    } catch (jsoncons::json_runtime_error<std::runtime_error>& e) {
        std::cout << "(1) " << e.what() << std::endl;
        std::cout << "(2) " << ec.message() << std::endl;
    } catch(...) {
        std::cout << "(3) " << std::endl;
    }

**Comment by dharriso** [comment]
Worth metionit that all the tests compiled and passed when using the following target "make test_jsoncons" including the jsonpatch tests i.e. 
[ 62%] Building CXX object tests/CMakeFiles/test_jsoncons.dir/src/jsonpatch/jsonpatch_tests.cpp.o

**Comment by danielaparker** [comment]
These two expressions
```c++
jsoncons::json doc(data);
jsoncons::json patch(patchData);
```
create json string values, which causes the exception.

Instead, for an equivalent to the example, use
```c++
jsoncons::json doc = jsoncons::json::parse(data);
jsoncons::json patch = jsoncons::json::parse(patchData);
```

**Comment by dharriso** [comment]
Hi Daniel

That worked a treat. Appreciate your prompt feedback and library is great

Thanks
