### ISSUE TITLE
Json_encoder error with parameter-type(std::cout)

### ISSUE THREAD

**Issue by ChooseYourPlan** [danielaparker/jsoncons#211]
#### But the code show in the 
https://github.com/danielaparker/jsoncons/blob/master/doc/ref/encode_json.md
doc doesen´t work for me (as far as i can see).

![image](https://user-images.githubusercontent.com/32968964/73399013-c6984280-42e6-11ea-83bf-daa4a4723772.png)

Also tried it with stream_sink<char> but that also failed.

### Error message for std::cout :
`Fehler (activ)	E0289	No Instance of the Constructor ""jsoncons::basic_json_encoder<CharT, Sink>::basic_json_encoder [mit CharT=char, Sink=jsoncons::stream_sink<char>]""			            Argumenttype: (std::ostream, jsoncons::indenting)
`

**Comment by danielaparker** [comment]
That's an error in the documentation, the example was never updated when the code changed, thank you very much for pointing it out. The example should be
```c++
#include <iostream>
#include <map>
#include <tuple>
#include <jsoncons/json.hpp>

using namespace jsoncons;

int main()
{
    std::map<std::string, std::tuple<std::string, std::string, double>> employees =
    {
        {"John Smith",{"Hourly","Software Engineer",10000}},
        {"Jane Doe",{"Commission","Sales",20000}}
    };

    json_stream_encoder encoder(std::cout);

    encoder.begin_object();
    encoder.name("Employees");
    encode_json(employees, encoder);
    encoder.end_object();
    encoder.flush();
}
```
 I've corrected it on master. 

Thanks,
Daniel

**Comment by ChooseYourPlan** [comment]
#### Yes https://github.com/danielaparker/jsoncons/commit/d57a354ac574a66a0648e374cab82567893f3c7e thats it.
Thanks for your fast response,
Tim
