### ISSUE TITLE
parsing empty json file fails

### ISSUE THREAD

**Issue by tgilyova** [danielaparker/jsoncons#216]
Hi,
I get the error "Unexpected end of file at line 1 and column 1" when parsing an empty json file.
```
	std::wifstream wistream("empty.json", ios_base::in);
	wojson json = wojson::parse(wistream);
```
Is it by design?
Thank you.
Best regards,
Tatyana Gileva

**Comment by danielaparker** [comment]
Yes. It's not valid JSON.

**Comment by tgilyova** [comment]
Thank you for the update
