### ISSUE TITLE
Typecast member.key() to string

### ISSUE THREAD

**Issue by eyepatch61** [danielaparker/jsoncons#218]
I am trying to use key and values in an object as a string. Please refer following code for the Idea what I am trying to do :
```
// Let jsonObject be an object having few fields.
for (const auto& member : jsonObject.object_range())
{
    string abc = "Adding strings " + member.key() + member.value();
}
```
I am getting error on above code.
I tried to use `(string)member.key()` which didn't work. I can't find a way in the documentation. Please let me know if anyone can help.

**Comment by eyepatch61** [comment]
I tried member.key().data() and it kind of helped me . I had to go through library code. Add these to documentation please.

**Comment by danielaparker** [comment]
`member.value()` returns a `json` value,  so when concatenating with a string, you need to write
```
string abc = "Adding strings " + member.key() + member.value().as<std::string>();
```

**Comment by eyepatch61** [comment]
Thanks for the clarification. I am wondering what's the data type for member in above code as I want to parse it to the other function and "auto" data type won't work.

**Comment by danielaparker** [comment]
Type of `member` is `json::key_value_type`

Type of `member.key()` is `json::key_type`, which in this case is the same as `std::string`.

Type of `member.value()` is json.

For reference see [basic_json](https://github.com/danielaparker/jsoncons/blob/master/doc/ref/basic_json.md) "Member type" section
