### ISSUE TITLE
snprintf() requires <stdio.h>

### ISSUE THREAD

**Issue by oleh-derevenko** [danielaparker/jsoncons#244]
While cross-compiling from Ubuntu Linux to QXN Neutrino 7.0.0, invocations of snprintf() in /include/jsoncons/detail/write_number.hpp require explicit inclusion of <stdio.h>.

In file included from /home/oder/Party/jsoncons/include/jsoncons/json_encoder.hpp:25:0,
                 from /home/oder/Party/jsoncons/include/jsoncons/pretty_print.hpp:19,
                 from /home/oder/Party/jsoncons/include/jsoncons/basic_json.hpp:29,
                 from /home/oder/Party/jsoncons/include/jsoncons/json.hpp:10,
                 from /home/oder/Party/jsoncons/tests/src/json_options_tests.cpp:4:
/home/oder/Party/jsoncons/include/jsoncons/detail/write_number.hpp: In function 'bool jsoncons::detail::dtoa_scientific(double, char, Result&)':
/home/oder/Party/jsoncons/include/jsoncons/detail/write_number.hpp:299:78: error: there are no arguments to 'snprintf' that depend on a template parameter, so a declaration of 'snprintf' must be available [-fpermissive]
         int length = snprintf(buffer, sizeof(buffer), "%1.*e", precision, val);
                                                                              ^
... (and more like this) ...

**Comment by danielaparker** [comment]
include has been added in master.
