### ISSUE TITLE
Provide template specialization for container types?

### ISSUE THREAD

**Issue by jadthegerbil** [danielaparker/jsoncons#254]
I'm attempting to use jsoncons with some generated code from [rtiddsgen](https://www.rti.com/gettingstarted), but the use of certain templates seems to really trip up jsoncons:

In particular, it seems that a sequence<uint8_t> makes jsoncons think it matches a certain signature, in particular, one with an allocator.  

Is there a way to tell jsoncons, "for types like rti::core::bounded_sequence<uint8_t, unsigned int L>, use a given allocator?" Or, "act like int16_t, as you're fine with that one for some reason!"

./include/jsoncons/converter.hpp: In instantiation of 'Into jsoncons::converter<Into, typename std::enable_if<(((! jsoncons::detail::is_basic_string<Into>::value) && jsoncons::detail::is_back_insertable_byte_container<Container>::value) || jsoncons::detail::is_basic_byte_string<T>::value)>::type>::from(const jsoncons::byte_string_view&, jsoncons::semantic_tag, std::error_code&) const [with Into = rti::core::bounded_sequence<unsigned char, 8192ul>; typename std::enable_if<(((! jsoncons::detail::is_basic_string<Into>::value) && jsoncons::detail::is_back_insertable_byte_container<Container>::value) || jsoncons::detail::is_basic_byte_string<T>::value)>::type = void]':
./include/jsoncons/json_type_traits.hpp:527:74:   required from 'static typename std::enable_if<jsoncons::detail::is_back_insertable_byte_container<Container>::value, T>::type jsoncons::json_type_traits<Json, T, typename std::enable_if<((! jsoncons::is_json_type_traits_declared<T>::value) && jsoncons::detail::is_compatible_array_type<Json, T>::value)>::type>::as(const Json&) [with Container = rti::core::bounded_sequence<unsigned char, 8192ul>; Json = jsoncons::basic_json<char, jsoncons::sorted_policy, std::allocator<char> >; T = rti::core::bounded_sequence<unsigned char, 8192ul>; typename std::enable_if<jsoncons::detail::is_back_insertable_byte_container<Container>::value, T>::type = rti::core::bounded_sequence<unsigned char, 8192ul>]'

./include/jsoncons/basic_json.hpp:3753:57:   required from 'typename std::enable_if<jsoncons::is_json_type_traits_specialized<jsoncons::basic_json<CharT, ImplementationPolicy, Allocator>, T>::value, T>::type jsoncons::basic_json<CharT, ImplementationPolicy, Allocator>::as() const [with T = rti::core::bounded_sequence<unsigned char, 8192ul>; CharT = char; ImplementationPolicy = jsoncons::sorted_policy; Allocator = std::allocator<char>; typename std::enable_if<jsoncons::is_json_type_traits_specialized<jsoncons::basic_json<CharT, ImplementationPolicy, Allocator>, T>::value, T>::type = rti::core::bounded_sequence<unsigned char, 8192ul>]'

src/HelloWorld.hpp:259:1810:   required from 'static jsoncons::json_type_traits<Json, HelloWorld>::value_type jsoncons::json_type_traits<Json, HelloWorld>::as(const Json&) [with Json = jsoncons::basic_json<char, jsoncons::sorted_policy, std::allocator<char> >; jsoncons::json_type_traits<Json, HelloWorld>::value_type = HelloWorld]'
./include/jsoncons/basic_json.hpp:3753:57:   required from 'typename std::enable_if<jsoncons::is_json_type_traits_specialized<jsoncons::basic_json<CharT, ImplementationPolicy, Allocator>, T>::value, T>::type jsoncons::basic_json<CharT, ImplementationPolicy, Allocator>::as() const [with T = HelloWorld; CharT = char; ImplementationPolicy = jsoncons::sorted_policy; Allocator = std::allocator<char>; typename std::enable_if<jsoncons::is_json_type_traits_specialized<jsoncons::basic_json<CharT, ImplementationPolicy, Allocator>, T>::value, T>::type = HelloWorld]'

./include/jsoncons/deser_traits.hpp:36:56:   required from 'static T jsoncons::deser_traits<T, CharT, Enable>::deserialize(jsoncons::basic_staj_cursor<CharT>&, jsoncons::json_decoder<Json, TempAllocator>&, std::error_code&) [with Json = jsoncons::basic_json<char, jsoncons::sorted_policy, std::allocator<char> >; TempAllocator = std::allocator<char>; T = HelloWorld; CharT = char; Enable = void]'

./include/jsoncons/decode_json.hpp:41:71:   required from 'typename std::enable_if<(! jsoncons::detail::is_basic_json<typename std::decay<_Tp>::type>::value), T>::type jsoncons::decode_json(const std::basic_string<CharT>&, const jsoncons::basic_json_decode_options<CharT>&) [with T = HelloWorld; CharT = char; typename std::enable_if<(! jsoncons::detail::is_basic_json<typename std::decay<_Tp>::type>::value), T>::type = HelloWorld]'

src/Hello.cxx:249:66:   required from here
./include/jsoncons/converter.hpp:44:30: error: no matching function for call to 'rti::core::bounded_sequence<unsigned char, 8192ul>::bounded_sequence(const allocator_type&)'
             Into bytes(alloc_);
                              ^

**Comment by danielaparker** [comment]
Can you provide a complete example?

Thanks,
Daniel

**Comment by jadthegerbil** [comment]
[minViableBusted.tar.gz](https://github.com/danielaparker/jsoncons/files/4839507/minViableBusted.tar.gz)
Attached. I stripped down/neutered all the generated boilerplate, and it continues to barf on the 'busted' member.

**Comment by jadthegerbil** [comment]
Looks like I was confused; neither "busted" nor "work" actually work--the first one was hiding the complaints about the second.

**Comment by danielaparker** [comment]
If you hack the `bounded_sequence` class to include the constructor

```c++
bounded_sequence(const allocator_type&) : size_(0)
{
}
``` 
the busted case should work. I would suggest that you try that to see if you run into any other issues. 

In the meantime I can look into rearranging some code so that you can remove that hack. But that will take a few days. 

You could always explicitly specialize `json_type_traits` for `bounded_sequence`, but you may not need to.

**Comment by danielaparker** [comment]
Since v0.154.0, your test case minViableBusted will compile.
