### ISSUE TITLE
Bugs in jsoncons::jsonpath::flatten()

### ISSUE THREAD

**Issue by wbangna** [danielaparker/jsoncons#255]
I wrote a small test program and I think I found two bugs.
https://gist.github.com/wbangna/b15370aab120ff5cc34784374d2189a6

The Output of the program is
```
{
    "$['data'][\"d'ef\"]": "def", 
    "$['data'][\"x\"y'z\"]": "xyz", 
    "$['data']['a\"bc']": "abc", 
    "$['data']['g.hi']": "ghi", 
    "$['data']['j\\kl']": "jkl", 
    "$['data']['m/no']": "mno"
}
1) path: $['data']["d'ef"]: def == def
2) path: $['data']["x"y'z"]: Exception: Expected ] at line 1 and column 14
3) path: $['data']['a"bc']: abc == abc
4) path: $['data']['g.hi']: ghi == ghi
5) path: $['data']['j\kl']: NO MATCH
6) path: $['data']['m/no']: mno == mno

This works:
path: $['data']["x\"y'z"]: xyz == xyz
```

Bug1: flatten() does not escape double quotes correctly. The last line shows that the corrected JSONPath works.
Bug2: json_query() does not work with backslashes.

Edit: Forgot to metion the Version I used: 0.153.1

**Comment by danielaparker** [comment]
You're right, thanks for reporting this. Fixed on master.
