### ISSUE TITLE
Nested array issue

### ISSUE THREAD

**Issue by andysCaplin** [danielaparker/jsoncons#261]
**Describe the bug**
**Enumerate the steps to reproduce the bug**
**Include a small, self-contained example if possible**

Given a json document with a nested array value 'names', e.g.

{ "names" : [ "a", "b", "c", "d" ] }
We've noticed that when the document is updated to remove entries in the nested array, for example when removing "c" and "d" above, we're sent a patchDocument that has the following operations:

OperationType:Remove path:"/names/2"
OperationType:Remove path:"/names/3"

This fails as /names/3 is no longer present once 2 is removed.

According to https://tools.ietf.org/html/rfc6902 it should instead read:

OperationType:Remove path:"/names/2"
OperationType:Remove path:"/names/2"

In https://tools.ietf.org/html/rfc6902 it states

Operations are applied sequentially in the order they
appear in the array. Each operation in the sequence is applied to
the target document; the resulting document becomes the target of the
next operation. Evaluation continues until all operations are
successfully applied or until an error condition is encountered.

**What compiler, architecture, and operating system?**

RedHat Linux 64 bit

**What jsoncons library version?**

0.153.3

**Comment by danielaparker** [comment]
I believe `jsonpatch::apply_patch` works correctly. In your example, the patch should be

```json
[
    {
        "op": "remove",
        "path": "/names/3"
    },
    {
        "op": "remove",
        "path": "/names/2"
    }
]
```
and applying that patch to the source document does give
```json
{
    "names": ["a", "b"]
}
```

However, it looks like there is a bug in `json_patch::from_diff`, which is generating the remove statements in the wrong order.

Daniel

**Comment by andysCaplin** [comment]
Hi - yes sorry. I transcribed the issue and didn't describe it fully. The remove operations mentioned above are being generated by jsoncons in that order when we apply a patch that removes 2 elements.

**Comment by danielaparker** [comment]
The issue with `jsonpatch::diff` should be fixed on master. Thanks very much for reporting this.

**Comment by andysCaplin** [comment]
Thanks for the quick fix - when is the next release ?

**Comment by danielaparker** [comment]
We'll put this into patch release 0.154.2, should be out today or tomorrow.

**Comment by danielaparker** [comment]
Go with latest 0.154.3, not .2
