### ISSUE TITLE
bson 

### ISSUE THREAD

**Issue by NotDark** [danielaparker/jsoncons#264]
how i can decode the pD type

![image](https://user-images.githubusercontent.com/44568476/90038233-c6e2b300-dcf7-11ea-8704-e68c984c1716.png)

i cant remove the Feature request label

**Comment by danielaparker** [comment]
You mean starting from BSON? Then, like this:

```c++
#include <iostream>
#include <jsoncons/json.hpp>
#include <jsoncons_ext/bson/bson.hpp>

using namespace jsoncons;

int main()
{
    std::vector<uint8_t> input = {0x13,0x00,0x00,0x00, // Document has 19 bytes
                                  0x05, // Binary data
                                  0x70,0x44,0x00, // "pD"
                                  0x05,0x00,0x00,0x00, // Length is 5
                                  0x80, // Subtype is 128
                                  0x48,0x65,0x6c,0x6c,0x6f, // 'H','e','l','l','o'
                                  0x00 // terminating null
                                  };

    json j = bson::decode_bson<json>(input);
    std::cout << "JSON:\n" << pretty_print(j) << "\n\n";

    std::cout << "tag: " << j["pD"].tag() << "\n";
    std::cout << "ext_tag: " << j["pD"].ext_tag() << "\n";
    auto bytes = j["pD"].as<std::vector<uint8_t>>();
    std::cout << "binary: " << byte_string_view{bytes} << "\n";
}
```
Output:
```
JSON:
{
    "pD": "SGVsbG8"
}

tag: ext
ext_tag: 128
binary: 48,65,6c,6c,6f
```
Note that pretty printing a `json` value by default encodes byte strings as `base64url` strings, but the `json` value holds the actual bytes.

**Comment by NotDark** [comment]
> You mean starting from BSON? Then, like this:
> 
> ```c++
> #include <iostream>
> #include <jsoncons/json.hpp>
> #include <jsoncons_ext/bson/bson.hpp>
> 
> using namespace jsoncons;
> 
> int main()
> {
>     std::vector<uint8_t> input = {0x13,0x00,0x00,0x00, // Document has 19 bytes
>                                   0x05, // Binary data
>                                   0x70,0x44,0x00, // "pD"
>                                   0x05,0x00,0x00,0x00, // Length is 5
>                                   0x80, // Subtype is 128
>                                   0x48,0x65,0x6c,0x6c,0x6f, // 'H','e','l','l','o'
>                                   0x00 // terminating null
>                                   };
> 
>     json j = bson::decode_bson<json>(input);
>     std::cout << "JSON:\n" << pretty_print(j) << "\n\n";
> 
>     std::cout << "tag: " << j["pD"].tag() << "\n";
>     std::cout << "ext_tag: " << j["pD"].ext_tag() << "\n";
>     auto bytes = j["pD"].as<std::vector<uint8_t>>();
>     std::cout << "binary: " << byte_string_view{bytes} << "\n";
> }
> ```
> 
> Output:
> 
> ```
> JSON:
> {
>     "pD": "SGVsbG8"
> }
> 
> tag: ext
> ext_tag: 128
> binary: 48,65,6c,6c,6f
> ```
> 
> Note that pretty printing a `json` value by default encodes byte strings as `base64url` strings, but the `json` value holds the actual bytes.

not starting from BSON but the "pD" are bson's binary now i need decode that

**Comment by danielaparker** [comment]
If you're starting from JSON, then you need to provide a hint about the encoding of the string. If `base64url`, 

```
int main()
{
     
    std::string input = R"(
{
    "pD": "SGVsbG8"
}
    )";

    json j = json::parse(input);
    std::cout << "JSON:\n" << pretty_print(j) << "\n\n";

    auto bytes = j["pD"].as<std::vector<uint8_t>>(byte_string_arg,semantic_tag::base64url);
    std::cout << "binary: " << byte_string_view{ bytes } << "\n";
}
```
Output:
```
JSON:
{
    "pD": "SGVsbG8"
}

binary: 48,65,6c,6c,6f
```

**Comment by NotDark** [comment]
> If you're starting from JSON, then you need to provide a hint about the encoding of the string. If `base64url`,
> 
> ```
> int main()
> {
>      
>     std::string input = R"(
> {
>     "pD": "SGVsbG8"
> }
>     )";
> 
>     json j = json::parse(input);
>     std::cout << "JSON:\n" << pretty_print(j) << "\n\n";
> 
>     auto bytes = j["pD"].as<std::vector<uint8_t>>(byte_string_arg,semantic_tag::base64url);
>     std::cout << "binary: " << byte_string_view{ bytes } << "\n";
> }
> ```
> 
> Output:
> 
> ```
> JSON:
> {
>     "pD": "SGVsbG8"
> }
> 
> binary: 48,65,6c,6c,6f
> ```

thank now working good

**Comment by danielaparker** [comment]
As far as I can tell, the rough equivalent to the `minibson` code would be
```
std::vector<uint8_t> d(upstream_data_ + 4, upstream_data_ + bytes_transferred);
 json j = bson::decode_bson<json>(d);
 auto bytes = j["m0"]["pD"].as<std::vector<uint8_t>>();
json j2 = bson::decode_bson<json>(bytes );
```

**Comment by NotDark** [comment]
> As far as I can tell, the rough equivalent to the `minibson` code would be
> 
> ```
> std::vector<uint8_t> d(upstream_data_ + 4, upstream_data_ + bytes_transferred);
>  json j = bson::decode_bson<json>(d);
>  auto bytes = j["m0"]["pD"].as<std::vector<uint8_t>>();
> json j2 = bson::decode_bson<json>(bytes );
> ```

yes i forgot the m0 but i found i missing that 5minute ago
