### ISSUE TITLE
jsoncons defines BOOST_HAS_FLOAT128

### ISSUE THREAD

**Issue by amerry** [danielaparker/jsoncons#272]
jsoncons's compiler_support header is defining BOOST_HAS_FLOAT128. This can lead to some interesting compiler errors when mixing jsoncons and boost, depending on header order:

```
 /usr/include/boost/atomic/detail/type_traits/is_iec559.hpp:37:19: error: 'float128_type' is not a member of 'boost'
  struct is_iec559< boost::float128_type >
```

This is because Boost and jsoncons disagree about when to define this (Boost has some extra checks that have to pass), so if you include some boost headers, then include jsoncons, then include more boost headers, the boost config headers can decide that there isn't a float128 type, while jsoncons decides there is, and then further boost headers think there should be a boost::float128_type when there isn't.

**What compiler, architecture, and operating system?**

- Compiler: GCC 5.4.0
- Architecture: x64
- Operating system: Ubuntu 16.04

**What jsoncons library version?**

 - [x] Latest release v0.156.0
 - [x] master

**Comment by danielaparker** [comment]
Thanks for reporting/fixing. Reopened for visibility. 

Fix included in patch release 0.156.1
