### ISSUE TITLE
The logic of this condition is strange

### ISSUE THREAD

**Issue by A-Gaber** [danielaparker/jsoncons#275]
https://github.com/danielaparker/jsoncons/blob/290d8216be071a8b36e021bf5579003723bb82c2/include/jsoncons_ext/jsonpath/jsonpath_function.hpp#L180

can anyone explain this if condition? when is it expected to be used?

**Comment by danielaparker** [comment]
It's basically "if not g++ 4.8", which is the earliest version of g++ that jsoncons supports, and our least compliant C++ 11 compiler. You'll find a number of `#defines` concerning this compiler in the code base. The one you noted omits jsonpath tests that use regular expressions in filters, as g++ 4.8 does not fully support regex,  and these tests would fail.

**Comment by A-Gaber** [comment]
Thanks @danielaparker 
I understand the intention, but for the logic assuming `__GNUC__` is always defined this part of the code will be used with all g++ except only 4.10 ----> 4.n right?
Actually I am using g++ 7.x and I noticed if I compile my library including this header it effects on the performance and on the other libraries.
For example if it is included in my part of the code with libtorch it makes libtorch script loader goes into runtime error!

**Comment by danielaparker** [comment]
No, used with all supported g++ except 4.8 (otherwise our tests would fail with 4.8 build.)

Whatever issue you're having with including `jsoncons_etc/jsonpath/jsonpath.hpp`, I don't see how that could be related to this `#if`/`#endif` block.

**Comment by A-Gaber** [comment]
Yes you are right I mistakenly red the last condition and in that case it is like what you explained.

I agree with you, it not clear how it is related I need to do more test to find out.
Up to this moment my code passes and work as expected if I commented this part.
If I keep it and do not include json_query in my code then it is also ok but once it is included libtorch script loader is not working as expected.

The problem is difficult to find out because I am not using json_query at all just including it causes the issue.

I will try some more test and get back with some clear conclusion.

**Comment by danielaparker** [comment]
Did you have a chance to make some more tests? I would be interested in your observations.

**Comment by danielaparker** [comment]
It doesn't sound to me like it's related to jsoncons, but if you do find something, please let us know.

**Comment by danielaparker** [comment]
Can we close this?
