### ISSUE TITLE
JSON schema validator

### ISSUE THREAD

**Issue by omar-bb** [danielaparker/jsoncons#280]
**JSON schema validator**

* Validating JSON documents based on a JSON Schema
* (Check if the user's input matches program expectations in a simpler way and avoid if statements overload)

**What other libraries (C++ or other) have this feature?**

* [f5-json-schema](https://github.com/KayEss/json-schema) draft-07 (Boost Software License 1.0)
* [JSON schema validator for JSON for Modern C++](https://github.com/pboettch/json-schema-validator) draft-07 (MIT)
* [Valijson](https://github.com/tristanpenman/valijson) draft-07 header-only library, works with many JSON parser implementations (BSD-2-Clause)

**Include a code fragment with sample data that illustrates the use of this feature**

* [Understanding JSON Schema conventions](http://json-schema.org/understanding-json-schema/index.html)

* Schema : 

```json
{
  "type": "object",
  "properties": {
    "first_name": { "type": "string" },
    "last_name": { "type": "string" },
    "birthday": { "type": "string", "format": "date" },
    "address": {
      "type": "object",
      "properties": {
        "street_address": { "type": "string" },
        "city": { "type": "string" },
        "state": { "type": "string" },
        "country": { "type" : "string" }
      }
    }
  }
}
```

* Would match this JSON document :

```json
{
  "first_name": "George",
  "last_name": "Washington",
  "birthday": "22-02-1732",
  "address": {
    "street_address": "3200 Mount Vernon Memorial Highway",
    "city": "Mount Vernon",
    "state": "Virginia",
    "country": "United States"
  }
}
```

**Comment by danielaparker** [comment]
Okay, we'll add it to the list.

**Comment by danielaparker** [comment]
The [jsonschema extension](https://github.com/danielaparker/jsoncons/blob/master/doc/ref/jsonschema/jsonschema.md) is now on master. Feedback appreciated.

**Comment by dineshkumar02** [comment]
@danielaparker , 

I am trying to use the JSON schema validator, by having the json schema is defined in another file, and referring the file,
and referring that file for the validation.

{
  "title": "testing properties",
  "type": "object",
  "properties": {
	"ReferenceToExternalSchema": {
            "$ref": "**other_file.json#/definitions/ExternalType**"
        }
    }
}

The other_file.json is located in the same .cpp file, but while executing the code I am getting the below error.
**Don't know how to load JSON Schema /other_file.json**

Also, I have tested some other basic functionalities with the JSON schema validator, and it's working as expected.

**Comment by dineshkumar02** [comment]
I found the example, in the schema validator documentation.

https://github.com/danielaparker/jsoncons/blob/master/doc/ref/jsonschema/jsonschema.md

**Comment by danielaparker** [comment]
To resolve a reference to an external JSONSchema document, the jsoncons implementation needs a URIResolver provided. The error message "Don't know how to load JSON Schema" suggests you haven't provided one. Compare with the example below, 
  
[Using a URIResolver to resolve references to schemas defined in external files](https://github.com/danielaparker/jsoncons/blob/master/doc/ref/jsonschema/jsonschema.md#using-a-uriresolver-to-resolve-references-to-schemas-defined-in-external-files)

and make sure that `make_schema` is provided with a second argument, 
```
auto sch = jsonschema::make_schema(schema, resolver);
```

**Comment by dineshkumar02** [comment]
Thanks @danielaparker
