### ISSUE TITLE
Consider switching to Github Action

### ISSUE THREAD

**Issue by omar-bb** [danielaparker/jsoncons#283]
Dear daniel,

I think switching to github action may improve the project's workflow and noting that it has a really great support for all kinds of platforms (so we can get rid of appveyor, travis and doozer (that seems outdated) ci and only check on github action when testing)

regards

**Comment by danielaparker** [comment]
Thanks for the suggestion. Will look into it when I have some time. Leave this one open.

**Comment by omar-bb** [comment]
Nice!, I will also work on it and I'll make a PR when i finish it

**Comment by danielaparker** [comment]
A PR would be welcome!

**Comment by samlevy25** [comment]
nice

**Comment by danielaparker** [comment]
We now use github actions for macos, ubuntu, and windows.
