### ISSUE TITLE
unused parameter 'tag'

### ISSUE THREAD

**Issue by dirk1730** [danielaparker/jsoncons#284]
When compiling, clang outputs:
    
```
jsoncons/basic_json.hpp:732:54: error: unused parameter 'tag' [-Werror,-Wunused-parameter]
       array_storage(const array& val, semantic_tag tag, const Allocator& a)
                                                     ^
jsoncons/basic_json.hpp:819:65: error: unused parameter 'tag' [-Werror,-Wunused-parameter]
       explicit object_storage(const object& val, semantic_tag tag, const Allocator& `a)
```

In both cases, the parameter tag is not used.

- Compiler: clang11
- Architecture (e.g. x86, x64) x64
- Operating system: linux

**Comment by danielaparker** [comment]
Thanks for reporting this one, and the other one. Could you check if you still see them with the latest code on master? I don't have access to a clang11 build environment to verify.

**Comment by dirk1730** [comment]
Hello Daniel,

Thanks for the quick fix. Both issues compile fine now!

Thanks, Dirk.

**Comment by dirk1730** [comment]
Fixed in https://github.com/danielaparker/jsoncons/commit/6cc08fce6dd6148c5abd0b05c054ffe2e19c2894
