### ISSUE TITLE
Cygwin support

### ISSUE THREAD

**Issue by schaumb** [danielaparker/jsoncons#295]
**Describe the proposed feature**

Currently there are no `CYGWIN.cmake` file in `build_files/cmake` directory. 
This is needed us to building jsoncons json lib in windows with cygwin toolset.

**What other libraries (C++ or other) have this feature?**

-

**Include a code fragment with sample data that illustrates the use of this feature**

-

**Comment by danielaparker** [comment]
Thanks for the feedback. We're currently restructuring the cmake files, and will be eliminating those platform specific files, as they no longer serve any purpose.

**Comment by danielaparker** [comment]
The platform specific files have been removed on master.
