### ISSUE TITLE
JSON Schema patch add operation failed

### ISSUE THREAD

**Issue by dineshkumar02** [danielaparker/jsoncons#297]
I am trying the example, which is mentioned in the documentation, and I am getting the $subject as error.

https://github.com/danielaparker/jsoncons/blob/master/doc/ref/jsonschema/jsonschema.md

In this documentation, trying with **Default** section code.

**Output/Error**
Patch: [{"op":"add","path":"#/bar","value":"bad"}]
Original data: {}
JSON Patch add operation failed

The patch should be applied the missing the keys

Throwing error message.

**Enumerate the steps to reproduce the bug**
The same example, which is mentioned the documentation.

**Include a small, self-contained example if possible**

**What compiler, architecture, and operating system?**

- Compiler: Microsoft (R) C/C++ Optimizing Compiler Version 19.27.29111 for x64
- Architecture (e.g. x86, x64) x86
- Operating system: Windows

**What jsoncons library version?**

 - [ ] Latest release v0.154.1
 - [ ] Other release ______
 - [x] master

**Comment by danielaparker** [comment]
Fixed on master

**Comment by dineshkumar02** [comment]
Thank you @danielaparker , Let me try the same example

**Comment by danielaparker** [comment]
Can we close this?

**Comment by dineshkumar02** [comment]
Thanks @danielaparker for fixing this issue. I have tested the functionality, and it's working as documented.

Thank you again for your help.
