### ISSUE TITLE
"Transforming JSON with filters" wiki page has incorrect examples

### ISSUE THREAD

**Issue by amerry** [danielaparker/jsoncons#30]
The do_name() etc overrides of json_filter have second parameter of type "int", rather than "size_t".

This can be spotted by using the "override" keyword instead of "virtual" - this will make compilation fail.

**Comment by amerry** [comment]
In addition, the includes listed in the example don't work on GCC. This is a fairly common thing with jsoncons - including a random jsoncons header without first including <jsoncons/json.hpp> often fails, because, say, jsoncons/json_serialiser.hpp includes jsoncons/json2.hpp *within its include guard*, and then jsoncons/json2.hpp tries to include jsoncons/json_serialiser.hpp (which has no effect, due to the include guard), and then tries to refer to jsoncons::basic_json_serialiser, which hasn't been declared yet.

**Comment by danielaparker** [comment]
The example with incorrect do_name and do_string_value overrides has been fixed on master. I also followed your suggestion of using the override keyword.

I'll have a look at the header issues separately.

**Comment by danielaparker** [comment]
I reorganized the header files to address these specific issues, jsoncons/json2.hpp has been removed from jsoncons/json_serialiser.hpp, and the example now compiles with just the includes listed in the example.
