### ISSUE TITLE
No exception thrown when using an empty json path on calling json_query

### ISSUE THREAD

**Issue by Flow86** [danielaparker/jsoncons#305]
After upgrading from v0.144.0 I encountered an issue when using an empty json path:
With the old version I got an exception thrown "The provided JSONPath is incorrect.".
With the new version, an empty result is returned.

*I thought that an empty json path is invalid?*

**What is the expected behavior?**
Exception thrown when using an empty json path (= invalid) on calling json_query

**What is the actual behavior?**
An empty result is returned.

**Enumerate the steps to reproduce the bug**
query jsoncons::jsonpath::json_query with an empty path

**Include a small, self-contained example if possible**
```c++
auto json = jsoncons::json::parse(R"({ "a": 1 })");
auto path = "";
auto result = jsoncons::jsonpath::json_query(json, path);
// expected: exception jsoncons::jsonpath::jsonpath_error thrown
// actual: result.empty() == true
```

**What compiler, architecture, and operating system?**

- Compiler: MSVC / clang
- Architecture: x64
- Operating system: Windows, Linux (Debian)

**What jsoncons library version?**
 - Latest release v0.160.0

**Comment by Flow86** [comment]
Ah, It seems this behavior was changed in #720

**Comment by danielaparker** [comment]
Reopening. It was changed, but I'm no longer sure that was right. We're currently working on a major rewrite of the jsonpath extension, and may reconsider that.

**Comment by danielaparker** [comment]
As of the next release, 0.161.0, an empty JSONPath string will be regarded as a syntax error and an error will be raised, see #306.
