### ISSUE TITLE
jsonpath issue

### ISSUE THREAD

**Issue by andysCaplin** [danielaparker/jsoncons#308]
In our code we allow the application to pass JSON path strings to be applied to our JSON objects.
To test the JSON path string is valid we apply it to an empty JSON object - as shown below

```c
                    try {
                        jsoncons::json result2 = jsoncons::jsonpath::json_query( jsoncons::json::parse("{}"), ptr);
                    } catch (const jsoncons::jsonpath::jsonpath_error& e) {
                        ds_log(event_log, DS_LOG_NOTIFY, "JSON: <%s> couldn't create query with params <%s> error <%s>\n", obj->name, ptr, e.what());
                        jparams->invalid_path = 1;
                    }
```

We have a unit test that attempts to use the path expression
```
$[childOrders[0,1]]
```

Up to jsoncons 0.160.0 this worked ok. But since 0.161.0 I get a failure with this log

```
<$[childOrders[0,1]]> error <Expected '$' or function expression at line 1 and column 19>
```

We were on 0.160.0 and I was upgrading to 0.162.1. The issue happens 0.161.0 and every version after.

**Comment by danielaparker** [comment]
Allowing a path expression such as `childOrders[0,1]` inside square brackets notation was a jsoncons extension.  Since 0.161.0, this needs to be written as $[@.childOrders[0,1]], see [JSONPath extension revisited](https://github.com/danielaparker/jsoncons/issues/306).

**Comment by andysCaplin** [comment]
Sorry, as you were writing this I looked at the release notes for 161 - which I should have done first and saw that the path stuff had changed.

**Comment by andysCaplin** [comment]
That suggested change works fine. I tested it. Will update our doc. Sorry again.
