### ISSUE TITLE
More warnings: Android

### ISSUE THREAD

**Issue by geiseri** [danielaparker/jsoncons#309]
**Describe the bug**

`include/jsoncons/detail/parse_number.hpp:861` and `include/jsoncons/detail/parse_number.hpp:874` have errors that length is unused: `operator()(const CharT* s, std::size_t length) const`.  it's odd though because amd64 native compiled just fine, it just seemed clang got in there.

**What compiler, architecture, and operating system?**

- Compiler: clang from ndk 21.3.6528147
- Architecture (e.g. x86, x64) host: x64, target: x86_64-none-linux-android21
- Operating system: linux

**What jsoncons library version?**

 - [*] Latest release v0.162.2

**Comment by danielaparker** [comment]
Fixed on master, thanks. Could you check if you can compile master cleanly? I'm compiling using gcc and clang with
```
-Werror -Wall -Wextra -Wimplicit-fallthrough -Wcast-align -Wcast-qual -Wsign-compare -pedantic
```
and using PVS Studio locally, but those two warnings weren't picked up.

Thanks,
Daniel

**Comment by geiseri** [comment]
I just tested with master.  Something is up.  I see the length on those lines have the unused variable, but I have no idea why clang complains and gcc not.  Unless somehow that code is dead or something on gcc.

**Comment by danielaparker** [comment]
My apologies, I had neglected to push that branch to master, could you try again?

It's a good question, but there is no difference in code coverage between the gcc and clang builds.

**Comment by danielaparker** [comment]
Actually, that section of code is only used in android builds, so that explains that.
