### ISSUE TITLE
json no longer works with boost::optional

### ISSUE THREAD

**Issue by amerry** [danielaparker/jsoncons#31]
The following code fails to compiler under GCC:

    boost::optional<jsoncons::json> opt_json;
    opt_json = jsoncons::json(jsoncons::json::an_object);

with the error

    boost/optional/optional.hpp:346:8: error: no matching function for call to ‘jsoncons::basic_json<char, std::allocator<void> >::operator new(sizetype, void*)’
            new (m_storage.address()) internal_type(val) ;
    note: candidate is:
    jsoncons/json1.hpp:151:18: note: static void* jsoncons::basic_json<Char, Alloc>::operator new(std::size_t) [with Char = char; Alloc = std::allocator<void>; std::size_t = long unsigned int]
         static void* operator new(std::size_t) { return typename Alloc::template rebind<basic_json>::other().allocate(1); }
    jsoncons/json1.hpp:151:18: note:   candidate expects 1 argument, 2 provided

**Comment by danielaparker** [comment]
This should be fixed on master, I added a class-specific in-place new to the json class that is implemented in terms of the global version
