### ISSUE TITLE
Bson Type support: ObjectId, regex, Decimal128 etc 

### ISSUE THREAD

**Issue by swzhang888** [danielaparker/jsoncons#321]
**Describe the proposed feature**

**What other libraries (C++ or other) have this feature?**

**Include a code fragment with sample data that illustrates the use of this feature**

**Comment by swzhang888** [comment]
It is listed in bson_format, but not implemented.

**Comment by danielaparker** [comment]
Thanks for the suggestion, we'll look into it.

**Comment by danielaparker** [comment]
Support has been added for ObjectId, regex, and decimal128, currently on master. Examples added in [bson](https://github.com/danielaparker/jsoncons/blob/master/doc/ref/bson/bson.md).
