### ISSUE TITLE
How to work with byte string keys?

### ISSUE THREAD

**Issue by fferri** [danielaparker/jsoncons#334]
CBOR payloads coming from languages where strings and byte strings are the same thing (e.g. Lua) have all map keys of byte string type.

How to work with this data?

```
std::vector<uint8_t> data{161, 65, 97, 24, 42}; // {'a': 42}
json j = cbor::decode_cbor<json>(data.begin(), data.end());
std::cout << pretty_print(j) << std::endl; // prints { "YQ": 42 }
std::cout << "j['a']: " << j["a"] << std::endl; // throws key_not_found
```

**Comment by danielaparker** [comment]
jsoncons cbor decode converts non-string cbor keys into strings. By default it converts byte strings into base64url encoded strings.

You can use a filter to undo the conversion from the byte string to a base64url encoded string, like this:

```
#include <jsoncons/json.hpp>
#include <jsoncons_ext/cbor/cbor.hpp>

using jsoncons::json;
namespace cbor = jsoncons::cbor;

class lua_json_filter : public jsoncons::json_filter
{
	public:
		lua_json_filter(jsoncons::json_visitor& visitor)
			: jsoncons::json_filter(visitor)
		{
		}
	private:
		bool visit_key(const string_view_type& name, const jsoncons::ser_context& context,
			           std::error_code& ec) override
		{
			std::string s;
			jsoncons::decode_base64url(name.begin(), name.end(), s);
			return this->destination().key(s, context, ec);
		}
};

int main()
{
	std::vector<uint8_t> data{ 161, 65, 97, 24, 42 }; // {'a': 42}

	jsoncons::json_decoder<json> decoder;
	lua_json_filter filter(decoder);
	cbor::cbor_bytes_reader reader(data, filter);
	reader.read();

	json j = decoder.get_result();
	std::cout << pretty_print(j) << std::endl; // prints { "YQ": 42 }

	try
	{
		std::cout << "j['a']: " << j["a"] << std::endl; // throws key_not_found
	}
	catch (const std::exception& e)
	{
		std::cout << e.what() << "\n";
	}
}
```
Output:
```
{
    "a": 42
}
j['a']: 42
```

Future versions of jsoncons will likely provide ways for intercepting the CBOR byte string key event before the byte string is converted, there already is a `cbor_visitor2` interface that can receive these events, but it's not currently documented. We may also provide a `cbor_option`  option for suppressing the conversion, in which case you could continue to use the `decode_cbor` function. But for now this is what you can do.
