### ISSUE TITLE
Parsing of json string with bytes in the values causes Illegal codepoint (>= 0xd800 && <= 0xdfff) error

### ISSUE THREAD

**Issue by harold-kfuse** [danielaparker/jsoncons#340]
I have a json string, where one of the field  values can contain bytes. When the parser tries to parse it, it throws either an illegal codepoint error or overlong utf-8 sequence error.

**Comment by danielaparker** [comment]
JSON strings must contain valid unicode, otherwise it isn't JSON as per the specification. If you want to send binary data in JSON, you can encode it as base64 or base64url.

**Comment by harold-kfuse** [comment]
Got it. Thanks.
