### ISSUE TITLE
Cannot compile: error: ‘this’ pointer is null

### ISSUE THREAD

**Issue by g3n35i5** [danielaparker/jsoncons#344]
**Describe the bug**

Expected behavior: jsoncons compiles without errors.

Actual behavior: I'm getting the following error:

```
/tmp/jsoncons/tests/src/json_traits_macro_functional_tests.cpp: In static member function ‘static jsoncons::json_type_traits<Json, {anonymous}::ns::Employee_NCGN>::value_type jsoncons::json_type_traits<Json, {anonymous}::ns::Employee_NCGN>::as(const Json&)’:
/tmp/jsoncons/include/jsoncons/json_traits_macros.hpp:530:172: error: ‘this’ pointer is null [-Werror=nonnull]
  530 | #define JSONCONS_CTOR_GETTER_NAME_AS_LAST_2(Getter, Name) (ajson.contains(Name)) ? (ajson.at(Name)).template as<typename std::decay<decltype(((value_type*)nullptr)->Getter())>::type>() : typename std::decay<decltype(((value_type*)nullptr)->Getter())>::type()
      |                                                                                                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~
```

**Enumerate the steps to reproduce the bug**
```
cd /tmp
git clone https://github.com/danielaparker/jsoncons.git
cd jsoncons
git checkout v0.168.1
mkdir build && cd build
cmake ..
make
```

**What compiler, architecture, and operating system?**

- Compiler: g++
- Architecture: x64
- Operating system: Archlinux 

**What jsoncons library version?**

 - [x] Latest release 0.168.1

**Comment by danielaparker** [comment]
It appears that with the `-Werror=nonnull` compiler option, your compiler doesn't like to see
```
(value_type*)nullptr
```
inside a `decltype` specifier.  I added the  `-Werror=nonnull`  option for our g++ builds, but wasn't able to reproduce  this issue on any of our test environments.

While not being able to reproduce it, I changed `(value_type*)nullptr` to `std::declval<value_type*>()`, which may satisfy your compiler. Would you be able to repeat your test with the code on master, and report back with the results?

**Comment by g3n35i5** [comment]
@danielaparker works perfectly, thank you for that quick solution!
