### ISSUE TITLE
Support JSON Schema Draft 2020-12

### ISSUE THREAD

**Issue by oiwg** [danielaparker/jsoncons#354]
The current version of JSON Schema is Draft 2020-12, whereas jsoncons currently supports Draft 7, which is two versions behind.

It would be great if jsoncons supported Draft 2020-12!

It would of course be useful also to retain the Draft 7 support, to allow validation against schemas written to conform to either draft.

I haven't looked to see how great the changes are (and so how big a feature request this is!)

**Comment by danielaparker** [comment]
Drafts 2019-09 and 2020-12 are now largely supported on master, and will be included in an upcoming 0.174.0 release. See [make_json_schema](https://github.com/danielaparker/jsoncons/blob/master/doc/ref/jsonschema/make_json_schema.md) for examples using the new function `make_json_schema`.
