### ISSUE TITLE
Having problem with using `json::an_object`

### ISSUE THREAD

**Issue by noise2** [danielaparker/jsoncons#36]
I am trying to create a json object with a key-value like below

```CPP
json config;
json xfile_opt(json::an_object);
xfile_opt.add("input-file", config_file);
config["XFILE_COMPATIBLE"] = std::move(xfile_opt);
```
but it seems i cannot make it right.
And also i couldn't find any documentation addressing my problem.

How can i accomplish this?
Thanks in advance

**Comment by noise2** [comment]
Sry with the post.
For what it's worth, I have fixed the problem like below:
```CPP
json xfile_opt(json::an_object);
config["XFILE_COMPATIBLE"] = std::move(xfile_opt);
config["XFILE_COMPATIBLE"]["input-file"] = string(config_file);
```

**Comment by danielaparker** [comment]
You could also have written:

    json config; 
    json xfile_opt;  // defaults to empty object
    xfile_opt.set("input-file", config_file); // add is for arrays
    config["XFILE_COMPATIBLE"] = std::move(xfile_opt);

**Comment by danielaparker** [comment]
Or 

json config; 
json xfile_opt;  // defaults to empty object
xfile_opt["input-file"] = config_file; 
config["XFILE_COMPATIBLE"] = std::move(xfile_opt);
