### ISSUE TITLE
jsoncons-0.97.2: Compilation error with Visual Studio Professional 2015.

### ISSUE THREAD

**Issue by nobfi** [danielaparker/jsoncons#39]
Visual Studio 2013 and Visual Studio 2015 with Platform Toolset "Visual Studio 2013 (v120)" compile the code successfully.

The issue appears if to switch to Visual Studio 2015 (v140) Platform Toolset.

Here is reported error:

1>c:\test\jsoncons\parse_error_handler.hpp(188): error C2694: 'const char *jsoncons::json_parser_category_impl::name(void) const': overriding virtual function has less restrictive exception specification than base class virtual member function 'const char *std::error_category::name(void) noexcept const'
1>  c:\test\jsoncons\parse_error_handler.hpp(188): note: see declaration of 'jsoncons::json_parser_category_impl::name'
1>  c:\program files (x86)\microsoft visual studio 14.0\vc\include\system_error(167): note: see declaration of 'std::error_category::name'

**Comment by danielaparker** [comment]
I believe that was fixed on master, I'll add a patch to the 0.97.2 release when I get back from vacation on the 16th. Daniel

**Comment by henrypp** [comment]
in [json_parser.hpp](https://github.com/danielaparker/jsoncons/blob/master/src/jsoncons/json_parser.hpp) (line 104) error when compile in VS2015

`max_depth_ = std::numeric_limits<int>::max();`

"std::numeric_limits" class member "::max()" replaced by max() macros.

temporary (poor) solution:
`#undef max`

**Comment by danielaparker** [comment]
Thanks for reporting that, the issue with the macro expansion of max() has been fixed on master.
