### ISSUE TITLE
Temporary allocations from std::stable_sort even when using ojson

### ISSUE THREAD

**Issue by mxmlnkn** [danielaparker/jsoncons#391]
Thanks four providing this library!

I am trying to use it because of its memory-efficient streaming capabilities for very large JSON files.

However, the parsing performance seems slow to me. It takes ~60s for 2.5 GiB, so ~60 MB/s. That seems slow when hearing of (untested) multiple GB/s for simdjson. Even gzip decompression is many times faster (> 200 MB/s).

I tried to look a bit into performance bottlenecks and most of the time is spent almost equally much in `basic_json_parser::parse_some`, `basic_json_parser::parse_string`, and `jsoncons::unicode_traits::is_legal_utf8`.
Nothing I can do much about. I also did take a look with heaptrack and was surprised to see millions of temporary allocations from inside `std::stable_sort` from inside `jsoncons::json`.

Ok, so I found it sorts keys alphabetically. I find this a questionable default because it sacrifices performance  for something I don't need but it's fine as long as there is an alternative.
Next, I tried `jsoncons::ojson`, which is said to preserve the original order, thinking that this should get rid of the problematic `std::stable_sort`.

But `jsoncons::ojson` also calls `std::stable_sort` unexpectedly.

I tried to copy-paste the code of `order_preserving_json_object` and `order_preserving_policy` into a `patched_jsoncons` namespace and replaced the `std::stable_sort` inside `order_preserving_json_object::build_index` with `std::sort` and voila, the millions temporary allocations from `std::stable_sort` are gone. I'm still seeing millions of temporary allocations inside `build_index` for the `_index.reserve` call though. I'm not sure why it is flagged as `temporary`. The runtime improvements for a 2.5 GiB chrome trace JSON file are unfortunately not significant but those allocations still seem wasteful.

Now, I'm not 100% sure why `std::stable_sort` is used. It seems unnecessary to me. It has to be sorted somehow because `std::unique` is called at some point. (Sorting inside `build_index` and then calling `std::unique` outside assuming that `build_index` did sort seems hard to read to me. I think the sort and call to `std::unique` should be right next to each other.)

**What compiler, architecture, and operating system?**

- Compiler: Clang 14
- Architecture (e.g. x86, x64) x64
- Operating system: Ubuntu 22.04

**What jsoncons library version?**

 - [x] Latest release 0.168.7

**Comment by mxmlnkn** [comment]
For the approach of iterating in a streaming way over the large array and using an immutable one-shot parser for the nested objects, another benefit would be that those string_views that jsoncons already returns would have a more well-defined lifetime. Currently, I'm iterating over the SAX style values and after I have a nested object fully parsed, I can process it. However, my assumption is that the `string_view` lifetime ends as soon as `cursor::next` has been called. This means I have to do some unnecessary string copies because I have no control over the underlying I/O buffer into which the string views presumably point. Assuming that the JSON variant-like object returned by the one-shot parser would behave like a pure view into the input buffer, except maybe for integer values and such, those string copies could be avoided altogether. Whether it improves runtime is separate matter though.

**Comment by danielaparker** [comment]
Thanks for the comments. I'll have to think about this.

Incidentally, `ujson` wouldn't use `std::unordered_map`.

**Comment by mxmlnkn** [comment]
I also had to implement a stable sorting in my code and `std::stable_sort` was 3x slower than a simple `std::sort`. My solution was to add an `index` member and then sort it with that as a secondary sort key:

```c++
for ( size_t i = 0; i < values.size(); ++i ) {
    values[i].index = i;
}
std::sort( 
    values.begin(), values.end(),
    [] ( const auto& a, const auto& b ) {
        return std::make_tuple( a.sortKey, a.index ) < std::make_tuple( b.sortKey, b.index );
    }
);
```

This is ~50% slower than std::sort on only one key but still almost 2x faster than `std::stable_sort`.

**Comment by danielaparker** [comment]
Following @mxmlnkn's suggestion, `json_decoder` now uses code that performs stable sorting with an index and `std::sort`, code is on master. That should address the issue of temporary allocations from `std::stable_sort` during deserialization to `json` or `ojson` values.
