### ISSUE TITLE
wjson encodes true/false/null with quotes

### ISSUE THREAD

**Issue by cschreib-ibex** [danielaparker/jsoncons#403]
**Describe the bug**

Consider this simple test code, which just dumps a single boolean field with either `jsoncons::json` or `jsoncons::wjson`:
```c++
#include <fstream>
#include <jsoncons/json.hpp>

template <typename CharT> void test(const char *file) {
  using json = jsoncons::basic_json<CharT>;
  using stream = std::basic_ofstream<CharT>;

  json j;
  if constexpr (std::is_same_v<CharT, char>) {
    j["boolean"] = true;
  } else {
    j[L"boolean"] = true;
  }

  stream(file) << jsoncons::pretty_print(j);
}

int main() {
  test<char>("test_char.json");
  test<wchar_t>("test_wchar.json");
}
```

**What is the expected behavior?**

I expect both created files `test_char.json` and `test_wchar.json` to be identical and contain
```json
{
    "boolean": true
}
```

**What is the actual behavior?**

`test_char.json`:
```json
{
    "boolean": true
}
```

`test_wchar.json`:
```json
{
    "boolean": "true"
}
```

**Enumerate the steps to reproduce the bug**

 - Clone jsoncons.
 - Build the example code above (requires C++17).
 - Run the compiled executable.

**Include a small, self-contained example if possible**

See above.

**What compiler, architecture, and operating system?**

- Compiler: gcc 9.4.0 and MSVC 17.4
- Architecture (e.g. x86, x64) x64
- Operating system: Linux and Windows

**What jsoncons library version?**

 - [ ] Latest release 0.169.0
 - [ ] Other release ______
 - [x] master

**Comment by cschreib-ibex** [comment]
I traced back the issue to 
```c++
#define JSONCONS_QUOTE(Prefix, A) JSONCONS_EXPAND(Prefix ## #A)
```

The `#A` is what is adding the unwanted quotes; it should have been just `A`.

**Comment by cschreib-ibex** [comment]
Fix provided in https://github.com/danielaparker/jsoncons/pull/406

**Comment by danielaparker** [comment]
Thanks. We lack sufficient test cases for the wide character specialization, so the impact of changing the code for string constants wasn't caught. We'll try to address that going forward.
