### ISSUE TITLE
jsonpath query empty array's length expect [0] but get []

### ISSUE THREAD

**Issue by zongyanke** [danielaparker/jsoncons#416]
**Describe the bug**
string jsonStr = R"(
{
    "comments": []
}
)";
json data = json::parse(jsonStr.c_str());
json result = jsonpath::json_query(data, "$.comments.length");

result == [0]

result == []

**Comment by economicseries** [comment]
You're right, should be fixed on master, thanks for reporting this.

**Comment by danielaparker** [comment]
Fix is in 0.170.0
