### ISSUE TITLE
New CWE in master after code modifications

### ISSUE THREAD

**Issue by AndreyAlifanov** [danielaparker/jsoncons#422]
Hi!

PVS-Studio found another CWE in "fixed" code.

source.hpp, line 172
[CWE-191] V555: The expression '(length - len) > 0' will work as 'length != len'.

```
The analyzer detected a potential error in an expression of "A - B > 0" type. It is highly probable that the condition is wrong if the "A - B" subexpression has the unsigned type.

The "A - B > 0" condition holds in all the cases when 'A' is not equal to 'B'. It means that we may write the "A != B" expression instead of "A - B > 0". However, the programmer must have intended to implement quite a different thing
```

**Comment by danielaparker** [comment]
PVS-Studio has too much time on its hands, I'd rather not change (length - len) > 0 to 'length != len'.

**Comment by danielaparker** [comment]
Fixed on master. Noting that the original  '(length - len) > 0', equivalent to 'length != len', works correctively, even if not what the author (me) intended.
