### ISSUE TITLE
basic_byte_string::append incorrect

### ISSUE THREAD

**Issue by ergpudb** [danielaparker/jsoncons#425]
basic_byte_string::append calls this:

`data_.insert(s, s+count);`

However, std::vector::insert needs an insertion point specified as the first parameter, e.g.

`data_.insert(data_.end(), s, s + count);`

As is it fails to compile if append is called.

basic_byte_string::assign appears similarly incorrect.

v0.170.0 / gcc 11.3 / C++17 / Linux / x64

**Comment by danielaparker** [comment]
Thanks for reporting this, fixed on master.
