### ISSUE TITLE
gcc linker reports undefined reference

### ISSUE THREAD

**Issue by rychale** [danielaparker/jsoncons#45]
Hi,

Could you please suggest if the library really missing implementation of assign method, or this is some kind of mistake on my side?

```
(.text._ZN5tracy8tracer_tILNS_11log_level_tE1ELNS_12write_mode_tE83ELNS_11timestamp_tE87EEC2ERKSsRKN8jsoncons10basic_jsonIcSaIvEEE[_ZN5tracy8tracer_tILNS_11log_level_tE1ELNS_12write_mode_tE83ELNS_11timestamp_tE87EEC5ERKSsRKN8jsoncons10basic_jsonIcSaIvEEE]+0xeb): undefined reference to `jsoncons::json_type_traits<char, std::allocator<void>, tracy::log_level_t>::assign(jsoncons::basic_json<char, std::allocator<void> >&, tracy::log_level_t)'
```

Thanks in advance,
Alexey

**Comment by rychale** [comment]
The reason is that I was trying to set value of property using var of type enum class:
```
config["log-level"] = log_level;

where log_level is of:

enum class log_level_t: uint8_t
{
        TRACE = 0,
        DEBUG,
        INFO,
        WARNING,
        ERROR,
        CRITICAL
};
```
I'm not sure if this is an issue or not. If I understand correctly, the operator= was resolved at compile stage using some template, but at linkage stage corresponding implementation was not found...

**Comment by danielaparker** [comment]
The templated assign doesn't know about enum class log_level_t. If you wrote

config["log-level"] = static_cast<int>(log_level);

it should work. But your example raise a number of issues.

Given that it's an error, we'll see if we can make it a compile error rather than a link error.

Daniel

**Comment by danielaparker** [comment]
The templated assign doesn't know about enum class log_level_t. If you wrote

config["log-level"] = static_cast<int>(log_level);

it should work. But your example raise a number of issues.

Given that it's an error, we'll see if we can make it a compile error rather than a link error.

Daniel

**Comment by danielaparker** [comment]
The templated assign doesn't know about enum class log_level_t. If you wrote

config["log-level"] = (int)(log_level);

it should work. But your example raise a number of issues.

Given that it's an error, we'll see if we can make it a compile error rather than a link error.

Daniel

**Comment by danielaparker** [comment]
If you you sync with the latest master, you'll now get a compile error rather than a link error for an unsupported type.

Also, with the latest master, you should be able to assign it cast to a uint8_t (as an alternative to an int)

`config["log-level"] = static_cast<uint8_t>(log_level);`

and retrieve is as a uint8_t

`config["log-level"].as<uint8_t>();`

You could also write a custom json_type_traits instantiation for `enum class log_level_t` if you really wanted to write

config["log-level"] = log_level;

Daniel

**Comment by rychale** [comment]
Perfect!
