### ISSUE TITLE
Unable to load/store float

### ISSUE THREAD

**Issue by rychale** [danielaparker/jsoncons#46]
Hi,

It is possible to write something like:
```
_config.get("mean", .0).as<double>();
_config["mean"] = 2.2; // double
```
But it looks like there is no similar functions accepting *float*:
```
_config.get("mean", .0).as<float>();
_config["mean"] = static_cast<float>(2.2);

Regards,
Alexey

**Comment by danielaparker** [comment]
There is now:

	jsoncons::json val;
	val["mean"] = static_cast<float>(10.0);
	float x = val["mean"].as<float>();
