### ISSUE TITLE
Retrieve the parent of an object located by jsonpath

### ISSUE THREAD

**Issue by PragmaTwice** [danielaparker/jsoncons#467]
**Describe the proposed feature**
Hi @danielaparker, firstly I want to thank you for such an amazing JSON library with rich features.

Our [Kvrocks](https://kvrocks.apache.org/) community is utilizing this library to implement JSON-related features like [RedisJSON](https://github.com/RedisJSON/RedisJSON)-compatibility. And my experience with jsoncons is really awesome.

For implementing some commands like [`JSON.DEL`](https://redis.io/commands/json.del/), we need to firstly use the jsonpath extension to locate an object in a JSON document, and then we need to delete the object if it is inside an array or object. (For example, given a JSON `{"a":1, "b":2}`, `JSON.DEL <key> $.a` results in `{"b":2}`.)

But it seems to be hard to delete since we cannot retrieve the parent object (or array) and then use some methods like `basic_json::erase`. (For example, given a JSON `{"a":1, "b":2}` and jsonpath `$.a`, we can only get the object `1`, but instead we need to retrieve its parent object and then delete the key `a`.)

So I am wondering if there is any chance that such an ability can be provided in jsoncons, or if there is an cheap workaround which can solve this problem.

Related issue in Kvrocks: https://github.com/apache/kvrocks/issues/1813

**What other libraries (C++ or other) have this feature?**
Maybe [RedisJSON](https://github.com/RedisJSON/RedisJSON)? Since it implements `JSON.DEL`.

**Comment by danielaparker** [comment]
jsoncons jsonpath supports a parent selector extension, `^`, borrowed from [jsonpath-plus](https://www.npmjs.com/package/jsonpath-plus), that should do what you want. 

```
#include <jsoncons/json.hpp>
#include <jsoncons_ext/jsonpath/jsonpath.hpp>

using namespace jsoncons;

std::string input = R"(
[{"a":1, "b":2},{"c":1,"d":2}]
)";

int main()
{
    json doc = json::parse(input);

    auto callback = [](const std::string& path, json& value)
    {
        if (value.is_object())
        {
            auto it = value.find("a");
            value.erase(it);
        }
    };
    jsonpath::json_replace(doc, "$..a^", callback);

    std::cout << doc << "\n";
}
```
Output:

```
[{"b":2},{"c":1,"d":2}]
```

**Comment by PragmaTwice** [comment]
I see. Thank you for your quick answer!

**Comment by PragmaTwice** [comment]
The parent selector is awesome, but we still face some problem to retrieve the key name.

For the example in https://github.com/danielaparker/jsoncons/issues/467#issuecomment-1783967621, it seems to be hard to retrieve the field name `a` in the parent object, since the path can be varied (e.g. `$.a`, `$["a"]`, `$[1]`, `$..a[*]`).

May I ask if you have some idea about this? Thanks.

**Comment by danielaparker** [comment]
Oh, I see. In that case I think the strategy would be to collect the normalized paths for all nodes associated with the path, and then delete them one by one. We don't currently have a utility function for deleting the node corresponding to a normalized path, but could add one in the next release.

**Comment by PragmaTwice** [comment]
> We don't currently have a utility function for deleting the node corresponding to a normalized path, but could add one in the next release.
Thank you. It will be highly appreciated.

**Comment by danielaparker** [comment]
Release 0.172.0 supports removing nodes that match on a JSONPath expression, e.g.

```cpp
#include <jsoncons/json.hpp>
#include <jsoncons_ext/jsonpath/jsonpath.hpp>
#include <fstream>
#include <cassert>

using jsoncons::json; 
namespace jsonpath = jsoncons::jsonpath;

int main()
{
    std::string input = R"(
    {
        "books":
        [
            {
                "category": "fiction",
                "title" : "A Wild Sheep Chase",
                "author" : "Haruki Murakami",
                "price" : 22.72
            },
            {
                "category": "fiction",
                "title" : "The Night Watch",
                "author" : "Sergei Lukyanenko",
                "price" : 23.58
            },
            {
                "category": "fiction",
                "title" : "The Comedians",
                "author" : "Graham Greene",
                "price" : 21.99
            },
            {
                "category": "memoir",
                "title" : "The Night Watch",
                "author" : "Phillips, David Atlee"
            }
        ]
    }
    )";
    json doc = json::parse(input);

    std::size_t n = jsoncons::jsonpath::remove(doc, "$.books[1,1,3,3,0,0]");

    assert(n == 3);

    std::cout << jsoncons::pretty_print(doc) << "\n\n";
```

Output:

```
{
    "books": [
        {
            "author": "Phillips, David Atlee",
            "category": "memoir",
            "title": "The Night Watch"
        }
    ]
}
```

**Comment by PragmaTwice** [comment]
Thank you!
