### ISSUE TITLE
endless loop in jmespath::search

### ISSUE THREAD

**Issue by MonkeybreadSoftware** [danielaparker/jsoncons#469]
if the expression for jmespath::search contains an extra CR on the end, we get an endless loop.

It looks like advance_past_space_character detects we are >= end and thus sets ec to an error.
But ec is not checked.

So after calling `advance_past_space_character(ec);`, we may need to add `if (ec) {return jmespath_expression();}` to exit the loop.

**Comment by danielaparker** [comment]
Interesting edge case,  I changed `advance_past_space_character` to allow it, since we already allow a CR followed by a space character.
