### ISSUE TITLE
Performance issue due to memory allocations

### ISSUE THREAD

**Issue by cperthuis** [danielaparker/jsoncons#48]
Hi,

While creating an average json tree, I am finding that a big percentage of the time is spent doing memory allocations and deallocations :
malloc 36%
free 21%

It's on a good desktop PC on windows 7.
In that example, jsoncons::basic_json constructor takes 90% of the CPU, so those measurements are not coming from anywhere else.

Function Name	Inclusive Samples	Exclusive Samples	Inclusive Samples %	Exclusive Samples %
jsoncons::basic_json<char,std::allocator<void> >::basic_json<char,std::allocator<void> >	1,800	101	90.73	5.09

The time spent freeing is concerning, there's probably a lot of extra work being done?
Also, I am wondering if it wouldn't be beneficial to provide a way to pass its own allocator or to do some kind of pooling.

Any thoughts?
I am generating about 5MB of json in about 40s at the moment, I think it's a bit too slow. I would expect a second or so.

Here's the sample code I am using:
```c++
json * createInstance(const json &type, bool isArrayElement = false)
{
	json *instance = NULL;
	
	std::string typeDef = type.as_string();
	
	if (type.is<json::object>())
	{
		std::string typeName0 = type["type"].as_string();

		const json *resolvedType = &type;
		bool isArray = false;
		int arrayDefaultSize = 1;

		if (type.has_member("type"))
		{
			if (isArrayElement == false && type.has_member("array"))
			{
				isArray = type["array"].as_bool();
			}
			if (type.has_member("array_default_size"))
			{
				arrayDefaultSize = type["array_default_size"].as_int();
			}
			
			std::string typeName = type["type"].as_string();
			TypesMap::iterator it = DataBlockImpl::_types.find(typeName);
			if (it != DataBlockImpl::_types.end())
			{
				resolvedType = it->second;
			}
		}
		
		if (isArray)
		{
			//create an object with "name", "type" and "array"
			instance = new json;
			for (auto it = type.begin_members(); it != type.end_members(); ++it)
			{
				(*instance)[it->name()] = std::move(*createInstance(it->value()));
			}
			//add a json array to the object
			json *elements = new json(json::an_array);
			for (int i = 0; i < arrayDefaultSize+1; i++)
			{
				json *element = createInstance(type,true);
				element->remove_member(std::string("array"));
				element->remove_member(std::string("array_default_size"));

				//name all the elements with their position in the array
				char buffer[64];
				sprintf(buffer, "%i", i-1); //item -1 is the template used to resize
				(*element)["name"] = std::string(buffer);

				elements->add(std::move(*element));
			}
			(*instance)["elements"] = std::move(*elements);
		}
		else
		{
			instance = new json;
			for (auto it = resolvedType->begin_members(); it != resolvedType->end_members(); ++it)
			{
				(*instance)[it->name()] = std::move(*createInstance(it->value()));
			}
			if (resolvedType != &type)
			{
				//we have resolved a type, we need to replace the struct type name by the name of the proxy
				(*instance)["struct"] = true;
				(*instance)["type"] = (*instance)["name"].as_string();
				(*instance)["name"] = type["name"].as_string();
				if (type.has_member("tags"))
					(*instance)["tags"] = type["tags"];
			}
		}
	}
	else if (type.is<json::array>())
	{
		instance = new json(json::an_array);
		for (auto it = type.begin_elements(); it != type.end_elements(); ++it)
		{
			instance->add(std::move(*createInstance(*it)));
		}
	}
	else
	{
		instance = new json(type);
	}
	return instance;
}
```

**Comment by danielaparker** [comment]
Hi cperthuis ,

Thanks for the feedback.

One question: what compiler are you using? Also, is your output mostly text, or integers, or floating point numbers?

An initial comment: I don't recommend using 'new json', every 'new' has to have a corresponding 'delete', or you'll have memory leaks. The jsoncons library has been designed to take advantage of copy elision and move semantics to avoid unnecessary copies. 

So I recommend

json createInstance(const json &type, bool isArrayElement = false)
{
    json instance = json::null;

and

        if (isArray)
        {
            //create an object with "name", "type" and "array"
            instance = json::object;
            for (auto it = type.begin_members(); it != type.end_members(); ++it)
            {
                // Copy elision works here with createInstance, you don't benefit from std::move
                instance[it->name()] = createInstance(it->value()); . 
            }
and
           for (int i = 0; i < arrayDefaultSize+1; i++)
            {
                json element = createInstance(type,true);
                element.remove_member(std::string("array"));
                element.remove_member(std::string("array_default_size"));

                //name all the elements with their position in the array
                char buffer[64];
                sprintf(buffer, "%i", i-1); //item -1 is the template used to resize
                element["name"] = std::string(buffer);

                elements.add(std::move(element));
            }
            // The contents of elements get moved into instance["elements"] 
            instance["elements"] = std::move(elements);

and so on.

Regarding performance in general, I'm currently following a program to benchmark jsoncons against other libraries, and address deficiencies. Enhancements will be added to master as they become available.

Daniel

**Comment by cperthuis** [comment]
Great, I'll try those suggestions and report the results.
I am using Visual Studio 2015 64 bits.

**Comment by danielaparker** [comment]
Also, if you know the approximate number of elements or members you'll be adding to a json array or object, you can reduce the number of memory allocations by using the reserve method, e.g.

           json elements = json::array();
           elements.reserve(30);

Daniel

**Comment by cperthuis** [comment]
Great, I was looking for something like this. That would work for me, in general I always know everything when I am writing out a json object. 
I might have missed it in the samples, if it's not there, it would be nice if it was on the simple usage case example.

**Comment by cperthuis** [comment]
It improved the speed a bit, it's about 2 times as fast now, my 5MB save takes about 25s.
I have another bottleneck elsewhere now, which I'll probably solved differently.
I don't understand the extra copy in resize_array. I don't know if it's really needed, but it's adding 8% in my case.

```c++
template<typename Char, typename Alloc>
template<typename T>
void basic_json<Char, Alloc>::resize_array(size_t n, T val)
{
    basic_json<Char, Alloc> j;
    j = val;  //hotspot 8%
    switch (type_)
    {
    case value_type::array_t:
        value_.array_->resize(n, j); //hotspot 42% (calling constructor)
        break;
    }
}
```

I am resizing some json arrays by passing a json object as template parameter which has a similar hierarchy than what I'll ultimately fill my array with. Then I change some values here and there in that array. But I often will override the entire sub-object later, so I should really either resize my arrays with an empty json object, or just add my objects one by one without resizing the array with a dummy template object.

**Comment by danielaparker** [comment]
Thanks for noticing the redundant assignment in resize! I vaguely recall that from when debugging something. I've removed it in master.

I'm currently investigating the performance of serialization.

Daniel

**Comment by danielaparker** [comment]
If you take the latest code on master, you should see an improvement in write times, with code like

    json root;
    std::ofstream os(output_filename,std::ofstream::binary);

    os << root;

or

    os << pretty_print(root);

Daniel
