### ISSUE TITLE
The spaces_around_comma options doesn't work

### ISSUE THREAD

**Issue by YintongMa** [danielaparker/jsoncons#490]
I want print out the json array by adding a space after comma. But the spaces_around_comma option doesn't work in the following simple case.
`   
Code:

    jsoncons::json j_arr(jsoncons::json_array_arg, {"1", "2", 3, 4});
    jsoncons::json_options options;
    options.spaces_around_comma(jsoncons::spaces_option::space_after);
    std::string buffer;
    jsoncons::encode_json(j_arr, buffer, options);
    std::cout << buffer << std::endl;
`

The output is:
`["1","2",3,4]`

What I want is:
`["1", "2", 3, 4]`

**Comment by danielaparker** [comment]
Thanks for reporting this, I'll have a look.

**Comment by danielaparker** [comment]
It's been a while since I've looked at the json options! I had to re-familiarize myself with them.

The function `encode_json` with `indenting::no_indent` as the (default) fourth argument doesn't perform any prettify operations on the output json, it produces compact single-line output only, and ignores prettify options. To prettify the output, with spaces and so on, you need to call it with `indenting::indent`.

If your input JSON looked like
```json
[["1", "2"], [3, 4]]
```

you could use
```c++
   jsoncons::json_options options;
   options.spaces_around_comma(jsoncons::spaces_option::space_after);
   options.array_array_line_splits(jsoncons::line_split_kind::same_line);
   std::string buffer;
   jsoncons::encode_json(j_arr, buffer, options, jsoncons::indenting::indent);
   std::cout << buffer << std::endl;
```
and your output would be
```
[
    ["1", "2"],
    [3, 4]
]
```
It seems we don't currently have an option for prettifying the output but leaving it on a single line.

**Comment by YintongMa** [comment]
Thank you so much for the help! I think I'll iterate the values and format the output by myself then

**Comment by danielaparker** [comment]
This is now supported on the branch `master`, with the new option `line_splits`,

```cpp
    jsoncons::json j_arr = jsoncons::json::parse(R"(["1", "2", 3, 4])");
    jsoncons::json_options options;
    options.spaces_around_comma(jsoncons::spaces_option::space_after) // default when using pretty printing 
           .line_splits(jsoncons::line_split_kind::same_line);
    std::string buffer;
    jsoncons::encode_json(j_arr, buffer, options, jsoncons::indenting::indent);
    std::cout << buffer << std::endl;
```
Output:
```json
["1", "2", 3, 4]
```
The `line_splits` value now becomes the default value for `object_object_line_splits`, `object_array_line_splits`, `array_object_line_splits`, and `array_array_line_splits`, so, for example,

```cpp
    jsoncons::json j_arr = jsoncons::json::parse(R"(["1", "2", [3, 4]])");
    jsoncons::json_options options;
    options.line_splits(jsoncons::line_split_kind::same_line);
    std::string buffer;
    jsoncons::encode_json(j_arr, buffer, options, jsoncons::indenting::indent);
    std::cout << buffer << std::endl;
```
produces

```json
["1", "2", [3, 4]]
```

**Comment by YintongMa** [comment]
That's awsome! Appreciated it!
