### ISSUE TITLE
Set json value for nonexistent path in jsonpath

### ISSUE THREAD

**Issue by PragmaTwice** [danielaparker/jsoncons#496]
First and foremost, I want to express my gratitude.
Apache Kvrocks consistently utilizes jsoncons to offer support for JSON data structures to users. We find the development experience with jsoncons outstanding!
Many thanks to the authors for your hard work.

**Describe the proposed feature**
As implemented in Redis, we want to set json values for some user-provided nonexistent jsonpath, e.g.
- we have a json value `{"a": 1}`
- user provides a json path `$.b` and value `2`
- we should return to user the json `{"a": 1, "b": 2}` with newly-added field `b`

Seems that in the jsonpointer extension in jsoncons, there's some utility to add value to a nonexistent location, i.e. `create_if_missing` parameter in https://github.com/danielaparker/jsoncons/blob/master/doc/ref/jsonpointer/replace.md, 
but this feature seems missing in jsonpath.

**What other libraries (C++ or other) have this feature?**
[RedisJSON](https://github.com/RedisJSON/RedisJSON) supports this feature.

**Include a code fragment with sample data that illustrates the use of this feature**

Maybe just like jsonpath, we can also add a parameter like  `create_if_missing`, e.g.
```cpp
jsonpath::json_replace(path, []{ ... }, /* create_if_missing = */ true);
```

**Comment by danielaparker** [comment]
Thanks for the suggestion. We'll look into it, but it could take awhile to get to it.

**Comment by danielaparker** [comment]
Suppose your data is

```json
{
    "books": [
        {
            "author": "Nigel Rees",
            "price": 8.95,
            "title": "Sayings of the Century"
        },
        {
            "author": "Evelyn Waugh",
            "price": 11.2,
            "title": "Sword of Honour"
        }
    ]
}
```
and your operation is
```
jsonpath::assign(doc, "$.books[2].price", json{ 13.5 });
```
What would you expect the result to be?

This?

{
    "books": [
        {
            "author": "Nigel Rees",
            "price": 8.95,
            "title": "Sayings of the Century"
        },
        {
            "author": "Evelyn Waugh",
            "price": 11.2,
            "title": "Sword of Honour"
        },
        {
            "price": 13.5,
        }
    ]
}
```
Or an error? (like the jsonpointer functions)

What would RedisJson do?

**Comment by PragmaTwice** [comment]
Hi @danielaparker , thank you for your reply and following up.

I've checked the behavior in RedisJSON.

Basically, I think the only allowed nonexistent path is a nonexistent object key on an existent path, e.g. 
- `$.a` exists, then we can set `$.a.b`
- if `$.a` exists but `$.a.b` doesn't, we cannot set `$.a.b.c`
- we cannot set to a nonexistent array subscript

**Comment by danielaparker** [comment]
Okay, I've add the following free function to the jsonpath library,

    template<class Json>
    std::pair<Json*,bool> assign(Json& root_value, const basic_json_location<Json::char_type>& location, 
        Json&& value, bool create_if_missing = false);   (since 0.174.0)
Attempts to assign a value at the specified location. If `create_if_missing` is true, creates key-object pairs 
when an object key is missing. Returns a `std::pair<Json*,bool>`, the bool component is `true`
if the assignment took place and `false` if not, if `true`, the `Json*` component points to the value that
was assigned or inserted. 

It can be used as follows,

```cpp
    std::string json_string = R"(
{"books": [ 
    { "category": "reference",
      "author": "Nigel Rees",
      "title": "Sayings of the Century",
      "price": 8.95
    },
    { "category": "fiction",
      "author": "Evelyn Waugh",
      "title": "Sword of Honour"
    }
  ] 
}
    )";

    json doc = json::parse(json_string);

    jsonpath::json_location loc = jsonpath::json_location::parse("$.books[1].price");

    auto result1 = jsonpath::assign(doc, loc, json{ 13.5 }, false);
    assert(!result1.second);  // assignment fails

    auto result2 = jsonpath::assign(doc, loc, json{ 13.5 }, true);
    assert(result2.second);  // assignment succeeds

    std::cout << prettyPrint(doc) << "\n";
```
Output:
```json
{
    "books": [
        {
            "author": "Nigel Rees",
            "category": "reference",
            "price": 8.95,
            "title": "Sayings of the Century"
        },
        {
            "author": "Evelyn Waugh",
            "category": "fiction",
            "price": 13.5,
            "title": "Sword of Honour"
        }
    ]
}
```

**Comment by PragmaTwice** [comment]
Great! Thank you for your quick action!

**Comment by danielaparker** [comment]
Renamed to be consistent with `jsonpointer::replace`, see [jsonpath::replace](https://github.com/danielaparker/jsoncons/blob/master/doc/ref/jsonpath/replace.md)
