### ISSUE TITLE
Arm-none-eabi-gcc compiler gives error

### ISSUE THREAD

**Issue by SlowTypist** [danielaparker/jsoncons#508]
https://github.com/danielaparker/jsoncons/blob/b883d895ec25ed21b084cd4c78ae3c2725737f68/include/jsoncons/detail/optional.hpp#L261

Throws error:
error: third operand to the conditional operator is of type 'void', but the second operand is neither a throw-expression nor of type 'void'
  261 |                        ? get()

**Comment by danielaparker** [comment]
@SlowTypist Could you check if that compiles now on master?

Thanks,
Daniel

**Comment by SlowTypist** [comment]
> @SlowTypist Could you check if that compiles now on master?
> 
> Thanks, Daniel

LGTM, compiles now.
