### ISSUE TITLE
jsoncons shouldnt use int128 and float 128 when cuda is activated

### ISSUE THREAD

**Issue by calebxyz** [danielaparker/jsoncons#518]
**jsoncons shouldnt use int128 and float 128 when cuda is activated**

**compile jsoncons includes with .cu file or -x cuda**

**What compiler, architecture, and operating system?**

- Compiler: clang 18.1.6
- Architecture (e.g. x86, x64) cuda
- Operating system: ubuntu 22

**What jsoncons library version?**

 - [ ] Latest release 0.174.0

**Comment by danielaparker** [comment]
This should be fixed on master
