### ISSUE TITLE
error: need ‘typename’ before ...

### ISSUE THREAD

**Issue by massimomorara** [danielaparker/jsoncons#53]
Hi.
First of all, sorry for my bad english.
Second, I'm trying to compile your test suite but I get some errors.
The first seems due to the fact that my compiler (g++ 4.9.2 on a Debian Jessie amd64) requires the keyword "typename" before (jsoncons/json_structures.hpp:829)

`std::vector<value_type,allocator_type>::iterator it;`

Changin in 

`typename std::vector<value_type,allocator_type>::iterator it`

the compilation continue.

I transcribe, below, the output

--- begin output ---
[  3%] Building CXX object CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/json_construction_tests.cpp.o
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp:19:0,
                 from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/json_construction_tests.cpp:10:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json_structures.hpp: In member function ‘jsoncons::json_object<StringT, JsonT, Alloc>::iterator jsoncons::json_object<StringT, JsonT, Alloc>::set(jsoncons::json_object<StringT, JsonT, Alloc>::iterator, jsoncons::json_object<StringT, JsonT, Alloc>::string_type&&, JsonT&&)’:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json_structures.hpp:829:9: error: need ‘typename’ before ‘std::vector<jsoncons::name_value_pair<StringT, JsonT>, Alloc>::iterator’ because ‘std::vector<jsoncons::name_value_pair<StringT, JsonT>, Alloc>’ is a dependent scope
         std::vector<value_type,allocator_type>::iterator it;
         ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json_structures.hpp:829:58: error: expected ‘;’ before ‘it’
         std::vector<value_type,allocator_type>::iterator it;
                                                          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json_structures.hpp:832:13: error: ‘it’ was not declared in this scope
             it = std::lower_bound(hint.get(),members_.end(),name.data() ,member_lt_string<value_type,char_type>(name.length()));
             ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json_structures.hpp:836:13: error: ‘it’ was not declared in this scope
             it = std::lower_bound(members_.begin(),members_.end(),name.data() ,member_lt_string<value_type,char_type>(name.length()));
             ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json_structures.hpp:839:13: error: ‘it’ was not declared in this scope
         if (it == members_.end())
             ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json_structures.hpp:852:25: error: ‘it’ was not declared in this scope
         return iterator(it);
                         ^
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/json_construction_tests.cpp:10:0:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp: At global scope:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp:2736:25: error: declaration of ‘typedef jsoncons::basic_json<StringT, Alloc>::member_type jsoncons::basic_json<StringT, Alloc>::name_value_pair’ [-fpermissive]
     typedef member_type name_value_pair;
                         ^
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp:19:0,
                 from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/json_construction_tests.cpp:10:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json_structures.hpp:260:7: error: changes meaning of ‘name_value_pair’ from ‘class jsoncons::name_value_pair<StringT, jsoncons::basic_json<StringT, Alloc> >’ [-fpermissive]
 class name_value_pair
       ^
CMakeFiles/jsoncons_tests.dir/build.make:54: set di istruzioni per l'obiettivo "CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/json_construction_tests.cpp.o" non riuscito
make[2]: *** [CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/json_construction_tests.cpp.o] Errore 1
CMakeFiles/Makefile2:60: set di istruzioni per l'obiettivo "CMakeFiles/jsoncons_tests.dir/all" non riuscito
make[1]: *** [CMakeFiles/jsoncons_tests.dir/all] Errore 2
Makefile:76: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2
--- end output ---

**Comment by danielaparker** [comment]
Fixed

**Comment by massimomorara** [comment]
I confirm: fixed.
But, sorry: the g++ "9.4.2" was a typo of mine; my g++ is in version "4.9.2" (obviously)
