### ISSUE TITLE
Allow jmespath to be const qualified

### ISSUE THREAD

**Issue by nnathan** [danielaparker/jsoncons#530]
I would like to see the ability to allow const reference to a `jmespath_expression`, to ensure that it's read-only and allow the compiler to do any optimisations.

It appears that the `jmespath_expression::evaluate()` are not const methods and therefore preventing making a useful const reference.

I was a bit concerned that the `jmespath_expression` was mutating itself each evaluate, but after applying a `const` to the `evaluate()` methods, and then made the `jmespath_expression` a const reference, it didn't seem to have any issue.

**Comment by danielaparker** [comment]
You're right, `evaluate()` should be const, it never mutates the state of the `jmespath_expression`. Fixed on master.

**Comment by nnathan** [comment]
Much appreciated, thanks for the quick turn around. I'll leave it up to you if you want to close the request.
