### ISSUE TITLE
Could we get a release of jsoncons

### ISSUE THREAD

**Issue by nnathan** [danielaparker/jsoncons#534]
Hi,

I asked a few weeks ago to add const to jmespath_expression::evaluate and you quickly turned around with the feature which I'm very appreciative of.

We're using conan to fetch jsoncons, would it be possible to do a version bump so I can use this feature, as conan requires a package version and can't fetch the latest from master.

Thanks!

**Comment by danielaparker** [comment]
Soon :-) There are two other minor issues I'm currently thinking about that I'd like to go in too.

**Comment by danielaparker** [comment]
It's in release 0.177.0
