### ISSUE TITLE
Should jsoncons drop support for wjson and wojson?

### ISSUE THREAD

**Issue by danielaparker** [danielaparker/jsoncons#536]
Currently, jsoncons supports wide character instantiations of the template class `basic_json` with `wchar_t`, in particular, `wjson` and `wojson`. At the time when we started jsoncons, back in 2013, it seemed like a good idea. However, judging from the issues and discussions, it doesn't seem like many users see any value in this feature. Our most popular extension by far, jsonschema, doesn't currently support wide characters, and nobody has complained.

We're considering removing wide character support from `basic_json` and related classes. Support for wide characters complicates a lot of things. Removing this support also makes it easier to improve the efficiency of checking unicode, following patterns established by the really fast JSON parsers.

This change would have no impact for current users of `json` and `ojson`, or of `basic_json` with custom template parameters.

Feedback welcome.

**Comment by AndreyAlifanov** [comment]
Hello!
We use this functionality. So, please don't remove it.

**Comment by danielaparker** [comment]
@AndreyAlifanov , Okay, we'll leave this the way it is.
