### ISSUE TITLE
error: declaration of ‘typedef ...

### ISSUE THREAD

**Issue by massimomorara** [danielaparker/jsoncons#54]
Second error compiling the test suite.
There is a problematic `typedef` definition in jsoncons/json.hpp:2736

`typedef member_type name_value_pair`

I don't know if it's the correct solution but, deleting the line, the compilation continue.

I transcrive, below, the output

--- begin output ---
[  3%] Building CXX object CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/json_construction_tests.cpp.o
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/json_construction_tests.cpp:10:0:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp:2736:25: error: declaration of ‘typedef jsoncons::basic_json<StringT, Alloc>::member_type jsoncons::basic_json<StringT, Alloc>::name_value_pair’ [-fpermissive]
     typedef member_type name_value_pair;
                         ^
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp:19:0,
                 from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/json_construction_tests.cpp:10:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json_structures.hpp:260:7: error: changes meaning of ‘name_value_pair’ from ‘class jsoncons::name_value_pair<StringT, jsoncons::basic_json<StringT, Alloc> >’ [-fpermissive]
 class name_value_pair
       ^
CMakeFiles/jsoncons_tests.dir/build.make:54: set di istruzioni per l'obiettivo "CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/json_construction_tests.cpp.o" non riuscito
make[2]: *** [CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/json_construction_tests.cpp.o] Errore 1
CMakeFiles/Makefile2:60: set di istruzioni per l'obiettivo "CMakeFiles/jsoncons_tests.dir/all" non riuscito
make[1]: *** [CMakeFiles/jsoncons_tests.dir/all] Errore 2
Makefile:76: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2
--- end output ---

**Comment by danielaparker** [comment]
typedef removed (name has been deprecated a long time)

**Comment by massimomorara** [comment]
I confirm: fixed
