### ISSUE TITLE
Add a registry that can be used with JSON Schema validation

### ISSUE THREAD

**Issue by michaelmior** [danielaparker/jsoncons#549]
**Describe the proposed feature**

Many JSON Schema validators support the ability to register external schemas based on their ID so they can be resolved at validation time.
The idea is that you pass in the schema and the ID and it would be saved into a local registry so that any future schemas which reference that schema by ID will discover it without needing resolution.

**What other libraries (C++ or other) have this feature?**

[Blaze]https://github.com/sourcemeta/blaze) is the only C++ library I am aware of.

**Include a code fragment with sample data that illustrates the use of this feature**

This is something that should be possible by implementing a resolver which has a method to add a schema instance.

**Comment by michaelmior** [comment]
@danielaparker Could you clarify how the existing resolver could be used to supply just `name-defs.json` as in your example above? It sounds like it would then be possible to have all the subsequent URIs you listed be resolved according to that single document.

That is, can I provide the schema for `http://localhost:1234/draft2020-12/name-defs.json` in the resolver and then have the following all be automatically resolved?

```
'http://localhost:1234/draft2020-12/name-defs.json'
'http://localhost:1234/draft2020-12/name-defs.json#/$defs/orNull'
'http://localhost:1234/draft2020-12/name-defs.json#/$defs/orNull/anyOf/0'
```

**Comment by michaelmior** [comment]
Could you give an example of how that would work? It seems like this would already resolve the issue here. (Although perhaps there could end up being a somewhat nicer API for what I'm trying to achieve.)

**Comment by danielaparker** [comment]
[Using a URIResolver to resolve references to schemas defined in external files](https://github.com/danielaparker/jsoncons/blob/master/doc/ref/jsonschema/jsonschema.md#using-a-uriresolver-to-resolve-references-to-schemas-defined-in-external-files)
