### ISSUE TITLE
error: declaration of ‘std::shared_ptr...

### ISSUE THREAD

**Issue by massimomorara** [danielaparker/jsoncons#56]
Fourth (and last, at the moment) error compiling the test suite.
My compiler give me an error in line 190 of `jsoncons_ext/jsonpath/jsonpath_filter.hpp`; declaration of `std::shared_ptr<term<JsonT>> term()`, `class token`

`std::shared_ptr<term<JsonT>> term()`
`    {`
`        return term_;`
`    }`

If I understand correctly, there is a collision of `term<>` class with `term()` member function.

Same problem with the declaration of `std::shared_ptr<term<JsonT>> term(token_stream<JsonT>& ts)`, lines 813-898.

I don't know which name change.

I transcribe, below, the output

--- begin output ---
[  3%] Building CXX object CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/jsonpath_filter_tests.cpp.o
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:17:0,
                 from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/jsonpath_filter_tests.cpp:15:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/jsonpath_filter.hpp:190:5: error: declaration of ‘std::shared_ptr<jsoncons::jsonpath::term<JsonT> > jsoncons::jsonpath::token<JsonT>::term()’ [-fpermissive]
     }
     ^
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:17:0,
                 from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/jsonpath_filter_tests.cpp:15:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/jsonpath_filter.hpp:64:7: error: changes meaning of ‘term’ from ‘class jsoncons::jsonpath::term<JsonT>’ [-fpermissive]
 class term
       ^
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:17:0,
                 from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/jsonpath_filter_tests.cpp:15:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/jsonpath_filter.hpp:898:5: error: declaration of ‘std::shared_ptr<jsoncons::jsonpath::term<JsonT> > jsoncons::jsonpath::jsonpath_filter_parser<JsonT>::term(jsoncons::jsonpath::token_stream<JsonT>&)’ [-fpermissive]
     }
     ^
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:17:0,
                 from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/jsonpath_filter_tests.cpp:15:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/jsonpath_filter.hpp:64:7: error: changes meaning of ‘term’ from ‘class jsoncons::jsonpath::term<JsonT>’ [-fpermissive]
 class term
       ^
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/jsonpath_filter_tests.cpp:15:0:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp: In instantiation of ‘JsonT jsoncons::jsonpath::json_query(const JsonT&, const typename JsonT::char_type*) [with JsonT = jsoncons::basic_json<std::basic_string<char>, std::allocator<char> >; typename JsonT::char_type = char]’:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/jsonpath_filter_tests.cpp:102:58:   required from here
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:87:90: error: no matching function for call to ‘json_query(const jsoncons::basic_json<std::basic_string<char>, std::allocator<char> >&, const char_type*&, std::size_t)’
     return json_query(root,path,std::char_traits<typename JsonT::char_type>::length(path));
                                                                                          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:87:90: note: candidates are:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:79:7: note: template<class JsonT> JsonT jsoncons::jsonpath::json_query(const JsonT&, const typename JsonT::string_type&)
 JsonT json_query(const JsonT& root, const typename JsonT::string_type& path)
       ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:79:7: note:   template argument deduction/substitution failed:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:87:90: note:   candidate expects 2 arguments, 3 provided
     return json_query(root,path,std::char_traits<typename JsonT::char_type>::length(path));
                                                                                          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:85:7: note: template<class JsonT> JsonT jsoncons::jsonpath::json_query(const JsonT&, const typename JsonT::char_type*)
 JsonT json_query(const JsonT& root, const typename JsonT::char_type* path)
       ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:85:7: note:   template argument deduction/substitution failed:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:87:90: note:   candidate expects 2 arguments, 3 provided
     return json_query(root,path,std::char_traits<typename JsonT::char_type>::length(path));
                                                                                          ^
CMakeFiles/jsoncons_tests.dir/build.make:238: set di istruzioni per l'obiettivo "CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/jsonpath_filter_tests.cpp.o" non riuscito
make[2]: *** [CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/jsonpath_filter_tests.cpp.o] Errore 1
CMakeFiles/Makefile2:60: set di istruzioni per l'obiettivo "CMakeFiles/jsoncons_tests.dir/all" non riuscito
make[1]: *** [CMakeFiles/jsoncons_tests.dir/all] Errore 2
Makefile:76: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2
--- end output ---

**Comment by danielaparker** [comment]
Fixed on master. Thank you very much for reporting these!

**Comment by massimomorara** [comment]
Thank you very much for jsoncons!
But is fixed only the fist `term()`.

Following you first correction, I suppose that the following patch can solve the second `term()` error

--- begin patch ---
--- jsonpath_filter.hpp.sav	2016-02-19 17:38:48.563969160 +0100
+++ jsonpath_filter.hpp	2016-02-19 17:43:30.865676298 +0100
@@ -782,7 +782,7 @@
 
     std::shared_ptr<term<JsonT>> expression(token_stream<JsonT>& ts)
     {
-        auto left = term(ts);
+        auto left = term_ptr(ts);
         auto t = ts.get();
         while (true)
         {
@@ -790,14 +790,14 @@
             {
             case token_types::plus:
             {
-                JsonT val = left->plus(*(term(ts)));
+                JsonT val = left->plus(*(term_ptr(ts)));
                 left = std::make_shared<value_term<JsonT>>(val);
                 t = ts.get();
             }
                 break;
             case token_types::minus:
             {
-                JsonT val = left->minus(*(term(ts)));
+                JsonT val = left->minus(*(term_ptr(ts)));
                 left = std::make_shared<value_term<JsonT>>(val);
                 t = ts.get();
             }
@@ -810,7 +810,7 @@
         return left;
     }
 
-    std::shared_ptr<term<JsonT>> term(token_stream<JsonT>& ts)
+    std::shared_ptr<term<JsonT>> term_ptr(token_stream<JsonT>& ts)
     {
         auto left = primary(ts);
         auto t = ts.get();
--- end patch ---

**Comment by massimomorara** [comment]
Sorry: I see now that I can upload the patch.

[patch-4bis.txt](https://github.com/danielaparker/jsoncons/files/138354/patch-4bis.txt)

**Comment by danielaparker** [comment]
Thanks! Could you try master again?

If I understand correctly, it's just the 'term' parameter name in the token constructor that has to change.

Daniel

**Comment by massimomorara** [comment]
Il 19/02/2016 18:23, Daniel Parker ha scritto:
> Thanks! Could you try master again?

	Yes but... sorry... first I finish to prepare the following 2 issues.


> If I understand correctly, it's just the 'term' parameter name in the
> token constructor that has to change.

	I suppose so.

		massimo

**Comment by massimomorara** [comment]
No: I was wrong, sorry.
The problem was (and partially is) the name of the `term()` member in `class token` *and* in `class jsonpath_filter_parser`. The name `term` clash with the name of the class that is template argument of the return value (`std::shared_ptr<term<JsonT>>`).
The first correction is enough but is to be applied to `jsonpath_filter_parser::term()` too.

**Comment by danielaparker** [comment]
Fixed on master: term(ts) renamed to make_term(ts)

**Comment by massimomorara** [comment]
I confirm: fixed.
