### ISSUE TITLE
[Doc] staj_event link in document is broken

### ISSUE THREAD

**Issue by mapleFU** [danielaparker/jsoncons#562]
**Describe the proposed feature**

Hi, thanks for the jsoncons library!

I'm learning the doc of staj parser of jsoncons, I found in https://github.com/danielaparker/jsoncons/blob/cdf93ad76679c3dfbd8a926956a0628d8432219a/doc/Reference.md the link is broken. And in fact here it only have document for `staj_event_type`.

Should we add of remove the part?

**Comment by danielaparker** [comment]
Thanks for pointing that out! I fixed the link on master.

**Comment by mapleFU** [comment]
Thanks!
