### ISSUE TITLE
Replace the static_cast<int>((int)...) with static_cast<int>(...)

### ISSUE THREAD

**Issue by JohannAnhofer** [danielaparker/jsoncons#566]
Not really a bug, but it issues compiler warnings about old style casts. 
In **static_cast<int>((int)...)**  the old style cast (int) is absolutely superfluous and probably  a left-over from converting old style casts to C++ casts.

- Compiler: GCC, Clang, MinGW 
- Architecture (e.g. x86, x64) x64
- Operating system: Opensuse/Ubuntu/MacOS/Windows

 - [x] Latest release 0.178.0
 - [x] master

**Comment by danielaparker** [comment]
Fixed on master, thanks!
