### ISSUE TITLE
error: no matching function for call to ‘json_query...

### ISSUE THREAD

**Issue by massimomorara** [danielaparker/jsoncons#57]
Next error: there is a problem compiling `jsoncons_ext/jsonpath/json_query.hpp`.
At line 87

`return json_query(root,path,std::char_traits<typename JsonT::char_type>::length(path));`

my compiler give me the error

"error: no matching function for call to ‘json_query(const jsoncons::basic_json<std::basic_string<char>, std::allocator<char> >&, const char_type*&, std::size_t)"

I suppose that the problem is that in `json_query.hpp` are three overloaded versions of `json_query()` that are defined in the wrong order: the first and the second version (2 arguments) are calling the third version (3 arguments); but the third version should be defined first to be visible to the others versions.

I attach a possible patch

[patch-5.txt](https://github.com/danielaparker/jsoncons/files/138424/patch-5.txt)

I transcribe, below, the output

--- begin output ---
[  3%] Building CXX object CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/jsonpath_filter_tests.cpp.o
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/jsonpath_filter_tests.cpp:15:0:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp: In instantiation of ‘JsonT jsoncons::jsonpath::json_query(const JsonT&, const typename JsonT::char_type*) [with JsonT = jsoncons::basic_json<std::basic_string<char>, std::allocator<char> >; typename JsonT::char_type = char]’:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/jsonpath_filter_tests.cpp:102:58:   required from here
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:87:90: error: no matching function for call to ‘json_query(const jsoncons::basic_json<std::basic_string<char>, std::allocator<char> >&, const char_type*&, std::size_t)’
     return json_query(root,path,std::char_traits<typename JsonT::char_type>::length(path));
                                                                                          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:87:90: note: candidates are:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:79:7: note: template<class JsonT> JsonT jsoncons::jsonpath::json_query(const JsonT&, const typename JsonT::string_type&)
 JsonT json_query(const JsonT& root, const typename JsonT::string_type& path)
       ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:79:7: note:   template argument deduction/substitution failed:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:87:90: note:   candidate expects 2 arguments, 3 provided
     return json_query(root,path,std::char_traits<typename JsonT::char_type>::length(path));
                                                                                          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:85:7: note: template<class JsonT> JsonT jsoncons::jsonpath::json_query(const JsonT&, const typename JsonT::char_type*)
 JsonT json_query(const JsonT& root, const typename JsonT::char_type* path)
       ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:85:7: note:   template argument deduction/substitution failed:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/jsonpath/json_query.hpp:87:90: note:   candidate expects 2 arguments, 3 provided
     return json_query(root,path,std::char_traits<typename JsonT::char_type>::length(path));
                                                                                          ^
CMakeFiles/jsoncons_tests.dir/build.make:238: set di istruzioni per l'obiettivo "CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/jsonpath_filter_tests.cpp.o" non riuscito
make[2]: *** [CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/jsonpath_filter_tests.cpp.o] Errore 1
CMakeFiles/Makefile2:60: set di istruzioni per l'obiettivo "CMakeFiles/jsoncons_tests.dir/all" non riuscito
make[1]: *** [CMakeFiles/jsoncons_tests.dir/all] Errore 2
Makefile:76: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2
--- end output ---

**Comment by danielaparker** [comment]
Fixed on master

**Comment by massimomorara** [comment]
I confirm: fixed
