### ISSUE TITLE
Scripts

### ISSUE THREAD

**Issue by lisa01morris** [danielaparker/jsoncons#571]
**Describe the bug**

**Enumerate the steps to reproduce the bug**

**Include a small, self-contained example if possible**

**What compiler, architecture, and operating system?**

- Compiler: ________
- Architecture (e.g. x86, x64) ____
- Operating system: ________

**What jsoncons library version?**

 - [ ] Latest release 0.178.0
 - [ ] Other release ______
 - [ ] master

**Comment by danielaparker** [comment]
I have no idea what this is about. Please elaborate, thanks.

**Comment by lisa01morris** [comment]
Good day dear
