### ISSUE TITLE
error: call of overloaded ‘make_array(int, int)’ is ambiguous

### ISSUE THREAD

**Issue by massimomorara** [danielaparker/jsoncons#58]
Another compiling line 159 of `test_suite/src/json_array_tests.cpp`

`basic_json<std::string,std::allocator<char>> a = basic_json<std::string,std::allocator<char>>::make_array<1>(10,0);`

According to my compiler, there are 2 version of `make_array<>()`, from `jsoncons/json.hpp`, that are applicable:
1) from line 1591

`    template <size_t dim, class T>`
`    static typename std::enable_if<dim==1,basic_json>::type make_array(size_t n, const T& val, const Alloc& allocator = Alloc())`

2) from line 1597

`    template <size_t dim, typename... Args>`
`    static basic_json make_array(size_t n, Args... args)`

I'm not sure to have understand the rationale, but I suppose that the second version is intended to operate only when `dim > 1`.

In this case, a solution can be the attached

[patch-6.txt](https://github.com/danielaparker/jsoncons/files/138439/patch-6.txt)

I transcribe, below, the output

--- begin output ---
[  3%] Building CXX object CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/json_array_tests.cpp.o
/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/json_array_tests.cpp: In member function ‘void json_array_test_suite::test_one_dim_array::test_method()’:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/json_array_tests.cpp:159:118: error: call of overloaded ‘make_array(int, int)’ is ambiguous
     basic_json<std::string,std::allocator<char>> a = basic_json<std::string,std::allocator<char>>::make_array<1>(10,0);
                                                                                                                      ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/json_array_tests.cpp:159:118: note: candidates are:
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/json_array_tests.cpp:10:0:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp:1592:61: note: static typename std::enable_if<(dim == 1), jsoncons::basic_json<StringT, Alloc> >::type jsoncons::basic_json<StringT, Alloc>::make_array(size_t, const T&, const Alloc&) [with long unsigned int dim = 1ul; T = int; StringT = std::basic_string<char>; Alloc = std::allocator<char>; typename std::enable_if<(dim == 1), jsoncons::basic_json<StringT, Alloc> >::type = jsoncons::basic_json<std::basic_string<char>, std::allocator<char> >; size_t = long unsigned int]
     static typename std::enable_if<dim==1,basic_json>::type make_array(size_t n, const T& val, const Alloc& allocator = Alloc())
                                                             ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp:1598:23: note: static jsoncons::basic_json<StringT, Alloc> jsoncons::basic_json<StringT, Alloc>::make_array(size_t, Args ...) [with long unsigned int dim = 1ul; Args = {int}; StringT = std::basic_string<char>; Alloc = std::allocator<char>; size_t = long unsigned int]
     static basic_json make_array(size_t n, Args... args)
                       ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp: In instantiation of ‘static jsoncons::basic_json<StringT, Alloc> jsoncons::basic_json<StringT, Alloc>::make_array(size_t, Args ...) [with long unsigned int dim = 2ul; Args = {int, int}; StringT = std::basic_string<char>; Alloc = std::allocator<char>; size_t = long unsigned int]’:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/json_array_tests.cpp:175:39:   required from here
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp:1602:36: error: call of overloaded ‘make_array(int&, int&)’ is ambiguous
         basic_json val = make_array<dim1>(args...);
                                    ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp:1602:36: note: candidates are:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp:1592:61: note: static typename std::enable_if<(dim == 1), jsoncons::basic_json<StringT, Alloc> >::type jsoncons::basic_json<StringT, Alloc>::make_array(size_t, const T&, const Alloc&) [with long unsigned int dim = 1ul; T = int; StringT = std::basic_string<char>; Alloc = std::allocator<char>; typename std::enable_if<(dim == 1), jsoncons::basic_json<StringT, Alloc> >::type = jsoncons::basic_json<std::basic_string<char>, std::allocator<char> >; size_t = long unsigned int]
     static typename std::enable_if<dim==1,basic_json>::type make_array(size_t n, const T& val, const Alloc& allocator = Alloc())
                                                             ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp:1598:23: note: static jsoncons::basic_json<StringT, Alloc> jsoncons::basic_json<StringT, Alloc>::make_array(size_t, Args ...) [with long unsigned int dim = 1ul; Args = {int}; StringT = std::basic_string<char>; Alloc = std::allocator<char>; size_t = long unsigned int]
     static basic_json make_array(size_t n, Args... args)
                       ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp:1606:32: error: call of overloaded ‘make_array(int&, int&)’ is ambiguous
             val[i] = make_array<dim1>(args...);
                                ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp:1606:32: note: candidates are:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp:1592:61: note: static typename std::enable_if<(dim == 1), jsoncons::basic_json<StringT, Alloc> >::type jsoncons::basic_json<StringT, Alloc>::make_array(size_t, const T&, const Alloc&) [with long unsigned int dim = 1ul; T = int; StringT = std::basic_string<char>; Alloc = std::allocator<char>; typename std::enable_if<(dim == 1), jsoncons::basic_json<StringT, Alloc> >::type = jsoncons::basic_json<std::basic_string<char>, std::allocator<char> >; size_t = long unsigned int]
     static typename std::enable_if<dim==1,basic_json>::type make_array(size_t n, const T& val, const Alloc& allocator = Alloc())
                                                             ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp:1598:23: note: static jsoncons::basic_json<StringT, Alloc> jsoncons::basic_json<StringT, Alloc>::make_array(size_t, Args ...) [with long unsigned int dim = 1ul; Args = {int}; StringT = std::basic_string<char>; Alloc = std::allocator<char>; size_t = long unsigned int]
     static basic_json make_array(size_t n, Args... args)
                       ^
CMakeFiles/jsoncons_tests.dir/build.make:445: set di istruzioni per l'obiettivo "CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/json_array_tests.cpp.o" non riuscito
make[2]: *** [CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/json_array_tests.cpp.o] Errore 1
CMakeFiles/Makefile2:60: set di istruzioni per l'obiettivo "CMakeFiles/jsoncons_tests.dir/all" non riuscito
make[1]: *** [CMakeFiles/jsoncons_tests.dir/all] Errore 2
Makefile:76: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2
--- end output ---

**Comment by danielaparker** [comment]
Fixed on master.

**Comment by massimomorara** [comment]
I confirm: fixed
