### ISSUE TITLE
problem with 64bit compiler

### ISSUE THREAD

**Issue by massimomorara** [danielaparker/jsoncons#59]
Trying to compile the test suite, I obtain another error that (I suppose) derives from the fact that I'm using a 64bit compiler.
My compiler says that `jsoncons::csv::basic_csv_serializer<CharT>::do_integer_value(long long int)` and `void jsoncons::csv::basic_csv_serializer<CharT>::do_uinteger_value(long long unsigned int)` are "marked override, but does not override".
This is because in the base class (`jsoncons::basic_json_output_handler<Char>`, if I'm not wrong) this member receiving `int64_t` (the first) and `uint64_t`.
In a 32 environment, `int64_t` and `uint64_t` are (usually) defined as `long long` and `unsigned long long` (respectively) and all goes well.
But in my 64bit environment, `int64_t` and `uint64_t` are defined as `long` and `unsigned long` (respectively), so the ovverride don't work because `int64_t` is different from `long long` and `uint_64` is different from `unsigned long long`.
It seems obvious to me that you must uniform everything to `long long` and `unsigned long long` or to `int64_t` and `uint64_t`.
Taking into account that `long long` must be at least 64 bit, but can also be larger, that `do_integer_value()` is called with `long long` (`json_output_handler.hpp`, line 126) and than `do_integer_value()` isn't made (if I'm not wrong) for an argument that is exactly 64bit, I suppose that the rigth solution is change `int64_t` with `long long`. Similarly, `uint64_t` should be changed to `unsigned long long`. For `do_integer_value()`, `do_uinteger_value()`, `print_integer()` and `print_uinteger()`.

I propose the following patches.

[patch-7h.txt](https://github.com/danielaparker/jsoncons/files/138618/patch-7h.txt)
[patch-7g.txt](https://github.com/danielaparker/jsoncons/files/138619/patch-7g.txt)
[patch-7e.txt](https://github.com/danielaparker/jsoncons/files/138620/patch-7e.txt)
[patch-7d.txt](https://github.com/danielaparker/jsoncons/files/138621/patch-7d.txt)
[patch-7c.txt](https://github.com/danielaparker/jsoncons/files/138615/patch-7c.txt)
[patch-7b.txt](https://github.com/danielaparker/jsoncons/files/138616/patch-7b.txt)
[patch-7a.txt](https://github.com/danielaparker/jsoncons/files/138617/patch-7a.txt)

I transcribe, below, the output

--- begin output ---
[  3%] Building CXX object CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp.o
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:11:0:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp: In instantiation of ‘class jsoncons::csv::basic_csv_serializer<char>’:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:494:40:   required from here
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:274:10: error: ‘void jsoncons::csv::basic_csv_serializer<CharT>::do_integer_value(long long int) [with CharT = char]’ marked override, but does not override
     void do_integer_value(long long val) override
          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:289:10: error: ‘void jsoncons::csv::basic_csv_serializer<CharT>::do_uinteger_value(long long unsigned int) [with CharT = char]’ marked override, but does not override
     void do_uinteger_value(unsigned long long val) override
          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp: In member function ‘void csv_test_suite::serialize_comma_delimited_file::test_method()’:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:494:20: error: cannot declare variable ‘serializer’ to be of abstract type ‘jsoncons::csv::basic_csv_serializer<char>’
     csv_serializer serializer(std::cout);
                    ^
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:11:0:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:76:7: note:   because the following virtual functions are pure within ‘jsoncons::csv::basic_csv_serializer<char>’:
 class basic_csv_serializer : public basic_json_output_handler<CharT>
       ^
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp:21:0,
                 from /home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_reader.hpp:21,
                 from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:10:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json_output_handler.hpp:181:18: note: 	void jsoncons::basic_json_output_handler<CharT>::do_integer_value(int64_t) [with CharT = char; int64_t = long int]
     virtual void do_integer_value(int64_t value) = 0;
                  ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json_output_handler.hpp:183:18: note: 	void jsoncons::basic_json_output_handler<CharT>::do_uinteger_value(uint64_t) [with CharT = char; uint64_t = long unsigned int]
     virtual void do_uinteger_value(uint64_t value) = 0;
                  ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp: In member function ‘void csv_test_suite::serialize_tab_delimited_file::test_method()’:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:529:20: error: cannot declare variable ‘serializer’ to be of abstract type ‘jsoncons::csv::basic_csv_serializer<char>’
     csv_serializer serializer(std::cout,params);
                    ^
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_reader.hpp:17:0,
                 from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:10:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json_input_handler.hpp: In instantiation of ‘class jsoncons::basic_empty_json_input_handler<char>’:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_parser.hpp:246:51:   required from ‘void jsoncons::csv::basic_csv_parser<CharT>::begin_parse() [with CharT = char]’
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_reader.hpp:113:9:   required from ‘void jsoncons::csv::basic_csv_reader<CharT>::read() [with CharT = char]’
/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:34:17:   required from here
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json_input_handler.hpp:261:10: error: ‘void jsoncons::basic_empty_json_input_handler<CharT>::do_integer_value(long long int, const jsoncons::basic_parsing_context<CharT>&) [with CharT = char]’ marked override, but does not override
     void do_integer_value(long long, const basic_parsing_context<CharT>&) override
          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json_input_handler.hpp:265:10: error: ‘void jsoncons::basic_empty_json_input_handler<CharT>::do_uinteger_value(long long unsigned int, const jsoncons::basic_parsing_context<CharT>&) [with CharT = char]’ marked override, but does not override
     void do_uinteger_value(unsigned long long, const basic_parsing_context<CharT>&) override
          ^
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_reader.hpp:20:0,
                 from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:10:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_parser.hpp: In instantiation of ‘void jsoncons::csv::basic_csv_parser<CharT>::begin_parse() [with CharT = char]’:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_reader.hpp:113:9:   required from ‘void jsoncons::csv::basic_csv_reader<CharT>::read() [with CharT = char]’
/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:34:17:   required from here
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_parser.hpp:246:51: error: cannot declare variable ‘ih’ to be of abstract type ‘jsoncons::basic_empty_json_input_handler<char>’
             basic_empty_json_input_handler<CharT> ih;
                                                   ^
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_reader.hpp:17:0,
                 from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:10:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json_input_handler.hpp:208:7: note:   because the following virtual functions are pure within ‘jsoncons::basic_empty_json_input_handler<char>’:
 class basic_empty_json_input_handler : public basic_json_input_handler<CharT>
       ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json_input_handler.hpp:199:18: note: 	void jsoncons::basic_json_input_handler<CharT>::do_integer_value(int64_t, const jsoncons::basic_parsing_context<CharT>&) [with CharT = char; int64_t = long int]
     virtual void do_integer_value(int64_t value, const basic_parsing_context<CharT>& context) = 0;
                  ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json_input_handler.hpp:201:18: note: 	void jsoncons::basic_json_input_handler<CharT>::do_uinteger_value(uint64_t, const jsoncons::basic_parsing_context<CharT>&) [with CharT = char; uint64_t = long unsigned int]
     virtual void do_uinteger_value(uint64_t value, const basic_parsing_context<CharT>& context) = 0;
                  ^
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_reader.hpp:20:0,
                 from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:10:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_parser.hpp:260:51: error: cannot declare variable ‘ih’ to be of abstract type ‘jsoncons::basic_empty_json_input_handler<char>’
             basic_empty_json_input_handler<CharT> ih;
                                                   ^
CMakeFiles/jsoncons_tests.dir/build.make:675: set di istruzioni per l'obiettivo "CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp.o" non riuscito
make[2]: *** [CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp.o] Errore 1
CMakeFiles/Makefile2:60: set di istruzioni per l'obiettivo "CMakeFiles/jsoncons_tests.dir/all" non riuscito
make[1]: *** [CMakeFiles/jsoncons_tests.dir/all] Errore 2
Makefile:76: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2
--- end output ---

**Comment by danielaparker** [comment]
Thanks for catching that! long long and unsigned long long should have been int64_t and uint64_t consistently. Fixed on master.  

We plan to add support for val.as< a 128 bit integer type>(), but the integer type in the json class data variant will remain 64 bit, numbers bigger than that will be stored differently in allocated storage.

Daniel

**Comment by massimomorara** [comment]
Yes... you can do so... but i had a bad feeling about this :-)
With you changes, I have another error.
In `jsoncons_ext/csv/csv_serializer.hpp`, line 280, my compiler say that the call

`value(val,header_os_);`

"is ambigous".
The point is that `val` is a `int64_t` (that is `long`, in my environment) but there isn't a `value(long, ...)` overloaded function.
So the compiler don't know if calling
1) `value(double, ...)`
2) `value(long long, ...)`
3) `value(unsigned long long)`
4) `value(bool, ...)`

If `val` is a `int64_t` (or `uint64_t`), you should add overloaded versions of `value()` for `long`, `unsigned long`, `int`, `unsigned int`, `short` and `unsigned short` (nothing forbid `int64_t` to be defined as `int` or `short`, in a platform where `int` or `short` is 64bit wide). Otherwise, you can modify `value(long long, ...)` in `value(int64_t, ...)`, but I don't know if it's consistent with the project.
If you use ever `long long` instead of `int64_t`, you shoudn't have this sort of problems.

Same problem in lines 284, 295 and 299.

I transcribe, below, the output

--- begin output ---
[  3%] Building CXX object CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp.o
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:11:0:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp: In instantiation of ‘void jsoncons::csv::basic_csv_serializer<CharT>::do_integer_value(int64_t) [with CharT = char; int64_t = long int]’:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:534:1:   required from here
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:280:37: error: call of overloaded ‘value(int64_t&, jsoncons::buffered_ostream<char>&)’ is ambiguous
                 value(val,header_os_);
                                     ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:280:37: note: candidates are:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:339:10: note: void jsoncons::csv::basic_csv_serializer<CharT>::value(double, jsoncons::buffered_ostream<CharT>&) [with CharT = char]
     void value(double val, buffered_ostream<CharT>& os)
          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:372:10: note: void jsoncons::csv::basic_csv_serializer<CharT>::value(long long int, jsoncons::buffered_ostream<CharT>&) [with CharT = char]
     void value(long long val, buffered_ostream<CharT>& os)
          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:383:10: note: void jsoncons::csv::basic_csv_serializer<CharT>::value(long long unsigned int, jsoncons::buffered_ostream<CharT>&) [with CharT = char]
     void value(unsigned long long val, buffered_ostream<CharT>& os)
          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:394:10: note: void jsoncons::csv::basic_csv_serializer<CharT>::value(bool, jsoncons::buffered_ostream<CharT>&) [with CharT = char]
     void value(bool val, buffered_ostream<CharT>& os) 
          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:284:30: error: call of overloaded ‘value(int64_t&, jsoncons::buffered_ostream<char>&)’ is ambiguous
                 value(val,os_);
                              ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:284:30: note: candidates are:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:339:10: note: void jsoncons::csv::basic_csv_serializer<CharT>::value(double, jsoncons::buffered_ostream<CharT>&) [with CharT = char]
     void value(double val, buffered_ostream<CharT>& os)
          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:372:10: note: void jsoncons::csv::basic_csv_serializer<CharT>::value(long long int, jsoncons::buffered_ostream<CharT>&) [with CharT = char]
     void value(long long val, buffered_ostream<CharT>& os)
          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:383:10: note: void jsoncons::csv::basic_csv_serializer<CharT>::value(long long unsigned int, jsoncons::buffered_ostream<CharT>&) [with CharT = char]
     void value(unsigned long long val, buffered_ostream<CharT>& os)
          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:394:10: note: void jsoncons::csv::basic_csv_serializer<CharT>::value(bool, jsoncons::buffered_ostream<CharT>&) [with CharT = char]
     void value(bool val, buffered_ostream<CharT>& os) 
          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp: In instantiation of ‘void jsoncons::csv::basic_csv_serializer<CharT>::do_uinteger_value(uint64_t) [with CharT = char; uint64_t = long unsigned int]’:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:534:1:   required from here
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:295:37: error: call of overloaded ‘value(uint64_t&, jsoncons::buffered_ostream<char>&)’ is ambiguous
                 value(val,header_os_);
                                     ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:295:37: note: candidates are:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:339:10: note: void jsoncons::csv::basic_csv_serializer<CharT>::value(double, jsoncons::buffered_ostream<CharT>&) [with CharT = char]
     void value(double val, buffered_ostream<CharT>& os)
          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:372:10: note: void jsoncons::csv::basic_csv_serializer<CharT>::value(long long int, jsoncons::buffered_ostream<CharT>&) [with CharT = char]
     void value(long long val, buffered_ostream<CharT>& os)
          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:383:10: note: void jsoncons::csv::basic_csv_serializer<CharT>::value(long long unsigned int, jsoncons::buffered_ostream<CharT>&) [with CharT = char]
     void value(unsigned long long val, buffered_ostream<CharT>& os)
          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:394:10: note: void jsoncons::csv::basic_csv_serializer<CharT>::value(bool, jsoncons::buffered_ostream<CharT>&) [with CharT = char]
     void value(bool val, buffered_ostream<CharT>& os) 
          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:299:30: error: call of overloaded ‘value(uint64_t&, jsoncons::buffered_ostream<char>&)’ is ambiguous
                 value(val,os_);
                              ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:299:30: note: candidates are:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:339:10: note: void jsoncons::csv::basic_csv_serializer<CharT>::value(double, jsoncons::buffered_ostream<CharT>&) [with CharT = char]
     void value(double val, buffered_ostream<CharT>& os)
          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:372:10: note: void jsoncons::csv::basic_csv_serializer<CharT>::value(long long int, jsoncons::buffered_ostream<CharT>&) [with CharT = char]
     void value(long long val, buffered_ostream<CharT>& os)
          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:383:10: note: void jsoncons::csv::basic_csv_serializer<CharT>::value(long long unsigned int, jsoncons::buffered_ostream<CharT>&) [with CharT = char]
     void value(unsigned long long val, buffered_ostream<CharT>& os)
          ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_serializer.hpp:394:10: note: void jsoncons::csv::basic_csv_serializer<CharT>::value(bool, jsoncons::buffered_ostream<CharT>&) [with CharT = char]
     void value(bool val, buffered_ostream<CharT>& os) 
          ^
CMakeFiles/jsoncons_tests.dir/build.make:675: set di istruzioni per l'obiettivo "CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp.o" non riuscito
make[2]: *** [CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp.o] Errore 1
CMakeFiles/Makefile2:60: set di istruzioni per l'obiettivo "CMakeFiles/jsoncons_tests.dir/all" non riuscito
make[1]: *** [CMakeFiles/jsoncons_tests.dir/all] Errore 2
Makefile:76: set di istruzioni per l'obiettivo "all" non riuscito
make: *** [all] Errore 2
--- end output ---

**Comment by danielaparker** [comment]
Those long long and unsigned long long types in csv_serializer should have been changed to int64_t and uint64_t too, fixed on master.

**Comment by massimomorara** [comment]
I confirm: fixed.
And more: compilation OK; test OK.
