### ISSUE TITLE
warning: enumeration values not handled in switches

### ISSUE THREAD

**Issue by massimomorara** [danielaparker/jsoncons#61]
Warning compiling with `clang++` the test suite.
There are some switches, in `jsoncons_ext/csv/csv_reader.hpp`, that do not handle all enum cases.
The first is in line 200 and do not handle the cases "modes::header" and "modes::done".
The second is in line 214 and do not handle the case "modes::done".
The third is in line 453 and do not handle 13 cases (all cases except "states::unquoted_string" and "states::escaped_value").
The fourth is in line 473 and do not handle the case "modes::done".

--- begin output ---
[ 96%] Building CXX object CMakeFiles/jsoncons_tests.dir/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp.o
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:10:
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_reader.hpp:20:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_parser.hpp:214:17: warning: enumeration value 'done' not handled in switch [-Wswitch]
        switch (stack_[top_])
                ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_parser.hpp:339:21: note: in instantiation of member function 'jsoncons::csv::basic_csv_parser<char>::after_record' requested here
                    after_record();
                    ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_reader.hpp:135:25: note: in instantiation of member function 'jsoncons::csv::basic_csv_parser<char>::parse' requested here
                parser_.parse(buffer_.data(),index_,buffer_length_);
                        ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:34:12: note: in instantiation of member function 'jsoncons::csv::basic_csv_reader<char>::read' requested here
    reader.read();
           ^
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:10:
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_reader.hpp:20:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_parser.hpp:200:21: warning: enumeration values 'done' and 'header' not handled in switch [-Wswitch]
            switch (stack_[top_])
                    ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_parser.hpp:356:25: note: in instantiation of member function 'jsoncons::csv::basic_csv_parser<char>::before_record' requested here
                        before_record();
                        ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_reader.hpp:135:25: note: in instantiation of member function 'jsoncons::csv::basic_csv_parser<char>::parse' requested here
                parser_.parse(buffer_.data(),index_,buffer_length_);
                        ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:34:12: note: in instantiation of member function 'jsoncons::csv::basic_csv_reader<char>::read' requested here
    reader.read();
           ^
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:10:
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_reader.hpp:20:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_parser.hpp:453:17: warning: 13 enumeration values not handled in switch: 'start', 'comment', 'expect_value'... [-Wswitch]
        switch (state_)
                ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_reader.hpp:139:17: note: in instantiation of member function 'jsoncons::csv::basic_csv_parser<char>::end_parse' requested here
        parser_.end_parse();
                ^
/home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:34:12: note: in instantiation of member function 'jsoncons::csv::basic_csv_reader<char>::read' requested here
    reader.read();
           ^
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/src/csv_tests.cpp:10:
In file included from /home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_reader.hpp:20:
/home/max/big/src/jsoncons-git/jsoncons/test_suite/build/cmake/../../../src/jsoncons_ext/csv/csv_parser.hpp:473:17: warning: enumeration value 'done' not handled in switch [-Wswitch]
        switch (stack_[top_])
                ^
4 warnings generated.
--- end output ---

**Comment by danielaparker** [comment]
I've added default: break; for the values that have no action required.

**Comment by massimomorara** [comment]
I confirm: no more warnings.
