### ISSUE TITLE
a little warning: extra ";"

### ISSUE THREAD

**Issue by massimomorara** [danielaparker/jsoncons#63]
Compiling a little test program with g++ (but clang++ say nothing), I obtain the following warning

`./jsoncons/json_error_category.hpp:39:2: warning: extra ‘;’ [-Wpedantic]`
` };`
`  ^`

And is right: a `namespace` isn't a `class` or a `struct` and don't want a closing `';'`

**Comment by danielaparker** [comment]
Fixed

**Comment by massimomorara** [comment]
I confirm: fixed.
