### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by phand00** [danielaparker/jsoncons#65]
Hi,

first time using the library with Visual Studio 2013.
I try to use wjson (UTF16).

in file json.hpp:
...
```
   template <typename T>
    basic_json(T val)
        : var_(null_type())
    {
==>        json_type_traits<value_type,T>::assign(*this,val);    <==
    }

```
Here is the error I get:
189 error C3861: 'assign': identifier not found
188 error C2039: 'assign': is not a member of 'jsoncons::json_type_traits<jsoncons::basic_json<wchar_t, std::allocator<void>>, T>'

Any idea where to search for. I take a look a json_type_traits.hpp and the wchar_t seems to be define correctly with a corresponding assign method:

```
template<class JsonT>
class json_type_traits<JsonT, wchar_t>
{
public:
    static bool is(const JsonT& rhs) JSONCONS_NOEXCEPT
    {
        if (rhs.is_integer())
        {
            return rhs.as_integer() >= std::numeric_limits<wchar_t>::min JSONCONS_NO_MACRO_EXP() && rhs.as_integer() <= std::numeric_limits<wchar_t>::max JSONCONS_NO_MACRO_EXP();
        }
        else if (rhs.is_uinteger())
        {
            return rhs.as_uinteger() <= static_cast<unsigned long long>(std::numeric_limits<wchar_t>::max JSONCONS_NO_MACRO_EXP());
        }
        else
        {
            return false;
        }
    }
    static wchar_t as(const JsonT& rhs)
    {
        return static_cast<wchar_t>(rhs.as_integer());
    }
    static void assign(JsonT& lhs, wchar_t ch)
    {
        lhs.assign_integer(ch);
    }
};
```

thanks for your help.

**Comment by danielaparker** [comment]
Which version of jsoncons are you using?

**Comment by phand00** [comment]
All right,

was able to reproduce the problem and identify the root of it...
Here is a sample:

```
	tjson root;
	tjson json_obj;

	PTCHAR pAttribute = _T("Attribute");
	TCHAR szTest[40] = _T("TEST BUFFER");
	
	root[_T("Test")] = _T("1 - 2");
	root[pAttribute] = szTest;
```

In this sample, the line root[pAttribute] = szTest cause the assign compile error.

PTCHAR is a wchar_t pointer  as defined in winnt.h

```
typedef WCHAR TCHAR, *PTCHAR;
typedef wchar_t WCHAR;    // wc,   16-bit UNICODE character

```

**Comment by danielaparker** [comment]
Okay, rewriting it as

    wjson root;
    wjson json_obj;

    wchar_t* pAttribute = L"Attribute";
    wchar_t* szTest = L"TEST BUFFER";

    root[L"Test"] = L"1 - 2";
    root[pAttribute] = szTest;

    std::wcout << root;

and testing on master with clang (my most compliant compiler) produces

    ISO C++11 does not allow conversion from string literal to `wchar_t *`

    no member named 'assign' in 'jsoncons::json_type_traits<jsoncons::basic_json<wchar_t,      std::allocator<wchar_t> >, wchar_t *>

The first error message relates to your assignments: in C++ 11, it's an error to assign L"" to a non const wchar_t*. Fixing that,

   const  wchar_t* pAttribute = L"Attribute";
   const wchar_t* szTest = L"TEST BUFFER";

it compiles, and the output is

    {"Attribute":"TEST BUFFER","Test":"1 - 2"}

It also compiles now with vs 2015 and vs 2013.

I still don't understand the `assign` error with non-const wchar_t*, but it works with const wchar_t*.

**Comment by phand00** [comment]
OK, thanks for quick answer.

The assignment of L"" to non const is purely for the sample purpose.

Do you have an Idea where to search for? I'm pretty new to your lib.... I didn't try with `char* `vs `const char*`. But I presume it's running fine...

Thanks again.

Dan

**Comment by danielaparker** [comment]
Hello Dan,

Just a quick follow up. Note that assignment of a string literal to non-const is illegal since C++11, it shouldn't compile, vs is non-conformant in that regard.

But the other issue, given that you have a non-const C string, and want to assign it to a json object, that should have worked. In fact json_type_traits didn't have a non-const specialization for C strings, I've added one, and this now works on master, for example:

    wjson root;

    const wchar_t* p = L"A string";
    wchar_t* q = const_cast<wchar_t*>(p);

    root["Test"] = q;

**Comment by phand00** [comment]
confirm it's working fine. Thanks a lot. :-)
