### ISSUE TITLE
float_reader locale

### ISSUE THREAD

**Issue by phand00** [danielaparker/jsoncons#66]
Hi Daniel,

I notice another problem at runtime when generating json code...
I was able to see another issue with DebugDiag and I always got this stack trace at runtime :

```
LeakTrack+13277      
Test!_calloc_impl+5d   f:\dd\vctools\crt\crtw32\heap\calloc_impl.c @ 47   
Test!_calloc_crt+33   f:\dd\vctools\crt\crtw32\heap\crtheap.c @ 62 + e   
Test!_wcreate_locale+69   f:\dd\vctools\crt\crtw32\misc\wsetloca.c @ 337 + d   
Test!_create_locale+5a   f:\dd\vctools\crt\crtw32\misc\wsetloca.c @ 400 + c   
Test!jsoncons::basic_json_parser<wchar_t>::basic_json_parser<wchar_t>+b8   c:\projets\Test\commun\jsoncons\json_parser.hpp @ 168 + b8   
Test!jsoncons::operator>><jsoncons::basic_json<wchar_t,std::allocator<wchar_t> > >+91   c:\projets\Test\commun\jsoncons\json.hpp @ 3443 + e   
Test!l_set_user+2f   c:\projets\Test\Test\Test.cpp @ 8696 + 29   
Test!l_set+361   c:\projets\Test\Test\Test.h @ 925 + 1c   
```

The solution I found is to handle the _locale_t member in float_reader class in jsoncons_io.hpp:
If I'm not wrong, the _locale_t struct must be freed with a call to _free_locale
So I add a destructor to handle this case. I also add some restrictions to assignment and copy constructor because I don't want the class to be copied by the system and cause any kind of crash on the call to _free_locale(locale) later during execution.

   ```
 float_reader() : locale()
    {
        locale = _create_locale(LC_NUMERIC, "C");
    }
    ~float_reader() {
        _free_locale(locale);
    }

    float_reader(const float_reader& fr) = delete;
    float_reader& operator=(const float_reader& fr) = delete;
```

Thanks.

**Comment by danielaparker** [comment]
Thanks for catching this! I've incorporated your changes on master.

**Comment by sergign60** [comment]
Hi Daniel,

I have another problem with jsoncons_master on Ubuntu 14.04 gcc version 5.3, boost 1.60


jsoncons/test_suite/build/cmake$ make
[ 3%] Building CXX object CMakeFiles/jsoncons_tests.dir/home/serg/ION/jsoncons/test_suite/src/json_filter_tests.cpp.o
In file included from /home/serg/ION/jsoncons/test_suite/src/json_filter_tests.cpp:15:0:
/home/serg/ION/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json_filter.hpp: In constructor ‘jsoncons::basic_begin_end_json_filter<CharT>::basic_begin_end_json_filter(jsoncons::basic_json_input_handler<CharT>&)’:
/home/serg/ION/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json_filter.hpp:224:11: error: class ‘jsoncons::basic_begin_end_json_filter<CharT>’ does not have any field named ‘json_filter’
: json_filter(handler)
^
make[2]: *** [CMakeFiles/jsoncons_tests.dir/home/serg/ION/jsoncons/test_suite/src/json_filter_tests.cpp.o] Error 1
make[1]: *** [CMakeFiles/jsoncons_tests.dir/all] Error 2
make: *** [all] Error 2

Do you know anything about it WBR,
Serguei

**Comment by sergign60** [comment]
another problem with examples - compiler gcc 5.3


jsoncons/examples/build/cmake$ make 
[ 16%] Building CXX object CMakeFiles/jsoncons_examples.dir/home/serg/ION/jsoncons/examples/src/readme_examples.cpp.o
/home/serg/ION/jsoncons/examples/src/readme_examples.cpp: In function ‘void readme_examples::example3()’:
/home/serg/ION/jsoncons/examples/src/readme_examples.cpp:314:40: error: no matching function for call to ‘std::basic_ofstream<wchar_t>::basic_ofstream(const wchar_t [15])’
std::wofstream os(L"booklist2.json");
^
In file included from /home/serg/ION/jsoncons/examples/src/readme_examples.cpp:4:0:
/usr/include/c++/5/fstream:725:7: note: candidate: std::basic_ofstream<_CharT, _Traits>::basic_ofstream(std::basic_ofstream<_CharT, _Traits>&&) [with _CharT = wchar_t; _Traits = std::char_traits<wchar_t>]
basic_ofstream(basic_ofstream&& __rhs)
^
/usr/include/c++/5/fstream:725:7: note: no known conversion for argument 1 from ‘const wchar_t [15]’ to ‘std::basic_ofstream<wchar_t>&&’
/usr/include/c++/5/fstream:715:7: note: candidate: std::basic_ofstream<_CharT, _Traits>::basic_ofstream(const string&, std::ios_base::openmode) [with _CharT = wchar_t; _Traits = std::char_traits<wchar_t>; std::string = std::basic_string<char>; std::ios_base::openmode = std::_Ios_Openmode]
basic_ofstream(const std::string& __s,
^
/usr/include/c++/5/fstream:715:7: note: no known conversion for argument 1 from ‘const wchar_t [15]’ to ‘const string& {aka const std::basic_string<char>&}’
/usr/include/c++/5/fstream:697:7: note: candidate: std::basic_ofstream<_CharT, _Traits>::basic_ofstream(const char*, std::ios_base::openmode) [with _CharT = wchar_t; _Traits = std::char_traits<wchar_t>; std::ios_base::openmode = std::_Ios_Openmode]
basic_ofstream(const char* __s,
^
/usr/include/c++/5/fstream:697:7: note: no known conversion for argument 1 from ‘const wchar_t [15]’ to ‘const char*’
/usr/include/c++/5/fstream:682:7: note: candidate: std::basic_ofstream<_CharT, _Traits>::basic_ofstream() [with _CharT = wchar_t; _Traits = std::char_traits<wchar_t>]
basic_ofstream(): __ostream_type(), _M_filebuf()
^
/usr/include/c++/5/fstream:682:7: note: candidate expects 0 arguments, 1 provided
make[2]: *** [CMakeFiles/jsoncons_examples.dir/home/serg/ION/jsoncons/examples/src/readme_examples.cpp.o] Error 1
make[1]: *** [CMakeFiles/jsoncons_examples.dir/all] Error 2
make: *** [all] Error 2

**Comment by sergign60** [comment]
Daniel, 

I suggest the following fixes:

 git diff src/jsoncons/json_filter.hpp

@@ -221,7 +221,7 @@ class basic_begin_end_json_filter : public basic_json_filter<CharT>
{
public:
basic_begin_end_json_filter(basic_json_input_handler<CharT>& handler)
- : json_filter(handler)
+ : basic_json_filter<CharT>(handler)
{
}
private:

git diff examples/src/readme_examples.cpp

@@ -311,7 +311,8 @@ void example3()
book[L"ratings"].erase(L"*");

// Serialize the booklist to a file
- std::wofstream os(L"booklist2.json");
+ std::wofstream os("booklist2.json");
os << pretty_print(booklist);
}

WBR,
Serguei

**Comment by danielaparker** [comment]
Thanks! I've incorporated those two.
