### ISSUE TITLE
json_parser_errc should not have the value 0

### ISSUE THREAD

**Issue by qis** [danielaparker/jsoncons#68]
When `jsoncons::json_parser_errc::unexpected_eof` is stored as `std::error_code`, then it cannot be tested in the usual way: [std::error_code::operator bool](http://en.cppreference.com/w/cpp/error/error_code/operator_bool)

I suggest increasing all `jsoncons::json_parser_errc` values by `1` and returning `null` instead of throwing:

```
static basic_json parse(const string_type& s, basic_parse_error_handler<char_type>& err_handler)
{
    basic_json_deserializer<basic_json<StringT, Alloc>> handler;
    basic_json_parser<char_type> parser(handler,err_handler);
    parser.begin_parse();
    parser.parse(s.data(),0,s.length());
    parser.end_parse();
    parser.check_done(s.data(),parser.index(),s.length());
    if (!handler.is_valid())
    {
        //JSONCONS_THROW_EXCEPTION(std::runtime_error,"Failed to parse json string");
        return null;
    }
    return handler.get_result();
}
```

**Comment by danielaparker** [comment]
Good point about the error codes, I've re-based them to 1 (on master.) Returning a null pointer in parse isn't an option, as the function returns a value. Returning a null json value isn't right either, as that's a valid value. Also note that the parser will generally throw a parse exception when it encounters a parsing error.

**Comment by qis** [comment]
It looks like the parser throws only when in a bad state. I think it would it be reasonable to simply stop parsing when an error handler functions return `false` instead of `void` and have an error handler that throws if that's desired.

**Comment by danielaparker** [comment]
json_reader now supports indicating errors through error codes as an alternative to throwing exceptions. See the documentation for json_reader for examples.
