### ISSUE TITLE
Inclusion of csv_reader header causes trouble

### ISSUE THREAD

**Issue by giordan12** [danielaparker/jsoncons#69]
I am testing the cv_reader by using this code:
`#include <iostream>
#include <fstream>
#include <string>
#include "jsoncons/json.hpp"
#include "jsoncons/json_deserializer.hpp"
#include "jsoncons_ext/csv/csv_reader.hpp"

using jsoncons::json;
using jsoncons::pretty_print;
using jsoncons::output_format;
using jsoncons::json_deserializer;
using jsoncons::csv::csv_reader;
using jsoncons::csv::csv_parameters;

int main(int argc, char** argv) {

}
`
and I get this error:
json_filter.hpp:224:11: error: class 'jsoncons::basic_begin_end_json_filter<CharT>' does not have any field named 'basic_json_filter'
         : basic_json_filter(handler)
Is there any way to just avoid this?

**Comment by danielaparker** [comment]
Could you try again using the latest master?

Thanks,
Daniel

**Comment by danielaparker** [comment]
I believe this is fixed on master.
