### ISSUE TITLE
Need some help reading data

### ISSUE THREAD

**Issue by MFallqvist** [danielaparker/jsoncons#70]
Hi im using your parser to read a file, but the problem for me is that the data I want to find is within the field extrincisics, namely "rotation" and "center". The json-file looks like this: 
{
    "sfm_data_version": "0.2",
    "root_path": "D:\\Lagring\\Plugg\\Examensarbete\\Data\\images",
    "views": [],
    "intrinsics": [],
    "extrinsics": [
        {
            "key": 0,
            "value": {
                "rotation": [
                    [
                        0.89280214808572156,
                        0.35067276062587932,
                        -0.28272413998197254
                    ],
                    [
                        -0.090429686592667424,
                        0.75440463553446824,
                        0.65015084224113584
                    ],
                    [
                        0.44127859245183554,
                        -0.5548894131618759,
                        0.70524530697098287
                    ]
                ],
                "center": [
                    -0.60959634064871249,
                    0.24123645392011658,
                    0.57783384588917808
                ]
            }
        },
        {
            "key": 1,
            "value": {
                "rotation": [
... etc

I successfully extract the "extrinsics" field (but not sure how to use it): 
string extrinsics(jsonFile["extrinsics"].as<std::string>());

And then I have tried using stringstream:
string extrinsics(jsonFile["extrinsics"].as<std::string>());
stringstream ss(extrinsics);

But this just means other problems, I rather would like your parser to find the data within the field "rotation" and "center". Should be relatively simple.. what am I missing?

**Comment by danielaparker** [comment]
Assuming you've read the text into a json value `root`:

```
    json extrinsics = root["extrinsics"];

    // Iterate over the elements of extrinsics
    for (auto extrinsic : extrinsics.elements())
    {
        json center = extrinsic["value"]["center"]; 

        // Access the elements of center as doubles
        double x = center[0].as<double>();
        double y = center[1].as<double>();
        double z = center[2].as<double>();

        json rotation = extrinsic["value"]["rotation"]; 
        // Similarly, access the elements of rotation as doubles
    }
```

**Comment by MFallqvist** [comment]
Ah nice it works perfect, thanks for a fast reply! :)
