### ISSUE TITLE
Missing File (json_exception.hpp)

### ISSUE THREAD

**Issue by WorksWellWithOthers** [danielaparker/jsoncons#76]
It seems the file "json_exception.hpp" is missing.

**Comment by WorksWellWithOthers** [comment]
`// Copyright 2013 Daniel Parker
// Distributed under the Boost license, Version 1.0.
// (See accompanying file LICENSE_1_0.txt or copy at http://www.boost.org/LICENSE_1_0.txt)

// See https://sourceforge.net/projects/jsoncons/files/ for latest version
// See https://sourceforge.net/p/jsoncons/wiki/Home/ for documentation.

#ifndef JSONCONS_JSON_EXCEPTION_HPP
#define JSONCONS_JSON_EXCEPTION_HPP

#include <string>
#include <vector>
#include <exception>
#include <cstdlib>
#include <cstring>
#include <iostream>
#include <cstdio>
#include "jsoncons/jsoncons.hpp"

namespace jsoncons {

}

#endif`

**Comment by danielaparker** [comment]
Where are you seeing that?

There is no file called `json_exception.hpp` in recent distributions. The class `json_exception` is defined in `jsoncons.hpp`.

**Comment by WorksWellWithOthers** [comment]
I'm sorry. I must be using an older copy. I was trying to follow the missing / default behavior portion of the documentation when I found out my json_exception was not being recognized.

Adding the json_exception.hpp removed that error for me. I did not realize that it is built in to the current version of jsoncons.hpp
