### ISSUE TITLE
Android does support localeconv

### ISSUE THREAD

**Issue by Phaestion** [danielaparker/jsoncons#78]
Hi there
I use your library in a project that I cross compile for Android. I recently upgraded to a new version of your library which has locale support for floats. 

Unfortunately Android does not have an implementation for "localeconv", so I had to comment that part out that it defaults to ".".

A macro can be used to do that I suppose.

Regards

**Comment by danielaparker** [comment]
Thanks for reporting this. The use of locale is to get around the fact that the C functions for converting to floats use the global locale, so we convert '.' to what strtod expects based on localeconv. To fix this we'll provide an alternative string to float converter conditional on __ANDROID__.

**Comment by danielaparker** [comment]
I've implemented a `#if` fix that should work with android, but can't test. Could you let me know if the code on master compiles with android?

Thanks,
Daniel

**Comment by danielaparker** [comment]
I'm closing this issue, will reopen if anyone reports a problem.
