### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by rychale** [danielaparker/jsoncons#79]
Hi,

Could you please fix compilation error:

ext/jsoncons/src/jsoncons/json_structures.hpp:1034:48: error: ‘s’ was not declared in this scope
         equals_pred<value_type,char_type> comp(s, length);
                                                ^

ext/jsoncons/src/jsoncons/json_structures.hpp:1034:51: error: ‘length’ was not declared in this scope
         equals_pred<value_type,char_type> comp(s, length);

**Comment by stephenberry** [comment]
The error described above is from the following function:
```
void set(string_type&& name, const Json& value)
    {
        equals_pred<value_type,char_type> comp(s, length);
        . . .
```

I don't get the error when compiling with Visual Studio 2015, but I get it when building with Xcode.

**Comment by danielaparker** [comment]
Thanks. Should be fixed. VS2015 skips compiling template code for functions that aren't being used, so it missed it.
