### ISSUE TITLE
Compilation Error: No member named 'assign'

### ISSUE THREAD

**Issue by stephenberry** [danielaparker/jsoncons#80]
I'm getting the following compilation error:
json.hpp:1698:41: No member named 'assign' in 'jsoncons::json_type_traits<jsoncons::basic_json<char, jsoncons::json_traits<char>, std::__1::allocator<char> >, std::__1::__bit_const_reference<std::__1::vector<bool, std::__1::allocator<bool> > > >'
``` c++
template <class T>
    basic_json(T val)
        : var_(null_type())
    {
        json_type_traits<value_type,T>::assign(*this,val);
    }
```

**Comment by danielaparker** [comment]
Which compiler? What platform?

Thanks,
Daniel

**Comment by stephenberry** [comment]
Xcode, Apple LLVM 7.1 with -std=c++14 and libc++ (LLVM C++ standard library with C++11 support)

Thanks,
Stephen

**Comment by danielaparker** [comment]
Can you provide a simple example that has this issue? It's happening with a constructor that takes a single argument, but I can't tell the type of the argument.

`json_type_traits<value_type,T>::assign` should exist for every type `T` that has a specialization in `json_type_traits.hpp`, which should be all the supported ones.

Thanks,
Daniel

**Comment by stephenberry** [comment]
I did some testing and it's when I use: `std::vector<bool>`

Other vector types compile fine, such as: `std::vector<double>`, `std::vector<size_t>`, etc.

Here's my function call that generates the error:
``` c++
bool success = access<std::string, double, bool, int, unsigned, size_t, vector<double>, vector<int>, vector<unsigned>, vector<size_t>>(variable, variable_out, base);
```

For testing I simplified it to:
``` c++
bool success = access<vector<bool>>(variable, variable_out, base);
```

And the access function that uses jsoncons:
``` c++
template <typename T>
      static bool access(jsoncons::json& obj, jsoncons::json& obj_out, Module& base)
      {
         std::string type = obj["type"].as<std::string>();
         std::string var = obj["var"].as<std::string>();

         bool success = false;
         if (typeid(T).name() == type)
         {
            success = true;
            if (obj.count("value")) // If a "value" member is specified, then we assume the user wants to set the variable.
               success = base.vars.set(var, obj["value"].as<T>());

            if (obj.count("t"))
            {
               const double t = obj["t"].as<double>();
               const auto& hist = base.history<T>(var);
               obj_out["value"] = interpolate(t, base.timeHistory(), hist);
            }

            obj_out["type"] = type;
            obj_out["value"] = base.vars.get<T>(var);
            obj_out["var"] = var;
         }

         return success;
      }

      template <typename First, typename Second, typename... Types>
      static bool access(jsoncons::json& obj, jsoncons::json& obj_out, Module& base)
      {
         if (access<First>(obj, obj_out, base))
            return true;

         return access<Second, Types...>(obj, obj_out, base);
      }
```

**Comment by danielaparker** [comment]
Thanks, I see what the issue is. std::vector<bool> is a special case, and it's element type (not bool) is not represented in json_type_traits. Let me think about how to fix this.

**Comment by danielaparker** [comment]
I've added an explicit specialization for std::vector<bool> to json_type_traits. Can you let me know if that resolves the issue?

Thanks,
Daniel

**Comment by stephenberry** [comment]
A template specification is needed:
``` c++
if (!rhs[i].is<bool>())
```
to
``` c++
if (!rhs[i].template is<bool>())
```
Just like your other code. Also for `v[i] = rhs[i].as<bool>();`

But, even after adding the `.template` I still get the same compile error. I can't tell why, it seems like it should work. I'll look more at it tomorrow if you haven't figured it out by then.

Thanks so much,
Stephen

**Comment by danielaparker** [comment]
Could you try again with the latest master? I've added a specialization of `vector<bool>::reference` to `json_type_traits`. I've added a test case that exhibits the issue in the absence of this specialization.

**Comment by stephenberry** [comment]
I still get the same error unless I change the new template to use `const_reference`:

``` c++
template<class Json>
class json_type_traits<Json, std::vector<bool>::const_reference>
. . .
    static void assign(Json& lhs, std::vector<bool>::const_reference hrs)
    . . .
```

Do you know why `const_reference` would be needed in my case?

Is this because my function taking the cast object is wanting a `const T&`?

**Comment by danielaparker** [comment]
In `json_type_traits::assign`, the `json` array value is constructed from `std::vector<bool>::const_iterator` begin/end iterators. That constructor uses `json_type_traits` for accessing the `std::vector<bool>::const_reference` elements from the iterator. 

 `std::vector<bool>` is a special case, and `std::vector<bool>::reference` is an implementation defined space efficient type. My understanding, however, is that `std::vector<bool>::const_reference` is generally defined as `bool`, it is with Visual Studio. But that doesn't seem to be with your toolset, as otherwise changing the template to use `const_reference` would collide with `bool`.

We can support this with `SFINAE`, having a` json_type_traits specialization` just for `bool`, if the two types are the same, or two specializations, if the types differ. 

In the meantime, use your fix, but we should have a solution on master fairly soon.

**Comment by danielaparker** [comment]
Could you try again with the latest master?

**Comment by stephenberry** [comment]
I tested the code and that fixed the problem! Thanks for handling this so quickly, and for your helpful explantation.

Stephen
