### ISSUE TITLE
json query evaluator helper function to detect single match

### ISSUE THREAD

**Issue by sjiekak** [danielaparker/jsoncons#82]
Is it possible to implement a helper function to test if a query result matched a single non array value?
For instance, I want `json_query(json, "$")` to return `json` and not `[json]`.  

It will be as simple as 

```
//jsonpath_evaluator
bool is_strict_single_match() const
{
	if (stack_.size() != 1)
		return false;

	cjson_ptr p = stack_.back()[0];

	return p->type() != value_types::array_t;
}
```

**Comment by danielaparker** [comment]
The specification for JsonPath (or the closest we have to one) requires returning an array, see http://goessner.net/articles/JsonPath/. See also the discussion here, http://stackoverflow.com/questions/23608050/getting-a-single-value-from-a-json-object-using-jsonpath.  

If you want to get a single value in some circumstances, why not just write a wrapper function over `json_query`? The elements in the array that `json_query` returns are just the elements in stack_.back(), if any.

Daniel

**Comment by sjiekak** [comment]
Thanks for the links.  
I would like this function to be independent from the query path and json parameters. To implement it with the current API, where `jsonpath_evaluator` members are rightfully private, I would have to mimic `jsonpath_evaluator`. 

This function could still be implemented in `jsonpath_evaluator `without breaking the spec. The user will have to use the `jsonpath_evaluator` object itself like this :  

```
//root, path arguments
using namespace jsoncons::jsonpath;
jsoncons::json result;

jsonpath_evaluator<jsoncons::json> evaluator;
evaluator.evaluate(root , path);

bool scalar = evaluator.is_strict_single_match();
if(scalar)
{
    result = evaluator.get_values();
}
else
{
    result = evaluator.get_values()[0];
}
```

**Comment by danielaparker** [comment]
If you define a function

template<class Json>
Json my_json_query(const Json& root, const typename Json::char_type* path)
{
    Json temp = json_query(root, path);
    return temp.size() == 1 ? std::move(temp[0]) : std::move(temp);
}

the user would only have to write

    json result = my_json_query(root, path);

and that does the same thing.

**Comment by sjiekak** [comment]
There is a single difference. If it matches an array with one element, the version I suggested will return this array (as an array) while what the user can write will return the first element of the array.

**Comment by danielaparker** [comment]
I'm closing this issue, as I want to keep `jsonpath_evaluator` part of the implementation, and because you can get exactly the same information from calling `size` on the return value of `json_query` as you would from calling `is_strict_single_match()`.
