### ISSUE TITLE
error in query

### ISSUE THREAD

**Issue by AndreyAlifanov** [danielaparker/jsoncons#83]
We realized error in json_query.

Query **$..book[(@.length-1)]** returns wrong results on test file [json.zip](https://github.com/danielaparker/jsoncons/files/436318/json.zip)

It should return two last books, but returns two second ones.

We expect:
_[{
  'category' => "fiction"
  'author' => "J. R. R. Tolkien"
  'title' => "The Lord of the Rings"
  'isbn' => "0-395-19395-8"
  'price' => "22.99"
},
[
  'category' => "fiction"
  'author' => "Rotov K.K."
  'title' => "The Lord of the Rings"
  'isbn' => "0-395-19395-8"
  'price' => "22.99"
}]_

But we get:
_[{
	"category": "fiction",
	"author": "Evelyn Waugh",
	"title": "Sword of Honour",
	"price": 12.99
},
{
	"category": "fiction",
	"author": "Tretyakovskiy R",
	"title": "Sword of Honour",
	"price": 12.99
}]_

**Comment by danielaparker** [comment]
Fixed in master

**Comment by AndreyAlifanov** [comment]
now error with query **$..[0].author** - it returns empty array
but should return two first authors

**Comment by danielaparker** [comment]
Fixed on master

**Comment by AndreyAlifanov** [comment]
Query sometimes returns extra arrays.

For example, query **$..newsLinks** returns:
**[**[{ ... }]**]**

It would be nice, if query returned no extra arrays. I expect result:
[{ ... }]

Test file:
[news.zip](https://github.com/danielaparker/jsoncons/files/441647/news.zip)

**Comment by danielaparker** [comment]
I think [[{ ... }]] is expected behaviour for this query, though. 

Comparing with [ JsonPath Evaluator ](http://jsonpath.herokuapp.com/), [Jayway](https://github.com/jayway/JsonPath), [Gatling](https://github.com/gatling/jsonpath) and Goesnner return [[{ ... }]], except [Nebhale](https://github.com/nebhale/JsonPath) returns [{ ... }].

**Comment by danielaparker** [comment]
Comparing with [ JsonPath Evaluator ](http://jsonpath.herokuapp.com/), I noticed that there's a difference between Jayway and Goesnner with respect to union. With Jayway, you can write

 $.newsLinks..['title','url','publishedDate','itemNumber']

and get
```
[
   {
      "title" : "Изменения в движении автобусов маршрутов №№ 7, 41 и 60",
      "url" : "http://www.gortransperm.ru/news/520",
      "publishedDate" : "2016-08-16",
      "itemNumber" : 1
   },
   {
      "title" : "Новое расписание на автобусном маршруте №38",
      "url" : "http://www.gortransperm.ru/news/519",
      "publishedDate" : "2016-08-11",
      "itemNumber" : 2
   },
...
```
which I think is what you want.

With Goesnner, on the other hand, you get 
```
[
   "Изменения в движении автобусов маршрутов №№ 7, 41 и 60",
   "http://www.gortransperm.ru/news/520",
   "2016-08-16",
   1,
   "Новое расписание на автобусном маршруте №38",
   "http://www.gortransperm.ru/news/519",
   "2016-08-11",
   2,
   "Новое расписание движения на автобусных маршрутах №№34, 48, 77",
   "http://www.gortransperm.ru/news/518",
   "2016-07-21",
   3,
...
```

**Comment by AndreyAlifanov** [comment]
ok, thank you for information
