### ISSUE TITLE
How to use the union operator in the query

### ISSUE THREAD

**Issue by amitnaik1** [danielaparker/jsoncons#84]
Hi Daniel,

Thanks for the library. I am trying to use the lib in filtering the JSON to get only certain values. Consider a JSON string like this:
```
{
  "firstName": "John",
  "lastName" : "doe",
  "age"      : 26,
  "address"  : {
    "streetAddress": "naist street",
    "city"         : "Nara",
    "postalCode"   : "630-0192"
  },
  "phoneNumbers": [
    {
      "type"  : "iPhone",
      "number": "0123-4567-8888"
    },
    {
      "type"  : "home",
      "number": "0123-4567-8910"
    }
  ]
}
```

I just want firstname and lastname in the result

I tried the expression 
`json result = json_query(testjson, "$[firstName,lastName]");`

I get an empty array.

On debugging the code I saw that when the expression is evaluated the find_elements() function only checks array types for the '[' brackets. I just want to know if I have my expression wrong. I did verify the expression at http://jsonpath.com/ and it worked fine.

Thanks,
Amit

**Comment by danielaparker** [comment]
Fixed in master

**Comment by danielaparker** [comment]
The [Stefan Goessner spec](http://goessner.net/articles/JsonPath/) implies that member names inside square brackets should be enclosed in single quotes. 
```
http://jsonpath.com/ allows
```
```
$[firstName],$[`firstName`], and in fact $[`firstName] and $[firstName']
```
for firstName lookup,

but inconsistently does not allow 
```$['firstName','lastName']``` (in fact treats the single quote as part of the string name.)

`jsoncons` currently allows:
```
json result = json_query(testjson, "$[firstName,lastName]");
```
// quoteless names, if the name starts with an alphabetical character or underscore, may contain spaces
```
json result = json_query(testjson, "$['firstName','lastName']");
```
// single quoted names
```
json result = json_query(testjson, "$[\"firstName\",\"lastName\"]");
```
// double quoted names

**Comment by amitnaik1** [comment]
Thanks ! that worked :) 

Ok another example query to to access within an object

`json result = json_query(testjson, "$['firstName','address.city']");`

I am not sure if this is valid in a union but does not seems wrong, I tried with the double quotes as well.

The below one does work

`json result = json_query(testjson, "$['firstName','address']");`

**Comment by danielaparker** [comment]
I think you need to do that with two queries:

        std::string path1 = "$['firstName','address']";
        json result1 = json_query(testjson, path1);

        std::string path2 = "$.[0,'city']";
        json result2 = json_query(result1, path2);

The second query doesn't return what I expect, though, will investigate.

**Comment by danielaparker** [comment]
Actually, you can do it with one query using recursive descent,

$..['firstName','city']

**Comment by danielaparker** [comment]
jsoncons v0.123.0 now allows union of completely separate paths are allowed, including

    $[firstName,address.city]
