### ISSUE TITLE
Errors while compiling in VS2015 with 4-th warnings level

### ISSUE THREAD

**Issue by AndreyAlifanov** [danielaparker/jsoncons#85]
We use 4-th warnings level and flag "Treats warnings as errors" is on.
We get several errors while compiling:

1>S:\DEV8-JSON\Mod\Cmn\JSONCons\jsoncons/json_parser.hpp(1370): error C2220: warning treated as error - no 'object' file generated (compiling source file Providers\DtJsonProvider.cpp)
****1>S:\DEV8-JSON\Mod\Cmn\JSONCons\jsoncons/json_parser.hpp(1370): warning C4456: declaration of 'd' hides previous local declaration (compiling source file Providers\DtJsonProvider.cpp)****
1>  S:\DEV8-JSON\Mod\Cmn\JSONCons\jsoncons/json_parser.hpp(1370): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings (compiling source file Providers\DtJsonProvider.cpp)
1>  S:\DEV8-JSON\Mod\Cmn\JSONCons\jsoncons/json_parser.hpp(1361): note: see declaration of 'd' (compiling source file Providers\DtJsonProvider.cpp)
1>  S:\DEV8-JSON\Mod\Cmn\JSONCons\jsoncons/json_parser.hpp(1358): note: while compiling class template member function 'void jsoncons::basic_json_parser<wchar_t>::end_integer_value(void)' (compiling source file Providers\DtJsonProvider.cpp)
1>  S:\DEV8-JSON\Mod\Cmn\JSONCons\jsoncons/json_parser.hpp(1293): note: see reference to function template instantiation 'void jsoncons::basic_json_parser<wchar_t>::end_integer_value(void)' being compiled (compiling source file Providers\DtJsonProvider.cpp)
1>  S:\DEV8-JSON\Mod\Cmn\JSONCons\jsoncons/json_reader.hpp(30): note: see reference to class template instantiation 'jsoncons::basic_json_parser<wchar_t>' being compiled (compiling source file Providers\DtJsonProvider.cpp)
1>  Providers\DtJsonProvider.cpp(290): note: see reference to class template instantiation 'jsoncons::basic_json_reader<wchar_t>' being compiled
**1>S:\DEV8-JSON\Mod\Cmn\JSONCons\jsoncons/json_parser.hpp(1391): warning C4456: declaration of 'd' hides previous local declaration (compiling source file Providers\DtJsonProvider.cpp)**
1>  S:\DEV8-JSON\Mod\Cmn\JSONCons\jsoncons/json_parser.hpp(1391): note: to simplify migration, consider the temporary use of /Wv:18 flag with the version of the compiler with which you used to build without warnings (compiling source file Providers\DtJsonProvider.cpp)
1>  S:\DEV8-JSON\Mod\Cmn\JSONCons\jsoncons/json_parser.hpp(1382): note: see declaration of 'd' (compiling source file Providers\DtJsonProvider.cpp)
**1>s:\dev8-json\mod\cmn\jsoncons\jsoncons_ext\jsonpath\jsonpath_filter.hpp(426): warning C4265: 'jsoncons::jsonpath::value_term<Json>': class has virtual functions, but destructor is not virtual**

and so on...

Please, fix code with warnings.

**Comment by danielaparker** [comment]
Fixed
