### ISSUE TITLE
Problems in code from static analyzer log

### ISSUE THREAD

**Issue by AndreyAlifanov** [danielaparker/jsoncons#87]
Our static analyzer tool ([PVS-Studio](http://www.viva64.com/en/pvs-studio)) found these errors in code:

V517 The use of 'if (A) {...} else if (A) {...}' pattern was detected. There is a probability of logical error presence. Check lines: 268, 313. output_format.hpp 268
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: length_or_precision_, value_. json.hpp 348
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: length_or_precision_. json.hpp 405
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: length_or_precision_. json.hpp 417
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: length_or_precision_. json.hpp 429
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: length_or_precision_, value_. json.hpp 435
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: length_or_precision_. json.hpp 440
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: length_or_precision_. json.hpp 452
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: length_or_precision_. json.hpp 458
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: depth_. jsonpath_filter.hpp 709
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: original_precision_. json_serializer.hpp 80
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: original_precision_. json_serializer.hpp 88
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: original_precision_. json_serializer.hpp 96
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: original_precision_. json_serializer.hpp 104
V730 It is possible that not all members of a class are initialized inside the constructor. Consider inspecting: cp2_, nesting_depth_, precision_, literal_index_. json_parser.hpp 97
V730 It is possible that not all members of a class are initialized inside the constructor. Consider inspecting: cp2_, nesting_depth_, precision_, literal_index_. json_parser.hpp 110

Can you fix it? Or I can provide pull request, if needed.

**Comment by danielaparker** [comment]
Fixed. Please let me know if I missed any.

**Comment by AndreyAlifanov** [comment]
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: value_. json.hpp 357
V730 It is possible that not all members of a class are initialized inside the constructor. Consider inspecting: value_. json.hpp 368
V730 It is possible that not all members of a class are initialized inside the constructor. Consider inspecting: value_. json.hpp 374
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: value_. json.hpp 446
V730 Not all members of a class are initialized inside the constructor. Consider inspecting: start_, end_, step_, positive_start_, positive_end_, positive_step_, ... json_query.hpp 156

**Comment by danielaparker** [comment]
Thanks. I'm currently away on vacation, but will look at these when I return.

**Comment by danielaparker** [comment]
Fixed, I think.

**Comment by danielaparker** [comment]
The 'parse_exception' class and  'token'  '=' operator class warnings should be fixed.

The iterator warnings I'll have to revisit sometime, they have a  templated constructor that is designed to support non-const to const initialization, this gets in the way of a pure copy constructor, but the warnings are benign.

**Comment by AndreyAlifanov** [comment]
Ok.
These errors have low priority, because there are many false positives in such diagnostics.
I close issue, thanks for fixing.
