### ISSUE TITLE
another error in jsonpath

### ISSUE THREAD

**Issue by AndreyAlifanov** [danielaparker/jsoncons#89]
Query "**$..about[0]**" returns empty value.
But should return first letter in **about** member.

Test file: [test.zip](https://github.com/danielaparker/jsoncons/files/473991/test.zip)

**Comment by danielaparker** [comment]
Fixed. Index i applied to a string will return the i'th codepoint in the string, converted into a json string value. Also, Query "$..about.length" will return the length of the string in codepoints.

**Comment by AndreyAlifanov** [comment]
$..about[0], $..about[1] ... $..about[13], and so on - return same results.
Query $..about.length is very slow. I have real file about 5K records (test.json is a very little part of it). Query $..about (and $..about[0]) return result quickly (less than one second), but $..about.length takes several minutes.

**Comment by danielaparker** [comment]
Something is amiss!

On my Windows 10 notebook, I get the following results with the code on master and test.json:

```c++
#include "jsoncons/json.hpp"
#include "jsoncons_ext/jsonpath/json_query.hpp"
#include <chrono>

int main() 
{
    json val = json::parse_file("json/test.json");

    auto start = high_resolution_clock::now();
    json result1 = json_query(val, "$..about[0]");
    auto end = high_resolution_clock::now();
    auto elapsed = std::chrono::duration_cast<std::chrono::nanoseconds>(end - start).count();
    std::cout << "(1) " << result1 << " " << elapsed << " nanoseconds" << std::endl;

    start = high_resolution_clock::now();
    json result2 = json_query(val, "$..about[1]");
    end = high_resolution_clock::now();
    elapsed = std::chrono::duration_cast<std::chrono::nanoseconds>(end - start).count();
    std::cout << "(2) " << result2 << " " << elapsed << " nanoseconds" << std::endl;

    start = high_resolution_clock::now();
    json result3 = json_query(val, "$..about[2]");
    end = high_resolution_clock::now();
    elapsed = std::chrono::duration_cast<std::chrono::nanoseconds>(end - start).count();
    std::cout << "(3) " << result3 << " " << elapsed << " nanoseconds" << std::endl;

    start = high_resolution_clock::now();
    json result4 = json_query(val, "$..about.length");
    end = high_resolution_clock::now();
    elapsed = std::chrono::duration_cast<std::chrono::nanoseconds>(end - start).count();
    std::cout << "(4) " << result4 << " " << elapsed << " nanoseconds" << std::endl;
}
```
Output:
```
(1) ["I"] 590986 nanoseconds
(2) ["n"] 636827 nanoseconds
(3) ["c"] 479559 nanoseconds
(4) [347] 351206 nanoseconds
```
The results are as expected and all times are under a millisecond.

For comparison, could you run this program against both `test.json` and the real file?

Thanks,
Daniel

**Comment by AndreyAlifanov** [comment]
error in code

class selector has virtual functions, but destructor is not virtual

**Comment by danielaparker** [comment]
Thanks! virtual destructor fixed.
