### ISSUE TITLE
gcc doesn't compile code

### ISSUE THREAD

**Issue by AndreyAlifanov** [danielaparker/jsoncons#91]
jsoncons/jsoncons.hpp:177:78: error: operands to ?: have different types ‘std::pair<const char*, long unsigned int>’ and ‘std::pair<const char*, int>’

I think, it should be:
return (count == index) ? std::make_pair(p,len) : std::make_pair(it,0**UL**);

**Comment by danielaparker** [comment]
Thanks, fixed.

**Comment by AndreyAlifanov** [comment]
That's not all.

ERROR when compiling ...
In file included from jsoncons_ext/jsonpath/json_query.hpp:17:0,
jsoncons_ext/jsonpath/jsonpath_filter.hpp: In member function ‘jsoncons::jsonpath::jsonpath_filter_expr jsoncons::jsonpath::jsonpath_filter_parser::parse(const char_type*, size_t, const char_type**)’:
jsoncons_ext/jsonpath/jsonpath_filter.hpp:924:22: error: ‘expr’ was not declared in this scope

Please, fix it. It should be **this->expr**, as I guess.

**Comment by danielaparker** [comment]
Fixed
