### ISSUE TITLE
ubuntu 16.04 compilation issues

### ISSUE THREAD

**Issue by alexkreimer** [danielaparker/jsoncons#92]
akreimer@akreimer-desktop:~/tmp/jsoncons/examples/build/cmake/debug$ cmake ..
-- The CXX compiler identification is GNU 5.4.0
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Configuring done
-- Generating done
-- Build files have been written to: /home/akreimer/tmp/jsoncons/examples/build/cmake/debug
akreimer@akreimer-desktop:~/tmp/jsoncons/examples/build/cmake/debug$ make
Scanning dependencies of target jsoncons_examples
[ 12%] Building CXX object CMakeFiles/jsoncons_examples.dir/home/akreimer/tmp/jsoncons/examples/src/json_any_examples.cpp.o
In file included from /home/akreimer/tmp/jsoncons/examples/build/cmake/../../../src/jsoncons/json_traits.hpp:15:0,
                 from /home/akreimer/tmp/jsoncons/examples/build/cmake/../../../src/jsoncons/json.hpp:19,
                 from /home/akreimer/tmp/jsoncons/examples/src/json_any_examples.cpp:5:
/home/akreimer/tmp/jsoncons/examples/build/cmake/../../../src/jsoncons/output_format.hpp: In member function ‘jsoncons::block_options jsoncons::basic_output_format<CharT>::array_array_block_option()’:
/home/akreimer/tmp/jsoncons/examples/build/cmake/../../../src/jsoncons/output_format.hpp:87:85: error: could not convert ‘((jsoncons::basic_output_format<CharT>*)this)->jsoncons::basic_output_format<CharT>::array_array_split_lines_’ from ‘jsoncons::line_split_kind’ to ‘bool’
         return array_array_split_lines_ ? block_options::next_line : block_options::same_line;
                                                                                     ^
/home/akreimer/tmp/jsoncons/examples/build/cmake/../../../src/jsoncons/output_format.hpp: In member function ‘jsoncons::block_options jsoncons::basic_output_format<CharT>::array_object_block_option()’:
/home/akreimer/tmp/jsoncons/examples/build/cmake/../../../src/jsoncons/output_format.hpp:98:86: error: could not convert ‘((jsoncons::basic_output_format<CharT>*)this)->jsoncons::basic_output_format<CharT>::array_object_split_lines_’ from ‘jsoncons::line_split_kind’ to ‘bool’
         return array_object_split_lines_ ? block_options::next_line : block_options::same_line;
                                                                                      ^
/home/akreimer/tmp/jsoncons/examples/build/cmake/../../../src/jsoncons/output_format.hpp: In member function ‘jsoncons::block_options jsoncons::basic_output_format<CharT>::object_array_block_option()’:
/home/akreimer/tmp/jsoncons/examples/build/cmake/../../../src/jsoncons/output_format.hpp:109:86: error: could not convert ‘((jsoncons::basic_output_format<CharT>*)this)->jsoncons::basic_output_format<CharT>::object_array_split_lines_’ from ‘jsoncons::line_split_kind’ to ‘bool’
         return object_array_split_lines_ ? block_options::next_line : block_options::same_line;
                                                                                      ^
/home/akreimer/tmp/jsoncons/examples/build/cmake/../../../src/jsoncons/output_format.hpp: In member function ‘jsoncons::block_options jsoncons::basic_output_format<CharT>::object_object_block_option()’:
/home/akreimer/tmp/jsoncons/examples/build/cmake/../../../src/jsoncons/output_format.hpp:120:87: error: could not convert ‘((jsoncons::basic_output_format<CharT>*)this)->jsoncons::basic_output_format<CharT>::object_object_split_lines_’ from ‘jsoncons::line_split_kind’ to ‘bool’
         return object_object_split_lines_ ? block_options::next_line : block_options::same_line;
                                                                                       ^
CMakeFiles/jsoncons_examples.dir/build.make:62: recipe for target 'CMakeFiles/jsoncons_examples.dir/home/akreimer/tmp/jsoncons/examples/src/json_any_examples.cpp.o' failed
make[2]: *** [CMakeFiles/jsoncons_examples.dir/home/akreimer/tmp/jsoncons/examples/src/json_any_examples.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/jsoncons_examples.dir/all' failed
make[1]: *** [CMakeFiles/jsoncons_examples.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by danielaparker** [comment]
Thanks for reporting this! It should be fixed on master.
