### ISSUE TITLE
test_suite compilation error

### ISSUE THREAD

**Issue by rychale** [danielaparker/jsoncons#95]
`In file included from /home/arychkov/git/jsoncons/test_suite/src/json_type_traits_stl_tests.cpp:6:0:
/home/arychkov/git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp: In instantiation of ‘jsoncons::basic_json<CharT, JsonTraits, Allocator>::basic_json(const T&) [with T = std::array<long unsigned int, 4ul>; CharT = char; JsonTraits = jsoncons::json_traits<char>; Allocator = std::allocator<char>]’:
/home/arychkov/git/jsoncons/test_suite/src/json_type_traits_stl_tests.cpp:216:25:   required from here
/home/arychkov/git/jsoncons/test_suite/build/cmake/../../../src/jsoncons/json.hpp:1807:54: error: ‘to_json’ is not a member of ‘jsoncons::json_type_traits<jsoncons::basic_json<char, jsoncons::json_traits<char>, std::allocator<char> >, std::array<long unsigned int, 4ul>, void>’
         : var_(json_type_traits<json_type,T>::to_json(val).var_)
`

**Comment by danielaparker** [comment]
What compiler/platform are you using?

If you comment out lines 215-220 in json_type_traits_stl_tests.cpp, does the rest compile?

Thanks,
Daniel

**Comment by rychale** [comment]
Yes, commenting out lines 215-220 fixed the issue.

I use gcc 5.1.1 on CentOS 7.2.1511.

Kind regards,
Alexey

**Comment by rychale** [comment]
It is fixed, thanks.
